### ISSUE TITLE
bufr2ioda.x does not work for prepbufr yaml for two cases 

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#1020]
## Current behavior (describe the bug)
The bufr2ioda.x built from feature/query_cxx_types and yaml files are used to produce ioda netCDF files. The prepbufr data (gdas.t12z.prepbufr) is subset  into adpsfc, adpupa, aircar, aircft, and sfcshp prepbufr data. The bufr2ioda.x works well for each individual subset prepbufr data when wildlcart (*) in yaml file is used. However, the first case is that when a given subset name is used in yaml file, eg., ADPSFC, the dimension name definition does not work, it automatically use dim_2.  The second case is that when full prepbufr file is used as an input, even yaml file uses a given subset names, bufr2ioda.x cannot produce correct netCDF file (it seems to have more Locations numbers).

- dimension name issue
- extract correct subset data from a full prepbufr data file

## To Reproduce

On Hera

source modulefile.iodaconv.query.hera.csh in /scratch1/NCEPDEV/da/Youlong.Xia/test

1.  In /scratch1/NCEPDEV/da/Youlong.Xia/test/bufrCloud/yaml, there are 4 examples (test1.yaml, test2.yaml, test2a.yaml, test2b.yaml): test1 uses a given subset name and full prepbufr data; test2 uses subset adpsfc prepbufr file and wildcart (benchmark), and test2a is the same as test2 but with a given subset name, and test2b is the same test2a but only dimension name uses */
2. The outputs by ncdump from test2, test2a, and test2b are compared using diff. The test2a and test2b is the same. Test2 and test2a haave only difference   between CloudSequence and dim_2 but the data are the same.
...

## Expected behavior

An correct data should be extracted from full prepbufr data.

## Additional information (optional)

The work can be done via the first approach: (a) subset full prepbufr data into individual prepbufr files, (b) bufr2ioda.x produce the ioda netCDF files for each subsets, (c) all subset prepbufr file can be combined into a unified prepbufr file using cat command, and combined yaml file can work for the unified prepbufr file to produce the final ioda-based netCDF file (i.e., cloud). 

Hopefully the second approach can use the yaml file and full prepbufr data file (as input) to produce the final ioda-based netCDF file directly

**Comment by PraveenKumar-NOAA** [comment]
@YoulongXia-NOAA I had similar problem with BUFR subset too.

**Comment by YoulongXia-NOAA** [comment]
@PraveenKumar-NOAA, Thank you for finding the similar problem. As now Ron is very busy to merge his feature/query-cxx to the develop, we may need to wait.

**Comment by rmclaren** [comment]
@emilyhcliu @PraveenKumar-NOAA @YoulongXia-NOAA  @nicholasesposito I have a question. Is there a need to be able to specify dimension names specifically for a particular subset. So for example lets say we've got some sequence XYZ that happens inside several different types of subsets. Your dimensions section might look like this

```yaml
dimensions:
  - name: FirstDimension
    path: ADPSFC/XYZ
  - name: SecondDimension
    path: SATWND/XYZ
```

as apposed to just naming always naming the dimension the same thing (no matter the subset)

```yaml
dimensions:
  - name: MyDimension
    path: */XYZ
```

If there isn't s competing reasons to be able to support the former scenario I think I will just force everybody to use the more generic */XYZ path (basically specifying dim names specifically to a subset will not be allowed, at least until we discover a need for it). If this approach is OK, I will update print_queries and validate the path to make sure it starts with * for now.

**Comment by YoulongXia-NOAA** [comment]
Thank you @rmclaren . Happy to see the issue sloved.
