### ISSUE TITLE
bufr2ioda dimension issue with an input subset bufr file

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1031]
## Current behavior (describe the bug)
The bufr2ioda.x with a given YAML is used to produce ioda netCDF file using bufr/ prepbufr as an input file. A bufr file contains several subsets of bufr files, eg ADPUPA has six subsets NC002001-NC002005,and NC004005, and each one of them can be used as an input for bufr2ioda. 

While using a suset bufr file, bufr2ioda produces dimension name correctly in a netCDF file which are exported from the YAML, when a wildcard (*) is used at the beginning of the PATH in the dimension: 

YAML section: 
      dimensions:
        - name: RadiosondeReportLevelData
          path: "*/UARLV"
        - name: RadiosondeCloudData
          path: "*/UACLD"

netCDF output: 
dimensions:
        Location = 643 ;
        RadiosondeCloudData = 3 ;
        RadiosondeReportLevelData = 255 ;

However,  when a subset name is used at the beginning of the path, the dimension name definition does not work and it automatically produces a default name like dim_2, dim_3, etc. 

YAML section: 
      dimensions:
        - name: RadiosondeReportLevelData
          path: "NC002001/UARLV"
        - name: RadiosondeCloudData
          path: "NC002001/UACLD"

netCDF output: 
dimensions:
        Location = 643 ;
        dim_2 = 255 ;
        dim_3 = 3 ;

Dimension naming issue from a YAML.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## To Reproduce

-Used Hera
-Used modules from the following file: ~/Praveen.Kumar/JEDI/env_ioda-bundle.sh 
-Steps to reproduce the behavior
1. Run bufr2ioda for the following YAML: ~/Praveen.Kumar/JEDI/IODA_CONVR_ADPUPA_BUFR_2020110112/bufr_ncep_adpupa_nc002001.yaml using two different paths in dimension section: */UARLV and NC002001/UARLV

## Expected behavior
Export the dimension name(s) from the YAML into the netCDF file.

**Comment by PraveenKumar-NOAA** [comment]
@YoulongXia-NOAA posted the same kind of bug for the prepbufr input.

**Comment by rmclaren** [comment]
Please see #1020.

**Comment by rmclaren** [comment]
Fixed by PR https://github.com/JCSDA-internal/ioda-converters/pull/1040

**Comment by PraveenKumar-NOAA** [comment]
@rmclaren thank you.
