### ISSUE TITLE
BUFR IODA: Add ability to add source field to dimension declarations.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#1041]
## Description

It's desirable to be able to add the ability to have a source field on the dimension parameters. For example you might want to associate dimension information with Channels so that you can correlate data at a position with a channel number which is derived from another BUFR variable. As long as the source data numbers (like channels for example) just repeat the same way for each message this should be feasible without too much trouble. So basically we will need a process by which we validate the sources data and then associate it correctly with the dimension data.

## Requirements

dimension dictionary will be extended with a `source` parameter that points to a source field in the BUFR file. The netcdf output will then annotate the dimension fields with this data.

An example for the dimensions field will look like this:

```yaml
dimensions:
  - name: Channel 
    path: "*/BRITCSTC"
    source: variables/channelNumber
```

The `source` field is new.

**Comment by rmclaren** [comment]
Branch: feature/query_labeled_dims

**Comment by gthompsnJCSDA** [comment]
@rmclaren I gave this issue an estimate of 8, which translates to 4 days of work.  Please change as you believe the level of effort to be more or less. Thanks for making this an issue and working on this very useful item.
