### ISSUE TITLE
Create ioda-converter for CrIS satellite radiance to brightness temperature

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#1045]
## Description
CrIS hyperspectral satellite radiance data begin as scaled radiance with different scaling factors for specific ranges of channel numbers.  To use in DA, we need to convert from the scaled to unscaled radiance values then to brightness temperature.  The VariableTransform for these two steps are implemented/available in UFO.  The ioda-converter, however, either needs to be written as a new application or use the ```feature/query_cxx``` branch of Ron McLaren's bufr2ioda converter.  Since this feature branch is not yet merged to develop, there is a risk it will not be merged in time to use it.

### Dependencies:
[ioda-converters PR 1006](https://github.com/JCSDA-internal/ioda-converters/pull/1006)
[ioda-converters issue 1041](https://github.com/JCSDA-internal/ioda-converters/issues/1041)

**Comment by BenjaminRuston** [comment]
Greg since we have IASI in R2D2 we should close and open something new when next round of conversion starts
