### ISSUE TITLE
Possible bug with the size of "size" when querying a bufr with multiple subtypes

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#1047]
## Description
When converting some aircraft bufr files using my new aircraftAltitude variable from #997 with yamls that only need some subtypes' worth of data, the software, while it grabs the needed information, grabs extra data that it is not supposed to be looking for and makes it "missing" data. For example, using the bufr_d file with my "noamdar" yaml, it should look for NC004001, 2, 3, 6, 9, 10, and 11, for a total of 18367 data points. NC004103 is also in the bufr_d file and has 8455 data points, which the "size" function "sees" and adds to the total number of data points. The number of total data points is 26822 in the output nc file, which is the total of all the above. 

I've been looking through Ron's code and my branch. I think the problem is that the "size" of the latitude array is too large. It appears that it finds every latitude but does not quantify them, leaving them as "missing", but still including them in the "size"

The good news is that none of the output data is affected. For all of the "extra" data( including lat, lon, aircraftAltitude and whatever else), it defaults to missing with a dateTime variable of "-1". What do we want to do about this?

The iodaconv branch I've been using is:
feature/query_cxx_types_NE_aircraftAltitude
with the changes/additions being made in:
iodaconv/src/bufr/BufrParser/Exports/Variables

My yamls are in:
/scratch1/NCEPDEV/da/Nicholas.Esposito/JEDI/testnewbufr2ioda/
and the yamls that make the bad data are:
newNOAM.yaml    (amdar with NC specification)
newNCnoAM.yaml  (no amdar with NC specification)
newNOAM.yaml         (no amdar without NC speficiation)

## Requirements
This may be a bugfix? If it is, then the fix would not add data where dateTime is -1 and the rest of the data is missing.

## Acceptance Criteria (Definition of Done)
It is finished once 
[ ] There is an explanation
[ ] There is a fix

**Comment by rmclaren** [comment]
Fix in feature/query_datetime_subset_fix
