### ISSUE TITLE
Create CALIPSO L2 IODA converter

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/ioda-converters#1051]
@jeromebarre commented on [Fri Sep 16 2022](https://github.com/JCSDA-internal/AOP22/issues/182)

**Comment by jeromebarre** [comment]
This is going to the next AOP

**Comment by gibbsp** [comment]
Removing link to unknown Epic, and moving this issue to icebox.

**Comment by jeromebarre** [comment]
closing this for now until shih wei will work on this

**Comment by SarahLu-NOAA** [comment]
@jeromebarre @weiwilliam 
Not intended to re-open #1051.  I have the impression that Shih-Wei has completed IODA converter for CALIOP L1 and L2.

**Comment by jeromebarre** [comment]
not in the repo,
https://github.com/JCSDA-internal/ioda-converters/tree/develop/src/compo
this can be PRed but the format and code will be outdated. It will be worth
to work on this when we are ready for this.

**Comment by weiwilliam** [comment]
@SarahLu-NOAA, Yes, like @jeromebarre said, the format is outdated.
We'll revisit it when the operator is ready. 
Later we can make the 2d array structure in the converter.
