### ISSUE TITLE
Add observation depth to SMAP soil moisture IODA converter 

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [JCSDA-internal/ioda-converters#1068]
## Description

For UFS issue 1752 we are adding the ability to do soil level interpolation, so that the UFS can simulate the soil moisture over the same depths as is observed.  See https://github.com/JCSDA-internal/ufo/issues/1752

To do this, we need to add a vertical observation depth to the SMAP IODA files.

@YoulongXia-NOAA can you please add an observed depth variable to the SMAP soil moisture IODA converters? For sondes, there is a metadata field called height (in m). @fcvdb @BenjaminRuston @huishao-r : I assume we want to do the same? 

The depth of all observations should be 2.5 cm. (observed depth is approximately 0-5 cm layers, so giving the middle point will be most consistent with the UFO's point-based interpolation routines).

This is Task 2 of the UFO issue linked above.

## Requirements

No new dependencies. Success is the observation depth being added to the SMAP soil moisture IODA converter.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, based on ioda conventional table, a variable is defined as depthBelowSoilSurface. It fits to 0.025 m.

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA and @ClaraDraper-NOAA who wrote the converter?  

I see these two are these the ones to look at:

smap9km_ssm2ioda.py
smap_ssm2ioda.py

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, I wrote these two converters.  This is the reason @ClaraDraper-NOAA  assign this task to me.

**Comment by YoulongXia-NOAA** [comment]
Than you for assigning me this task, @ClaraDraper-NOAA. I will work to add soil depth in both SMAP converters.  Yesterday I cannot build iod-bundle on hera by using ioda and iodaconv develop branch, asking my colleagues to help.  When I have a test, I will create a PR for your review.
