### ISSUE TITLE
common converters use single calling structure

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#1069]
put a family of converters under a single calling structure to allow a more consistent experience when converting data

**Comment by gibbsp** [comment]
@BenjaminRuston Can we update this issue for release 2? What is the status?

**Comment by BenjaminRuston** [comment]
@gibbsp was letting infrastructure team finish release, pulling the thread

**Comment by BenjaminRuston** [comment]
closed with #1161
