### ISSUE TITLE
Create a simple composite of WMO Block and Station numbers (BUFR) into 5-character string for station_id

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#1074]
## Description

In BUFR input data, the year, month, day, etc. is each in a separate mnemonic/variable and the ```timestamp``` construct was used to create a simpler ```dateTime``` variable needed in IODA (e.g., 2019-11-24T11:34:29Z).  In a similar context, the WMO 2-digit block number comes as one BUFR variable and the 3-digit station number comes as another variable.  We should create a compositing routine to combine the two items into a 5-character string with possible leading zero digit for the ```station_id``` that nearly all UFO software requires.

## Requirements

Given WMO block number = 72 and station number 403, we need a variable ```station_id``` that is 5-characters: ```72403```.  However, we need to consider leading zero digits since WMO block number 1 is Norway, so the final variable should be a simple ```sprintf("%02d", WMO-block-number)``` concatenated with ```sprintf("%03d", WMO-station-number)```

## Acceptance Criteria (Definition of Done)
Meets requirements, reviews accepted, passing ctests.

## Dependencies
None

**Comment by BenjaminRuston** [comment]
@gthompsnJCSDA seems like still working on this, moving to a new epic as shutting down OBSPROC-47

**Comment by BenjaminRuston** [comment]
@rmclaren is this issue still relevant or has the work to moved to another branch and issue

**Comment by rmclaren** [comment]
@BenjaminRuston Yes, I believe this issue is still relevant. Ultimately @gthompsnJCSDA should decide.

**Comment by BenjaminRuston** [comment]
@gthompsnJCSDA then this must be the whole WIGOS identifier discussion

will discuss and see if we need to create a different or modify the title of the issue

**Comment by gthompsnJCSDA** [comment]
With @rmclaren  newer python interface to bufr2ioda, is that not a trivial matter that needs about 2 lines of python code for either the combination of WMO numbers (i.e., WMO block 72 and station ID 201 turned into `72201` which is Miami, FL by the way) or the WIGOS id such as `01-234abcd-287-98`?

**Comment by rmclaren** [comment]
I agree this is very easy to do with python. It makes sense to make a built in compenent if you are worried about consistency, and supporting it in the YAML interface. We can play it by ear if you want.

**Comment by BenjaminRuston** [comment]
@rmclaren where is this at now with the script backend to IODA is this now possible, in short is this issue still open or can be closed

**Comment by gthompsnJCSDA** [comment]
> @rmclaren where is this at now with the script backend to IODA is this now possible, in short is this issue still open or can be closed

I am not certain but I thought @PraveenKumar-NOAA may have added this to the code base in C++ already.  If not, then I don't think it's done until we can show it with a stand-alone ioda-converter that does what is described in a file-input to file-output test; because not everyone will necessarily want the in-memory converter by itself.

**Comment by PraveenKumar-NOAA** [comment]
@gthompsnJCSDA yes, you are correct. This is done and already merged. 
@BenjaminRuston @rmclaren we can close this issue.
