### ISSUE TITLE
Adopt newer ```Query``` method for ```bufr2ioda.x``` for various converters (list in description)

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#1077]
## Description
When Ron McLaren's ```feature/query_cxx``` branch was merged to develop, some YAML files were left out of the updating, particularly those using WMO-formatted BUFR rather than prepBUFR. The files that were skipped are now bypassed in the ctests.  This issue is created to resolve those gaps and re-enable all prior ctests, therefore the YAML files as well as the test reference files need to be updated.

This work is undertaken within the ```feature/greg_fix_query``` branch

The list of YAML files that need updating (each is associated with a ctest and a testoutput file):

### Files:
- [x] aircar_bufr2ioda.yaml
- [x] airep_wmoBUFR2ioda.yaml
- [ ] amdar_wmoBUFR2ioda.yaml
- [x] buoy_wmoBUFR2ioda.yaml
- [x] gnssro_wmoBUFR2ioda.yaml
- [x] rass_wmoBUFR2ioda.yaml
- [ ] ship_wmoBUFR2ioda.yaml
- [ ] synop_wmoBUFR2ioda.yaml
- [x] satwind_EUMet_wmoBUFR2ioda.yaml
- [x] satwind_Himawari_wmoBUFR2ioda.yaml
- [x] satwind_Insat_wmoBUFR2ioda.yaml
- [ ] vadwinds_wmoBUFR2ioda.yaml

## Requirements

Re-enabling the commented out ctests must now pass using the updated YAML and testoutput files.

## Acceptance Criteria (Definition of Done)
Success on ctests and positive reviews

## Dependencies

#1084

**Comment by gthompsnJCSDA** [comment]
@rmclaren   I tagged you in my issue only as a reminder of which of the WMO-formatted bufr files cause ```bufr2ioda.x``` to fail.  Could you please put in the dependent issue for which you are making the code changes to fix the problem?

**Comment by BenjaminRuston** [comment]
@gthompsnJCSDA is this one to pick back up, or close and open a new issue?

**Comment by symoore90** [comment]
which epic can I connect this issue to? @gthompsnJCSDA

**Comment by BenjaminRuston** [comment]
think this can be closed now.. most of these converters are done and they aren't tied to this issue any more.
