### ISSUE TITLE
Test and implement possible changes for the OMPS O3 converter

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/ioda-converters#1085]
## Description
Test and run the OMPS converter for O3 columns https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/ompsnm_o3_nc2ioda.py

If needed, implement the necessary changes to have this working with `ColumnRetrieval` operator in UFO.
yaml examples can be found in https://github.com/JCSDA-internal/ufo/blob/develop/test/testinput/unit_tests/operators/tropomi_no2.yaml

Operator https://github.com/JCSDA-internal/ufo/tree/develop/src/ufo/operators/atmvertinterplay needs to be phased out and replaced by the more general column operator for all L2 nadir retrievals
https://github.com/JCSDA-internal/ufo/tree/develop/src/ufo/operators/columnretrieval

Units option to have mol.m-1 or DU could be implemented see https://github.com/JCSDA-internal/ioda-converters/issues/1019 for details

**Comment by BenjaminRuston** [comment]
@jeromebarre this moving to IceBox.  Is this is still the current issue for this work?

IODA PR has been merged, shifting effort toward use of FORTRAN API with composition data

**Comment by jeromebarre** [comment]
@SarahLu-NOAA has not made progress on this. This is a low priority issue. Removing this for the skylab v4 release. @BenjaminRuston not sure I understand the link with IODA PR and the fortran API. Those are independent from this.

**Comment by jeromebarre** [comment]
finished with https://github.com/JCSDA-internal/ufo/commit/b285fd5dc6b1e86e3c5858231fc1522ac8ef35ac
@SarahLu-NOAA
