### ISSUE TITLE
Bufr2ioda can not handle bufr variables for more than ONE-dimension

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1088]
## Description

- There are only three time-related mnemonics in ADPUPA/prepbufr named DHR, RPT, and HRDR, which report time in HOURS. The variables DHR and RPT are ONE-dimensional, while HRDR is TWO-dimensional. For HRDR, the first dimension is for location and the second is for level as the sonde ascends. Hence, HRDR is needed to be used in the creation of the IODA DateTime variable. 

- Most time variables in BUFR are ONE-dimensional, but for ADPUPA/prepbufr HRDR a new functionality is required in the DateTime.cpp/ or related codes where the code(s) is checking for more than ONE-dimension variable. 

- Related issues (#945, #975)

## Requirements

- There are no requirements. 

## Acceptance Criteria (Definition of Done)

- Reads BUFR time variables for more than ONE-dimension and runs successfully _bufr2ioda.x_. 

## Dependencies

- There are no dependencies.

**Comment by gthompsnJCSDA** [comment]
I am pretty certain this can now be closed.  Ron resolved this via the work of PR #1090 and most BUFR mnemonics were already working correctly in 2D except the elements going into ```dateTime```, therefore I am closing this issue.  Re-open if you believe it is an error to close it.

**Comment by PraveenKumar-NOAA** [comment]
Good, thanks.
