### ISSUE TITLE
NOAA EMC BUFR Converter for AOP22

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#1101]
## Description
This Epic contains EMC contributions to the BUFR converter in the following two categories for AOP22
- [BUFR Converter - Functionality Enhancement (Code Development)](https://github.com/JCSDA-internal/ioda-converters/issues/969)
- [BUFR Converter - YAML Development, Test and Validation](https://github.com/JCSDA-internal/ioda-converters/issues/1102)

## Requirements

>If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)
>If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)
>What does it mean for this to be finished?

## Dependencies
>What must be done before this can be done? Add issue dependencies in ZenHub as appropriate
>Does this block progress on other issues? Add this issue as a dependency to other ZenHub issues as appropriate

**Comment by BenjaminRuston** [comment]
@emilyhcliu do you agree let's just close this for now and will open issues as needed moving forward

**Comment by BenjaminRuston** [comment]
closing on @emilyhcliu advice and moving to new work to new issues
