### ISSUE TITLE
NOAA EMC BUFR Converter - YAML Development, Test, and Validation for AOP22

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#1102]
## Description
BUFR Converter development related to YAML development, Test, and Validation

## Requirements

>If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)
>If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)
>What does it mean for this to be finished?

## Dependencies
>What must be done before this can be done? Add issue dependencies in ZenHub as appropriate
>Does this block progress on other issues? Add this issue as a dependency to other ZenHub issues as appropriate

**Comment by BenjaminRuston** [comment]
@emilyhcliu maybe close this one as well, is this still being used or are you transferring to new epics

**Comment by BenjaminRuston** [comment]
closing this epic after discussion with @emilyhcliu new work will be assigned to more recent epics
