### ISSUE TITLE
Create IODA files for GOES data to use in Skylab_v3.0

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#1104]
## Description

Create IODA files from GOES data using Eric's python ioda-converter for time periods of 2021Aug01-31 and 2022Feb15-Mar15.
It will be ideal to have multi-resolution in space and time so we can test in a rigorous scientific way for which combination improves the obs-analysis.  However, the original resolution in space (about 2km) and time (full-disk scans about every 15 mins) is likely to overwhelm the storage capacity.  As a first set of data, resample to 8 km spacing and one dataset per hour.  See the sample image below for examples of Vis and IR taken from original netCDF files and after the resampling.

## Acceptance Criteria (Definition of Done)
Completion of the data processing for targeted 30-day windows

## Dependencies
None

## Example 1:  Visible (channel 1) GOES-16 image in center from original NetCDF file and after resampling both GOES-18 (left) and GOES-16 (right)
<img width="3100" alt="GOES_combo1" src="https://user-images.githubusercontent.com/63315545/199735909-c9477b89-83da-429c-9d62-068e39407a4a.png">

## Example 2:  Infrared (channel 13) GOES-16 image in center from original NetCDF file and after resampling both GOES-18 (left) and GOES-16 (right)
<img width="3100" alt="GOES_combo2" src="https://user-images.githubusercontent.com/63315545/199735947-da6e4148-0bae-4a90-b124-26c51ba39bc3.png">

**Comment by BenjaminRuston** [comment]
@gthompsnJCSDA we'll want to close this or assign a new r2d2-ingest PR to it and close it then

**Comment by fabiolrdiniz** [comment]
Is it related to https://github.com/JCSDA-internal/r2d2-ingest/issues/14?
