### ISSUE TITLE
Python modules not properly installed 

### ISSUE THREAD

**Issue by fcvdb** [JCSDA-internal/ioda-converters#1159]
The` lib_python,` `gsi_ncdiag `and `wrfda_ncdiag` Python modules are not installed properly during the build of `ioda-converters`.

All the code ends up in the directory `<build>/lib/pyiodaconv`, while the other two modules `ioda`  `ioda_obs_space` are installed in `<build>/lib/python3.9/pyioda`. 

So they are not found at run time with the simple command:  
`export PYTHONPATH="<build>/lib/python3.9/pyioda:${PYTHONPATH}"`
That is usually applied.

The installation needs to be fixed. Meanwhile a quick fix can be:
```
export PYTHONPATH="<build>/lib/python3.9/pyioda:${PYTHONPATH}"
cd <build>/lib/python3.9/pyioda
ln -sf ../../pyiodaconv lib_python
ln -sf ../../pyiodaconv gsi_ncdiag
ln -sf ../../pyiodaconv wrfda_ncdiag
```

See also issue #1158

**Comment by CoryMartin-NOAA** [comment]
Yes, see my discussion at the end of #1087

**Comment by fcvdb** [comment]
Adding @fabiolrdiniz to the discussion.

**Comment by fcvdb** [comment]
adding @ericlingerfelt to the discussion.

**Comment by ericlingerfelt** [comment]
I am working with @PatNichols currently to resolve all of this.

**Comment by BenjaminRuston** [comment]
can we consolidate these three into a single:  `lib_jedi_python`  (or similar)

`lib_python`
`pyioda`
`pyiodaconv`

**Comment by srherbener** [comment]
I agree these should be consolidated into one path, which should be a standard python location. I believe that means: `<install-prefix>/lib/python<version>/site-packages`, where `<install-prefix>` is the build area as well as the CMAKE_INSTALL_PREFIX setting (ie, `make install` follows the same pattern).

**Comment by fcvdb** [comment]
Closing this issue. The [PR](https://github.com/jcsda-internal/ioda-converters/issues/1160) was temporarily reverted.
