### ISSUE TITLE
Capability to revert Antenna Temperature correction for AMSU-A and MHS

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#1172]
## Description
Add the capability of converting Antenna Temperature (TDR) to Brightness Temperature (SDR) for AMSU-A and MHS

**Comment by BenjaminRuston** [comment]
the AMSU-A converter is now working as you desire correct?

**Comment by BenjaminRuston** [comment]
@emilyhcliu you have converter working as desired or more work needed?

**Comment by PatNichols** [comment]
@emilyhcliu Can we close this one?

**Comment by BenjaminRuston** [comment]
@emilyhcliu believe this is completed and will close for now. Though you did just mention some slight differences when combining RARS data with the standard feed, think it is unrelated to this which has been completed
