### ISSUE TITLE
Better feedback for bad GroupBy specification.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#1175]
## Description
Users often misuse the Group By field in the YAML file as they don't understand when what they are asking is impossible. We need better validation to check to make sure that group by parameters are being applied under the correct circumstances in order to prevent a lot of user confusion.

## Requirements
Will throw an exception when attempting to use a group by field inappropriately.

## Acceptance Criteria (Definition of Done)
User will get an exception if they attempt to apply group by on data where this is not possible. The error message will clearly state what the problem is.

**Comment by BenjaminRuston** [comment]
@rmclaren closing this as believe PR #1176 closed this
