### ISSUE TITLE
Snow depth units are all mixed up

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [JCSDA-internal/ioda-converters#1178]
## Description

The snow depth units for IMS and GHCN are all mixed up. I haven't looked at the other snow depth data sets.

For the GHCN snow depth data:
1. The input data are in mm. 
2. The current converter (src/land/ghcn_snod2ioda.py) gives the output units as m, but does not convert the input data.  
3. On the other hand, my IODAv3 files that I converted from v2 files using ioda-upgrade-v2-to-v3.x still have the GHCN totalSnowDepth in mm (with correct values). 

For IMS snow depth data: 
1. The input data are in mm. Note, this unit is inherited from the background snwdph (or snodl), and the units are given incorrectly in some UFS files. I'm checking with Mike whether these units will change.
2. The current converter gives the output units as m, and divides the input by 1000. 
3. In my DA experiments, I'm getting incorrect output because the background is in mm, and the IMS snow depth is in m, and the assimilation is not converting any of the units.

## Requirements

Easiest solution: revert to having snow depth in units of mm in the IODA files. This requires correcting the GHCN metadata, and removing the unit conversion in IMS. 

More involved: if you're stuck on using units of m, we need to correct the GHCN converter to correctly output the data in m. I'll also need a way to tell JEDI that my input snow depth is in mm.

We should also check the GTS snow depth converter for similar issues.

## Acceptance Criteria (Definition of Done)

All snow depth values are in correct units

**Comment by BenjaminRuston** [comment]
@ClaraDraper-NOAA i'm leaning toward using `mm` as the unit and specify this correctly in the converter

not sure if SI is imposed through the UFO at this point for all observations, but happy to figure this one out

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA @BenjaminRuston, I will take a look today first. I did not touch them for several months. Thank you.

**Comment by ClaraDraper-NOAA** [comment]
@BenjaminRuston I'm on team mm too, as it's more common for snow depth. I checked with Mike Barlage (EMC Land Modeling Lead), and he said there are no plans to change this in the UFS. It gets a bit tricky as mm is kg/m2 for water so we can argue that both mm and m are SI.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, @BenjaminRuston, when I used ioda_validator.x to check snow depth, I argued as the uses would like to use mm rather than m, but they told me that in UFO part, it can be used to convert from m into mm. They asked me to change mm into m as requested. If we decided to change the unit from m back to mm, at least we need to let Greg and Stephen know.  If you decided, I can start to work for this reversing processing.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, I checked ghcn_snod2ioda.py  and imsfv3_scf2ioda.py in the develop branch of ioda-bundle,  I found mm was converted into m via the below line for ghcn_snod2ioda.py :
 
for i in range(len(vals)):
            if vals[i] >= 0.0:
                **errs[i] = 0.04
                vals[i] = 0.001*vals[i]**

For imsfv3_scf2ioda.py, it was converted in the line below:

        **errsd[:] = 0.08**
        ncd.close()

        times = np.empty_like(sncv, dtype=object)

        # get datetime from filename
        str_date = re.search(r'\d{8}', self.filename).group()
        my_date = datetime.strptime(str_date, "%Y%m%d")
        start_datetime = my_date.strftime('%Y-%m-%d')
        base_datetime = start_datetime + 'T18:00:00Z'

        for i in range(len(lats)):
            times[i] = base_datetime
            **sndv[i] = 0.001*sndv[i]**

I am not sure where you found the converters do not convert mm into m.  I did not recall that I mixed up my data processing from my converters. I may need more details.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA  - thank, I missed the conversion line in the GHCN converter. 

Note: it's the v2 to v3 converter that I used to convert my v2 GHCN snow depth to v3 did not change the unit (perhaps this was a namelist setting?). 

@BenjaminRuston  Regardless of what unit we go with here, we're going to have to have a way to easily address the case when the model uses a different unit.  Do you know if this exists yet?

**Comment by BenjaminRuston** [comment]
@ClaraDraper-NOAA there is going to be a VADER code sprint which should create standard for the models so we won't have different units for different models

now the model is `mm` so we are going with this is the idea correct?  after the VADER sprint we can potentially update if needed at that time

**Comment by ClaraDraper-NOAA** [comment]
@BenjaminRuston Do you mean that after the code sprint we'll be able to ingest output from models regardless of what unit the model has, or that JEDI is going to impose units on the models (and models will have to be re-coded to match those units)?

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, please let me know when VADER code sprint will be held so that I can attend. At least including me in email list. Thank you.

**Comment by BenjaminRuston** [comment]
@ClaraDraper-NOAA hah, this is right in the middle of what I"m working on now...

wonder if we should use this issue or create a new one

**Comment by YoulongXia-NOAA** [comment]
Ben,

Now land DA uses mm. But ioda converter unit convention asked me to use m
for validator. Can we change convention unit to mm or land DA users need to
use m. Please coordinate it. Thank you.

Youlog
================================================================
Youlong Xia, Ph.D
SAIC at EMC/NCEP
5830 University Research Court
College Park, MD 20740
Phone: 301-683-3696
=================================================================

**Comment by ClaraDraper-NOAA** [comment]
@BenjaminRuston Has the situation changes in anyway that make this issue out-dated (i.e., why create a new one?). What we need to do comes down to your answer to my question from 28 February: 

"Do you mean that after the code sprint we'll be able to ingest output from models regardless of what unit the model has, or that JEDI is going to impose units on the models (and models will have to be re-coded to match those units)?"

JEDI can do the DA in whatever unit it wants, but we need to update the converters to be consistent with that unit, and we need to have a mechanism for converting restarts if they're not in the expected unit.

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston and @ClaraDraper-NOAA, from my side, if I get a clear guidance, I would like to modify the converters and test them. Currently I have to consider two sides: on is from the user, and the second from ioda converter code sprint and its organizer. The later would like to use a unified convention table and unit controlled by obsspace yaml file.  This is the reason to lead to these mixed up. As you @BenjaminRuston is coordinating land converters,  this is a good chance to do something  before next code sprint.

**Comment by BenjaminRuston** [comment]
I'm asking the VADER folks as would naively think that you can leave the model histories alone and just have JEDI do the conversion for the I/O... will update as I go

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, okay, keep me updated. Thank you.

**Comment by BenjaminRuston** [comment]
@ClaraDraper-NOAA to wrap this up for now let's have the converter write out `mm` but going ahead and stating in the file that the units are `mm` this is working in my end-to-end tests


(https://github.com/JCSDA-internal/ioda-converters/pull/1327)

we will then work in the future on the model interface potentially changing units from the model histories or restarts to something else but that can be future work
