### ISSUE TITLE
YAML for the [3D]RTMA/URMA High-Resolution Radiosonde Data

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1184]
## Description
Write example YAMLs that convert 3[D]RTMA/URMA High-Resolution Radiosondes BUFR to NetCDF using _bufr2ioda.x_ for the following subsets:

NC002101 -- MSG TYPE 002-101 RAWINSONDE - FIXED LAND
NC002102 -- MSG TYPE 002-102 RAWINSONDE - MOBIL LAND
NC002103 -- A51103 | MSG TYPE 002-103 RAWINSONDE - SHIP
NC002104 -- A51104 | MSG TYPE 002-104 DROPWINSONDE
NC002105 -- A51105 | MSG TYPE 002-105 PIBAL

Use these YAMLs to convert into an IODA-formatted netCDF file
Add outputs to the ioda-converter testoutput directory
Add tests to the CMakeLists.txt files
Have the tests pass

## Requirements
All important mnemonics required by the [3D]RTMA/URMA users need to be known.

## Acceptance Criteria (Definition of Done)
It will be finished when all files have been checked and tests have passed.

## Dependencies
The _bufr2ioda.x_

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA is this still being worked on

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston working on a High-Resolution Radiosonde YAML for the global data, that will work for [3D]RTMA/URMA as well. Hence, I am closing this issue.
