### ISSUE TITLE
Validation of [3D]RTMA Mesonet Data Generated Using bufr2ioda

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1191]
## Description

- The purpose of this issue is to validate the [3D]RTMA Mesonet NetCDF output data generated using the YAMLs in #1132 plus bufr2ioda.x. Two NetCDF files are generated using the following BUFR subset files:

| NC255004 | A55004 | MTYP 255-004  Mesonet from MADIS: APRS WeatherNet              |
| NC255101  | A55101  | MTYP 255-101  Coop from MADIS: NEPP &  HCN-Modrnzd- NOA  |

- The input BUFR and output NetCDF files will be plotted using Python and other tools, and statistical analysis will be performed for the comparison. 
- The pressure, temperature, and wind obs will be used for the validation. 

## Requirements

- Plotting script to plot BUFR and NetCDF files.

## Acceptance Criteria (Definition of Done)

- Agreement between the BUFR and NetCDF data.

## Dependencies

- There are no dependiencies.

**Comment by PraveenKumar-NOAA** [comment]
**Validation for the NC255004 subset: 
Pressure plots:** 

![bufr_nc255004_pressure](https://user-images.githubusercontent.com/63739712/225723432-6b2d2110-25a5-4f04-baed-6de51af2b0df.png)

![ioda-pressure_nc255004 (1)](https://user-images.githubusercontent.com/63739712/225723581-392dce57-5df5-4346-b9d5-ad5f680d4aca.png)

**Comment by PraveenKumar-NOAA** [comment]
**Wind plots:** 

![bufr_nc255004_wind (1)](https://user-images.githubusercontent.com/63739712/225733588-2e3fa93f-e920-4c9e-97e2-9b9ea44e869b.png)

![ioda-wind_nc255004](https://user-images.githubusercontent.com/63739712/225733659-790c94f8-d4ba-4fc9-942d-47d0f6ff924b.png)

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu @MatthewMorris-NOAA I created these plots in an effort to validate output NetCDF files. Once you OK with these, I will update ObsSpace.yaml for the missing RTMA variables and submit a PR for these mesonet YAMLs.

**Comment by MatthewMorris-NOAA** [comment]
The plots look good to me!

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu please review these plots.

**Comment by PraveenKumar-NOAA** [comment]
Finished and YAMLs merged to develop.
