### ISSUE TITLE
Can't find lib_python to import ioda package on S4

### ISSUE THREAD

**Issue by weiwilliam** [JCSDA-internal/ioda-converters#1196]
## Description
I'm trying to create a python script that grabs OpenAQ PM2.5 data and puts it in IODA format on S4.
However, the way, `import lib_python.ioda_conv_engines as iconv` and `from lib_python.orddicts import DefaultOrderedDict`, to use ioda packages does not work.
I already added `<my_build_dir>/lib/python3.9/pyioda` and `<my_build_dir>/lib/pyiodaconv` to my PYTHONPATH environment variable.

By removing `lib_python.` in each line, it can find packages properly.
Do I miss anything? Thanks.

`tropomi_no2_co_nc2ioda.py` also has this problem.

I installed ioda-bundle with loading modules below, 
``` 
    module purge
    module use /data/prod/jedi/spack-stack/modulefiles
    module load miniconda/3.9.12
    module load ecflow/5.8.4
    module load mysql/8.0.31
    module use /data/prod/jedi/spack-stack-1.3.0/envs/unified-env/install/modulefiles/Core
    module load stack-intel/2021.5.0
    module load stack-intel-oneapi-mpi/2021.5.0
    module load stack-python/3.9.12
    module unuse /opt/apps/modulefiles/Compiler/intel/non-default/22
    module unuse /opt/apps/modulefiles/Compiler/intel/22
    module load jedi-ewok-env/unified-dev jedi-fv3-env/unified-dev soca-env/unified-dev
    module list
```

**Comment by srherbener** [comment]
@weiwilliam it turns out that you need a third directory added to your PYTHONPATH (to find lib_python):
- `<my_clone_of_iodaconv>/src`

It might be that you would be missing something by removing the lib_python from the import commands

I have a feeling that we may not be approaching this the way the iodaconv developers intended. I think it would be good if we can get advice/guidance from @PatNichols or @BenjaminRuston.

**Comment by weiwilliam** [comment]
@srherbener Yeah, thanks. It works by adding one more folder to PYTHONPATH. 
I thought there was something wrong when I built the bundle, and it led to the "lib_python" wasn't created in the <build-dir>/lib folder.

**Comment by jeromebarre** [comment]
Is your issue solved @weiwilliam ? Can we close this?

**Comment by weiwilliam** [comment]
@jeromebarre Temporarily, yes. But I wonder is it what we should expect in the current develop branch? Do users have to add the src/lib_python to use converters properly?

**Comment by jeromebarre** [comment]
please have a look at https://github.com/JCSDA-internal/ioda-converters/blob/4c7db32fbac519078879e51c56a7ebdd838922fe/test/CMakeLists.txt#L430 and how the tests are run and how the environment variable is added: https://github.com/JCSDA-internal/ioda-converters/blob/4c7db32fbac519078879e51c56a7ebdd838922fe/test/CMakeLists.txt#L1069. @climbfuji should we have the python path amended once the compilation is finished so we would avoid this recurrent issue with users?

**Comment by weiwilliam** [comment]
@jeromebarre Thank you so much! That's the thing I was looking for. It makes tests for converters work, but users can't run a converter without adding the "src" folder into the user's PYTHONPATH.

I consider creating lib_python in the build folder and keeping the source folder as original (which means not running tests with calling library python scripts there).
Does it make sense?

**Comment by jeromebarre** [comment]
> @weiwilliam there are two ways for it to work, you can either now do `pip install` of the ioda-converters
> 
> or add "src" to the PYTHONPATH. there is a little bit of reorganization to be completed here, but the main goal is to make it so the converters can use utilities in common rather than cookie cutter converters (copy and changing a few lines)

didn't know about `pip install` for iodaconv. that's even better. this with venv setup like for skylab should prevent this kind of issue now. @weiwilliam i think you got your answers now. let me know if you still need this open.

**Comment by weiwilliam** [comment]
@BenjaminRuston Thank you! I got it.
@jeromebarre Yeah, we can close it.

**Comment by srherbener** [comment]
I think it would be good to eventually have the cmake configurations install everything necessary in: `<prefix>/lib/python<version>/site-packages` which is a standard location for python. By `<prefix>` I mean your build directory for running ctests, and the install directory (after running `make install`).

This way the ctests and installation both have the packages in a single standard python location, and you can access them with a single path added to PYTHONPATH.

**Comment by PatNichols** [comment]
> I think it would be good to eventually have the cmake configurations install everything necessary in: `<prefix>/lib/python<version>/site-packages` which is a standard location for python. By `<prefix>` I mean your build directory for running ctests, and the install directory (after running `make install`).
> 
> This way the ctests and installation both have the packages in a single standard python location, and you can access them with a single path added to PYTHONPATH.

@srherbener i hope to do a PR for that once the relaunch is done. If we can sync, ioda and ioda converters to do this it would be great.

**Comment by jeromebarre** [comment]
Good to hear. I guess I'll leave this issue open and you can link the PR mentioned above. We'll close when the PR will be merged.

**Comment by jeromebarre** [comment]
I'm closing this now since https://github.com/JCSDA-internal/ioda-converters/pull/1212 has been merged.
