### ISSUE TITLE
Validation of High-Res Radiosonde Cloud Data Generated Using bufr2ioda

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1203]
## Description

- The purpose of this issue is to validate the High-Res Radiosonde cloud data generated using the YAML in  #1184. 

- The output NetCDF file is generated using the following BUFR file: 
| NC002101 | A51101 | MSG TYPE 002-101  RAWINSONDE - FIXED LAND (BUFR)         | 

- The input BUFR and output NetCDF file will be plotted using Python and other tools, and statistical analysis will be performed for the comparison.

- The cloudAmount (CLAM) will be used for the validation.

## Requirements

- Plotting script to plot BUFR and NetCDF files.

## Acceptance Criteria (Definition of Done)

- Agreement between the BUFR and NetCDF data.

## Dependencies

- There are no dependiencies.

**Comment by PraveenKumar-NOAA** [comment]
Plots for the cloudAmount obs are generated using the input BUFR and output NetCDF files: 

**BUFR plot:** 
![bufr_nc002101_cloudAmount](https://user-images.githubusercontent.com/63739712/230382054-e747dca0-7166-4613-bbcd-60275a698770.png)

**IODA plot:** 
![ioda-cloudAmount_nc002101](https://user-images.githubusercontent.com/63739712/230382225-0a7c30c7-ce70-4ae6-9b87-45a76f9f4f4e.png)

The extra number of counts in IODA plot is coming from the missing values.

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu @MatthewMorris-NOAA I generated these plots for the high-res radiosonde cloud data. Once you agree with these plots, I will submit a PR.

**Comment by PraveenKumar-NOAA** [comment]
Plots for the heightOfBaseOfCloud obs generated using the input BUFR and output NetCDF files:

**BUFR plot:** 
![bufr_nc002101_heightOfBaseOfCloud](https://user-images.githubusercontent.com/63739712/230418025-64a3a49d-dc95-4a45-8cfb-d21994757ac9.png)


**IODA plot:** 
![ioda-heightOfBaseOfCloud_nc002101](https://user-images.githubusercontent.com/63739712/230418158-528f4aab-97a8-4a65-a836-d8a1bd85b74e.png)

**Comment by PraveenKumar-NOAA** [comment]
@liujake this information is in our BUFR. In the plots above, I used, RAWINSONDE - FIXED LAND (NC002101) BUFR data files.

**Comment by emilyhcliu** [comment]
@KumarPraven 
The observation counts between the BUFR and the IODA should match.  Let's figure out why they don't match and fix it first.  It could be issue in the plotting not in the bufr converter.

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA is this still being worked on

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston yes, I am workin on a related issue.

**Comment by PraveenKumar-NOAA** [comment]
Closing this issue, this will be dealt separately with the High-Res Radiosonde global data!
