### ISSUE TITLE
[Bug]  GOES converter is not calculating the correct solar zenith angle

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#1204]
## Current behavior (describe the bug)
The solar zenith angle computed within the GOES converter (python code) is not calculating the correct solar zenith angle (also need to check the solar azimuth angle).  The following image shows the solar zenith angle found in a GOES-16 IODA file for 1800 UTC 15 Feb 2022.

![g16_8km_MetaData_solarZenithAngle](https://user-images.githubusercontent.com/63315545/230486599-5b1d17db-4644-45a6-98ca-02ab3af28501.png)

Whereas the following image shows the correct values.

![SZAmap](https://user-images.githubusercontent.com/63315545/230617355-edc564e7-5908-4432-ad35-fcc1d446efca.png)

## To Reproduce

Run GOES converter, plot `MetaData/solarZenithAngle`

**Comment by gthompsnJCSDA** [comment]
@ericlingerfelt   I will locate and fix the bug in the calculations.  I just wanted to keep you informed.

**Comment by ericlingerfelt** [comment]
Thanks for checking this out, @gthompsnJCSDA!

**Comment by gthompsnJCSDA** [comment]
I now have the correct code for `MetaData/SolarZenithAngle` but I'm also checking the `MetaData/SolarAzimuthAngle` to ensure it is correct.
A plot of the fixed variable is here.
![g16_8km_MetaData_solarZenithAngle](https://user-images.githubusercontent.com/63315545/230794241-84e9ec47-db3e-41c1-9573-d176c1140c1c.png)

**Comment by gthompsnJCSDA** [comment]
An image of the fixed `MetaData/SolarAzimuthAngle` is now shown here.
![g16_8km_MetaData_solarAzimuthAngle](https://user-images.githubusercontent.com/63315545/231511372-33d439d9-3238-4558-b68a-9330cbd0dc1a.png)
