### ISSUE TITLE
Gmao IODA_v3 converter is slow

### ISSUE THREAD

**Issue by Dooruk** [JCSDA-internal/ioda-converters#1218]
**gmao_obs2ioda.py**(marine) takes exponentially longer to execute for files with increasing number of observation numbers. Also, there doesn't seem to be a ctest for the GMAO IODA conversion except for a validation test.

It starts happening after the updates from IODA_v2 to IODA_v3. IODA_v2 conversions are instant for the same files.

I conducted tests with multiple file types and two different versions of IODA_v3:

#### gmao-obs-2021071500-jason3.nc
Found a total number of observations: 23817
Elapsed time: 276.86 seconds

#### gmao-obs-2021070100-saral.nc
Found a total number of observations: 10972
Elapsed time: 58.64 seconds

#### gmao-obs-20180415.nc (this is in the test/testinput)
Found a total number of observations: 7701
Elapsed time: 22.15 seconds

**Comment by PatNichols** [comment]
@Dooruk this is a known problem with some converters. The culprit is the np.append function. If I get some bandwidth I can fix it. @jeromebarre Do you wish to fix it?

**Comment by jeromebarre** [comment]
Please avoid for loops as much as possible like for example: https://github.com/JCSDA-internal/ioda-converters/blob/d99ad214e63435dbe40281a81b8871b9968d637e/src/marine/gmao_obs2ioda.py#L174
For whatever you need to do during the conversion phase you need to act on arrays and use masks. So most of those converters that are looping on number of observations need to be refactored... See an example of a fast converter: https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/tempo_nc2ioda.py

**Comment by PatNichols** [comment]
@jeromebarre When you have a numpy append (X) it means you reallocate a whoie new array, copy the contents into the new array and then assign X to the last element. For a couple of converters, I split up to numpy arrays and then merge them together later which saves on copying large amount of data. I did start experimenting with using something like a python list which is a bit more like std::vector in c++ then assign that to a numpy array. I haven't found the bandwidth to do more.

**Comment by BenjaminRuston** [comment]
@Dooruk have you retooled the converter, can this be closed

**Comment by Dooruk** [comment]
@BenjaminRuston sorry, this fell out of my radar as we have been using EMC observations. I will give these two options a try if it doesn't work we can close the issue for now.

@PatNichols do you have an example converter with the approach you described in the repo that you can point me to? If not I will test @jeromebarre's masked array approach.

**Comment by PatNichols** [comment]
> @BenjaminRuston sorry, this fell out of my radar as we have been using EMC observations. I will give these two options a try if it doesn't work we can close the issue for now.
> 
> @PatNichols do you have an example converter with the approach you described in the repo that you can point me to? If not I will test @jeromebarre's masked array approach.

@Dooruk 

https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/conventional/amv_ssec_ascii2ioda.py

**Comment by Dooruk** [comment]
I'm finally fixing this and will create a PR soon. I have a question regarding the `_FillValue`. I noticed there is a method in `iconv` for fill values:

`iconv.get_default_fill_val(np.float32)`

However, most other converter scripts use `999` as the `_FillValue`. I would think this to save space on the output file size but is there a standard we should be adhering to?

**Comment by srherbener** [comment]
> I'm finally fixing this and will create a PR soon. I have a question regarding the `_FillValue`. I noticed there is a method in `iconv` for fill values:
> 
> `iconv.get_default_fill_val(np.float32)`
> 
> However, most other converter scripts use `999` as the `_FillValue`. I would think this to save space on the output file size but is there a standard we should be adhering to?

The _FillValue is being used to mark missing data values (whereas the PreQC variable is being used to mark good/bad data). Note that the IODA reader will convert any values matching the _FillValue to an internal JEDI missing value.

My recommendation would be to:
1. First check if there is a missing value mark being used in the provider data (the input to the converter). If so, copy that missing value into the _FillValue which will preserve the missing value marks (if any) when the data is read into IODA
2. If there is not a missing value mark in the provider data, use the appropriate default from the `iconv.get_default_fill_val(np.float32)` functions.

**Comment by Dooruk** [comment]
Thanks @srherbener, I have one more follow up question. I see that the missing values get filled with `_` character automatically by ioda.writer, so I see the following for the `ncdump` of `ObsValue`:

```bash
group: ObsValue {
  variables:
  	float waterTemperature(Location) ;
  		waterTemperature:_FillValue = 9.96921e+36f ;
  		string waterTemperature:units = "C" ;
  data:

   waterTemperature = _, _, _, _, _, _, 19.61212, 15.25665, 12.65726, 

```

So I should also be replacing ObsError with a _FillValue and set PreQC for these variables to 11 or 12?

**Comment by srherbener** [comment]
> Thanks @srherbener, I have one more follow up question. I see that the missing values get filled with `_` character automatically by ioda.writer, so I see the following for the `ncdump` of `ObsValue`:
> 
> ```shell
> group: ObsValue {
>   variables:
>   	float waterTemperature(Location) ;
>   		waterTemperature:_FillValue = 9.96921e+36f ;
>   		string waterTemperature:units = "C" ;
>   data:
> 
>    waterTemperature = _, _, _, _, _, _, 19.61212, 15.25665, 12.65726, 
> ```
> 
> So I should also be replacing ObsError with a _FillValue and set PreQC for these variables to 11 or 12?

Actually, it is ncdump putting in the '_' character. ncdump is doing this in the places that the variable value matches the _FillValue. Say you have variable "A" which is an integer and has a size of 5. A is set to [ 1, 2, 3, 4, -999 ] and the attribute "_FillValue" on the variable A is set to -999. Then ncdump will print out for A: `A = 1, 2, 3, 4, _  ;`. 

PreQC is for the quality check values (if any) that came from the data provider (ie, the entity that created the input file used by your converter). If there are no quality check values from the data provider, then either PreQC should not be created in the output ioda file or PreQC should be created with every value matching the _FillValue (which is done automatically when you call the function in the ioda library that creates the variable).  The definitions of all the quality check values from the data provider should be left as is for the PreQC variable, and the converter should not invent new values. 

I think we need someone from the OBS team to help with setting up the PreQC variable. There should be some example converters that can be used for guidance and/or some utility functions that can be used. @gthompsnJCSDA, @BenjaminRuston  can you help with this? Thanks!

**Comment by gthompsnJCSDA** [comment]
@Dooruk  I am happy to assist you with other work on the converter.  It seems you received good advice from others about the slowness of using append and using explicit loops in the `Location` dimension.  NCEP-EMC has some very specific values of the `PreQC` variable which I think is their `QualityMarker` variable.  There is a document I found multiple years ago with descriptions of the integer values.  Do you know where to find it?  Feel free to ask me questions if you need help.

**Comment by Dooruk** [comment]
> NCEP-EMC has some very specific values of the `PreQC` variable which I think is their `QualityMarker` variable. There is a document I found multiple years ago with descriptions of the integer values. Do you know where to find it? Feel free to ask me questions if you need help.

Thanks @gthompsnJCSDA. I'm not familiar with the `QualityMarker`, would you mind pointing me to it? I see that it is used in NOAA-EMC repo but I can't find where they get defined.

**Comment by Dooruk** [comment]
I actually have another question. Could I store instrument id information (to distinguish between the same obs sources but different instruments, say ARGO or CTDs) using JEDI nomenclature?

**Comment by gthompsnJCSDA** [comment]
> > NCEP-EMC has some very specific values of the `PreQC` variable which I think is their `QualityMarker` variable. There is a document I found multiple years ago with descriptions of the integer values. Do you know where to find it? Feel free to ask me questions if you need help.
> 
> Thanks @gthompsnJCSDA. I'm not familiar with the `QualityMarker`, would you mind pointing me to it? I see that it is used in NOAA-EMC repo but I can't find where they get defined.

Here is the NCEP code table showing the values of the Quality Markers ([code table 7](https://www.emc.ncep.noaa.gov/mmb/data_processing/prepbufr.doc/table_7.htm)).  When creating a converter for `ioda-converters` you are not required to use this table of values if you do not want.  This is kinda the NCEP standard but when using the UFO `PreQC` filter, you can use whatever values you want for filtering so the choice is really up to you.  I can provide a real world example.  The GOES ABI data has `Data Quality Flags` (DQF) in each L1b raw data file.  Those use an integer from 0 to 5 with specific textual description in the attributes of the netCDF file.  So I use the `PreQC` filter setting of values of either 0 (which is used for "good" data) and 1 (which is listed for "conditionally usable") and throw out data pixels with 2-5.

**Comment by gthompsnJCSDA** [comment]
> I actually have another question. Could I store instrument id information (to distinguish between the same obs sources but different instruments, say ARGO or CTDs) using JEDI nomenclature?

The JEDI data conventions has a list of possible choices for you.  It probably makes the most sense to create a file Global Attribute such as `description`, `platform`, or `source`.  The reference document with variable names is found here [JEDI Data Conventions](https://docs.google.com/spreadsheets/d/1fHb2QIHOwgp4d6plyn9Dj9HZFZsDRxcPaUV6hdTb5BU) and you can review the bottom tab for Global Attributes.

**Comment by srherbener** [comment]
Thanks @gthompsnJCSDA for your help with this!
