### ISSUE TITLE
compare ATMS data from raw files versus remapped

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#1254]
## Description

use files from Skylab v4 pathway from individual granules which have not sampling performed and compare these to files which use the remapping developed by EMC

## Requirements

complete experiments in atm-land configuration using file from 2 alternate pathways

unsampled granules
NCO BUFR files converted using `bufr_ncep_atms_remap.yaml`

**Comment by BenjaminRuston** [comment]
Finished this first round of comparisons it appears the bias coefficients in Skylab are working we for the raw files better than those remapped.  This may be due to the antenna pattern correction.  This can be seen in ATMS ch08

Here is the default ATMS (no remapping) what is in Skylab v4:
![radiance brightnessTemperature omb l8-8 2022021600](https://github.com/JCSDA-internal/ioda-converters/assets/93737224/b381775a-116d-4655-ac87-fd4faeb2bf13)


Here is the ATMS remapped using `bufr_ncep_atms_remap.yaml`:
![radiance brightnessTemperature omb l8-8 2022021600](https://github.com/JCSDA-internal/ioda-converters/assets/93737224/ad3650c1-0e0a-4dee-a1f6-b07e604915ec)

**Comment by BenjaminRuston** [comment]
This should be repeated using:  `bufr_ncep_atms_ta_remap.yaml` to see if this aligns better with the bias coefficients

**Comment by smaticka** [comment]
The results of `o-b` from `skylab-atm-land` were compared for `atms_npp` and `atms_n20`, using `ioda-converters`: `ta_remap`, `remap`, and just the `default bufr`.

The `ta_remap` had the smallest mean `o-b` of the 3, for channel 8 on 16 Feb 2022 at 00H, and should be used as the ioda converter:

<img width="1053" alt="image" src="https://github.com/JCSDA-internal/ioda-converters/assets/40580449/b3c79bf4-f427-4ab7-9ab6-1ee6a9c98ed8">

<img width="1047" alt="image" src="https://github.com/JCSDA-internal/ioda-converters/assets/40580449/14c8a7b7-0750-4ed0-99ec-0525485025ff">

**Comment by ashley314** [comment]
Thanks! @smaticka should [bufr_ncep_atms_ta_remap.yaml ](https://github.com/JCSDA-internal/ioda-converters/blob/develop/test/testinput/bufr_ncep_atms_ta_remap.yaml)be used for all atms when converting?

**Comment by smaticka** [comment]
Correct! @ashley314
