### ISSUE TITLE
Issues in using burf2ioda.x to convert a new bufr data

### ISSUE THREAD

**Issue by jiaruidong2017** [JCSDA-internal/ioda-converters#1257]
I tried to generate the `ioda` format `netcdf` file by using `bufr2ioda.x`, but it failed with the following errors:

**./bufr2ioda.x bufr_ncep_nbd_snow2.yaml**
```
PRE-MAIN-INFO BufrParser: Parsing file ./input_nbd.bufr_d
PRE-MAIN-INFO Executing Queries
PRE-MAIN-WARNING Warning: Query String */SNWSQ1/TOSD didn't apply to subset NC000015
PRE-MAIN-INFO Building Bufr Data
PRE-MAIN-INFO Exporting Data
PRE-MAIN-ERROR Exception: Bad parameter: BoundingFilter variable must be a array of numbers (found list of strings).
terminate called after throwing an instance of 'eckit::BadParameter'
  what():  Bad parameter: BoundingFilter variable must be a array of numbers (found list of strings).
Abort
```

The yaml file was used to convert this new bufr data is attached at the bottom. This yaml file was used to successfully convert the adpsfc snow depth data into the ioda netcdf file. I checkout the converted netcdf file from adpsfc as below: 

```
group: ObsValue {
  variables:
        float totalSnowDepth(Location) ;
                totalSnowDepth:_FillValue = 3.402823e+38f ;
                string totalSnowDepth:long_name = "Total Snow Depth" ;
                string totalSnowDepth:units = "mm" ;
                string totalSnowDepth:coordinates = "longitude latitude" ;
  } // group ObsValue
}
```

However, the output `totalSnowDepth` variable to this new bufr data is in the `int` format as below, which is different from the `float` format in the converted `adpsfc` file above. 

```
group: ObsValue {
  variables:
        int totalSnowDepth(Location) ;
                totalSnowDepth:_FillValue = 2147483647 ;
                string totalSnowDepth:long_name = "Total Snow Depth" ;
                string totalSnowDepth:units = "mm" ;
                string totalSnowDepth:coordinates = "longitude latitude" ;
  } // group ObsValue
}
```
@rmclaren @emilyhcliu Do you have any suggestions? Thanks. 

[bufr_ncep_nbd_snow2.txt](https://github.com/JCSDA-internal/ioda-converters/files/11654345/bufr_ncep_nbd_snow2.txt)

**Comment by emilyhcliu** [comment]
@jiaruidong2017 I just spoke to @BenjaminRuston.  He tested the YAML and it worked for him.  He will talk to you.  
I will run it to check if there is any issues.  I will let you know.

**Comment by rmclaren** [comment]
Thanks @BenjaminRuston  and @emilyhcliu for taking a look.

@jiaruidong2017 The types are automatically inferred from the metadata for the mnemonic. So it looks like the meta data indicates that totalSnowDepth is an integer... You can override the type by specifying the "type" manually as follows:

          totalSnowDepth:
            query: "[*/SNWSQ1/TOSD, */MTRMSC/TOSD, */STGDSNDM/TOSD]"
            type: float
            transforms:
              - scale: 1000.0

This should also fix your exception. I just noticed that the filter function expects a "float" as its input and doesn't recognize integers... So that's a bug... ugg.

As an aside, why are you applying the bounding filter? Missing values will be marked with the missing value (fill value) so netcdf readers will recognize them as such. I guess your trying to limit the size of the output data.

**Comment by rmclaren** [comment]
Sorry, I replied to the automated github email that got sent out...

**Comment by jiaruidong2017** [comment]
Thanks @emilyhcliu Sorry for the misleading. The input data is not from `adpsfc` dump file, while it is the dump file from `b000/xx015` tank, e.g., `gdas.t00z.nbd_snowd.20230101.bufr_d`.

**Comment by rmclaren** [comment]
Try commenting out the filter.

**Comment by jiaruidong2017** [comment]
I got the same results with empty values.

**Comment by jiaruidong2017** [comment]
All other metadata have valid values.

**Comment by rmclaren** [comment]
Created the following issue: https://github.com/JCSDA-internal/ioda-converters/issues/1258. Waiting for my certificate to be renewed on HERA...

**Comment by rmclaren** [comment]
@jiaruidong2017 ok, finaly got back in

So when I run print_queries.x I get the following for possible queries in this file:

```
>> print_queries.x ./input_nbd.bufr_d
Available subset variants: 
NC000015
Total number of subset variants found: 1

NC000015
 Dimensioning Sub-paths: 
  1d  *

 Queries: 
  1d  int     NC000015/WGOSIDS
  1d  int     NC000015/WGOSISID
  1d  int     NC000015/WGOSISNM
  1d  string  NC000015/WGOSLID
  1d  int     NC000015/STID
  1d  int     NC000015/NSID
  1d  string  NC000015/LSTN
  1d  int     NC000015/TOST
  1d  int     NC000015/YEAR
  1d  int     NC000015/MNTH
  1d  int     NC000015/DAYS
  1d  int     NC000015/HOUR
  1d  int     NC000015/MINU
  1d  float   NC000015/CLATH
  1d  float   NC000015/CLONH
  1d  float   NC000015/HSMSL
  1d  float   NC000015/HSALG[1]
  1d  float   NC000015/TMDB
  1d  float   NC000015/HSALG[2]
  1d  int     NC000015/MODM
  1d  int     NC000015/SOGR
  1d  float   NC000015/TOSD
  1d  int     NC000015/SDEN
  1d  int     NC000015/MSWEM
  1d  int     NC000015/SWEMS
  1d  string  NC000015/SEQNUM
  1d  string  NC000015/BUHD
```

You're variable definition should look like this:

```
          totalSnowDepth:
            query: "*/TOSD"
            transforms:
              - scale: 1000.0
```

I confirmed the path by looking at the output of **gettab.x** as well. The variable is inside non-repeating sequences. These do not count as part of the path as they always repeat exactly 1 time.

**Comment by rmclaren** [comment]
The **type:** specification is also not necessary. It was guessing the type as it could not find the corresponding variable in the paths that you specified. Once it can find the variable it will resolve to the correct type of float.

**Comment by rmclaren** [comment]
Non-repeating sequences are ignored for path string purposes to make the query strings shorter.

**Comment by BenjaminRuston** [comment]
@jiaruidong2017 yes as Emily mentioned I was able to run the converter using your yaml file but this was for a `adpsfc` file from the NCAR RDA, so just confirming what you mentioned early on in this issue.

Seems like the ability to also process the `gdas.t00z.nbd_snowd.20230101.bufr_d` type file would be advantageous. last week you mentioned the `snocvr` files (which I haven't tried yet), as well as the `adpsfc` will have to catch up with you to see how these `nbd_snowd` also fit into the picture as complementary snow observations

**Comment by jiaruidong2017** [comment]
@rmclaren Thank you very much for your great efforts. Yes, it works perfect as you suggested.

**Comment by jiaruidong2017** [comment]
@BenjaminRuston With great help from @rmclaren, it works for the new snow depth data. I will close this issue, and let's talk later. Thanks @rmclaren again.
