### ISSUE TITLE
[Bug] Recent updates in ioda has broken ioda-converters ctests

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#1269]
## Current behavior (describe the bug)

The merging of the ioda PRs https://github.com/JCSDA-internal/ioda/pull/1006 and https://github.com/JCSDA-internal/ioda/pull/1014 have inadvertently impacted 34 ioda-converters ctests. My apologies that this occurred. It was due to a lack of communication and coordinated testing. Note that the coordinated testing issue is being addressed by current work in the INFRA team.

Here is a listing of the failing tests:
```
The following tests FAILED:
	591 - test_iodaconv_nsidc_l4cdr_icec (Failed)
	594 - test_iodaconv_gds2_sst_l2p (Failed)
	595 - test_iodaconv_gds2_sst_l3u (Failed)
	597 - test_iodaconv_rads_adt (Failed)
	598 - test_iodaconv_godae_prof (Failed)
	599 - test_iodaconv_godae_ship (Failed)
	600 - test_iodaconv_godae_trak (Failed)
	601 - test_iodaconv_hgodas_adt (Failed)
	602 - test_iodaconv_hgodas_insitu (Failed)
	604 - test_iodaconv_glider (Failed)
	607 - test_iodaconv_cryosat2 (Failed)
	608 - test_iodaconv_emc_ice (Failed)
	614 - test_iodaconv_avhrr_radiance (Failed)
	615 - test_iodaconv_pace_oc_l2 (Failed)
	616 - test_iodaconv_pace_radiance_L1B (Failed)
	621 - test_iodaconv_metar (Failed)
	622 - test_iodaconv_sondetac (Failed)
	623 - test_iodaconv_viirs_jpss1_oc_l2 (Failed)
	624 - test_iodaconv_modis_aqua_oc_l2 (Failed)
	625 - test_iodaconv_viirs_jpss1_oc_l3 (Failed)
	626 - test_iodaconv_godae_bgc_argo (Failed)
	631 - test_iodaconv_gsidiag_conv_uv (Failed)
	632 - test_iodaconv_gsidiag_conv (Failed)
	643 - test_iodaconv_modis_aod (Failed)
	646 - test_iodaconv_airnow (Failed)
	687 - test_iodaconv_generic_gnssro_bufr (Failed)
	691 - test_iodaconv_atms_nc4 (Failed)
	692 - test_iodaconv_atms_BGRemap_nc4 (Failed)
	693 - test_iodaconv_generic_bufr_raob (Failed)
	694 - test_iodaconv_amdar (Failed)
	695 - test_iodaconv_buoy (Failed)
	696 - test_iodaconv_ship (Failed)
	697 - test_iodaconv_synop (Failed)
	712 - test_iodaconv_land_owp_snow_obs_dup_thin (Failed)
```
A lot of the issues are differences due to attributes that before the above PRs did not write out properly. Here's a sample:
```
24085 DIFFER : NUMBER OF GLOBAL ATTRIBUTES : 5 <> 3
24086 DIFFER : NAME OF GLOBAL ATTRIBUTE : ioda_version : GLOBAL ATTRIBUTE DOESN'T EXIST IN "testoutp      ut/nsidc_l4_icec.nc"
24087 DIFFER : NAME OF GLOBAL ATTRIBUTE : odb_version : GLOBAL ATTRIBUTE DOESN'T EXIST IN "testoutpu      t/nsidc_l4_icec.nc"
24088 <end of output>
24089 Test time =   0.74 sec
24090 ----------------------------------------------------------
24091 Test Failed.
24092 "test_iodaconv_nsidc_l4cdr_icec" end time: Jun 14 09:16 MDT
24093 "test_iodaconv_nsidc_l4cdr_icec" time elapsed: 00:00:00
24094 ----------------------------------------------------------
```
Hopefully, this can be resolved with a quick verification and update of the ioda-converters test reference files.

## To Reproduce

1. clone ioda-bundle
2. build with all develop branchs
3. run ctests

## Expected behavior

All ioda and ioda-converters ctests pass

**Comment by srherbener** [comment]
@rmclaren I realize that you might already be working on this. I just wanted the ZenHub issue so that we can track this properly. Thanks!

**Comment by rmclaren** [comment]
@srherbener No problem.

**Comment by BenjaminRuston** [comment]
@CoryMartin-NOAA what is your take on this. I just noticed today the `test_iodaconv_land_owp_snow_obs_dup_thin` failed as am working on snow with Jairui. 

Should we revert the ioda change until all the new `testoutput` are prepared?  This could be ready shortly, I'll hold tight until we talk tomorrow at the tagup

**Comment by CoryMartin-NOAA** [comment]
I'll leave that up to you all to decide, if it's just a matter of updating test reference files, I say just wait and we can update them tomorrow or Friday, but if the tests fail due to other issues, then we can revert.

**Comment by rmclaren** [comment]
I'm having trouble running those other tests because of issues with the way my environment is configured. If anybody wants to go through those other tests asnd update those testoutput files (ones were attributes are missing), please do so...

**Comment by srherbener** [comment]
Done! Hopefully the ctests will all pass now
