### ISSUE TITLE
Generate observation data for land DA ctests in JEDI

### ISSUE THREAD

**Issue by jiaruidong2017** [JCSDA-internal/ioda-converters#1274]
The JEDI team agreed us to have new test date for JEDI land related ctests. After discussion with @CoryMartin-NOAA and @barlage, the new selected date is May 1, 2023. Therefore, we will need two observation data for two ctests in the JEDI fv3-bundle. One is `ghcn_snwd_ioda_20230501.nc`, and the other is `smap_smc_ioda_20230501.nc`. @YoulongXia-NOAA @ClaraDraper-NOAA would you please generate or tell me how to generate the two observation data? Thanks.

**Comment by jiaruidong2017** [comment]
I have successfully generated the GHCN data `ghcn_snwd_ioda_20230501.nc`.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, that is great. If you build ioda-bundle, you enter ioda-bundle/iodaconv/src/land, you will find ioda python converter for SMAP, it can be used to produce V3 ioda format data. It should be very similar to the GHCN data but only input file and format are different.

**Comment by YoulongXia-NOAA** [comment]
It include 9km and 36 km NRT converters. Double check what SMAP soil moisture you want to use.

**Comment by YoulongXia-NOAA** [comment]
For SMAP NRT data, I archived them in HPSS /NCEPDEV/emc-land/5year/Youlong.Xia/smapNRT/2023 for both A and D products. Please consider which one you would like to use as a test data.

**Comment by YoulongXia-NOAA** [comment]
I am not sure what latency time is for 9km product. I archive the product with several-hours latency. Please check with @ClaraDraper-NOAA  and see if you can get 20230501 product if you want to use 9km product as the product may have 6-month latency.

**Comment by YoulongXia-NOAA** [comment]
Two data sources https://nsidc.org/data/smap/data and https://asf.alaska.edu/data-sets/sar-data-sets/smap/smap-data-and-imagery/ can be used to check and download input data. and then use ioda-converter to produce ioda v3 NetCDF 4 file. For ctest, you may need nick or similar command reduce input data size.

**Comment by jiaruidong2017** [comment]
@YoulongXia-NOAA Thanks for your quick information. I have no idea what data source will be used. What I need is just a sample data for the ctest in JEDI.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA @jiaruidong2017 I will try to generate a file for you on Friday (if not, I'm on leave until 5 July, and will do it when I get back).

**Comment by jiaruidong2017** [comment]
Thanks @ClaraDraper-NOAA for your help.

**Comment by jiaruidong2017** [comment]
@YoulongXia-NOAA When I generated the GHCN observation file, I used your processing script as below:

`/scratch1/NCEPDEV/da/Youlong.Xia/ioda-bundle/build/bin/ghcn_snod2ioda.py`

But, I found it was the old script with the variable name `snowDepth`. Do you have the new `ioda-bundle` I can use to generate the GHCN observation data with the variable name `totalSnowDepth`? Thanks.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, please use my yesterday built ioda-bundle (see /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/bin). It should work. If you have any questions, please let me know.

**Comment by jiaruidong2017** [comment]
Thanks @YoulongXia-NOAA Which module do I need to load?

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, See README_Modeule_Use in /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle I use GDASapp module

**Comment by jiaruidong2017** [comment]
After I loaded your gdasapp module, I run the script. But, it failed with the following error messages:

```
Traceback (most recent call last):
  File "/scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/bin/ghcn_snod2ioda.py", line 11, in <module>
    import pandas as pd
ImportError: No module named pandas
```
Any suggestions? Thanks.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, your previous method may not work now. Two suggestions are below: (1) build your own ioda-bundle and then work in your bin directory, (2) give me your input file and I do it within my ioda-bundle build/bin directory. Use python ghcn_snod2ioda.py -i input_ghcn_file.csv -o output_ioda_file.nc -f ghcn_station.txt -d YYYYMMDD -m maskout, ghcn_station.txt is in /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/iodaconv/doc/fix, you soft link it or copy it the bin directory. It should work. Give me your csv file and I can make a test.

**Comment by jiaruidong2017** [comment]
Thanks @YoulongXia-NOAA for your great efforts. My input data is at below:

/scratch2/NCEPDEV/land/data/DA/snow_depth/GHCN/processing/20230501.csv

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, to save your time, I got the smap 9m data and put it in /scratch2/NCEPDEV/land/data/DA/soil_moisture/SMAP9km on hera for 20230501 for all available time. Please select one to use.  This data is consistent with my ioda-converter development but update version.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, @ClaraDraper-NOAA, I would like use ioda-converter ghcn_snod2ioda.py built within ioda-bundle directory to produce ioda data for 202030501 GHCN data Jiaui gave me but it is not successful.  But this is a correct way to produce ioda data as I have developed the ioda-converters within ioda-bundle and they have passed ctests.  The users should use those convertes to produce their data rather than use their own version to produce ioda data, in particular for test.  If you use your own ioda-converters offline rather than ioda-bundle, the converted ioda-data may be not consistent with the data produced within ioda-bundle, at least it is a risk.  I did not have any experience using ioda-converters within ioda-bundle. @CoryMartin-NOAA, do you anyone from your group to use ioda-converter within ioda-bundle to produce ioda data, e.g., Andew tangborn? Yesterday I ran ghcn c test within ioda-bundle, it passed. I checked Testing directory, the log file is below:
632/797 Testing: test_iodaconv_ghcn_snod
632/797 Test: test_iodaconv_ghcn_snod
Command: "/usr/bin/bash" "/scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/bin/iodaconv_comp.sh" "netcdf" "/scratch1/NCEPDEV/da/python/opt/core/miniconda3/4.6.14/envs/gdasapp/bin/python3.7 /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/bin/ghcn_snod2ioda.py
                          -i testinput/ghcn_20200228.csv
                          -o testrun/ghcn_snod_20200228.nc
                          -f /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/iodaconv/doc/fix/ghcn-stations.txt
                          -d 20200228
                          -m maskout" "ghcn_snod_20200228.nc" "0.0"
Directory: /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/iodaconv/test

This means that I can do it in test directory using the command above after I modified input and output name and date? I am not sure how to use it to produce ioda data. @CoryMartin-NOAA, @BenjaminRuston, do you have any experiences or know who has such a experience?  I also bring Ben to this link as he has more experience for ioda-converter development. Thanks,

Youlong

**Comment by CoryMartin-NOAA** [comment]
I'm not sure I understand the issue/your question. What is not working when running individually that runs in the test framework?

**Comment by YoulongXia-NOAA** [comment]
@CoryMartin-NOAA, if I run this command in test directory, it has the error below:

 import lib_python.ioda_conv_engines as iconv
ModuleNotFoundError: No module named 'lib_python'

But run ctest -R iodaconv_ghcn in build directory, it passed.

**Comment by YoulongXia-NOAA** [comment]
@CoryMartin-NOAA, my major question is how to use ioda-converters within ioda-bundle to produce ioda-v3 data.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, after I run V2 offline a years ago, I did not run offline ioda converter for v3. I recalled that you ran v3 a couple weeks ago. Could you please share your environment setup for v3 ioda-converter offline run? I tested the converter Built by me and got the same error as Jiarui got. Thank you.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, you have created v2 file, you can use ioda-upgrade-v2-to-v3.x in /scratch2/NCEPDEV/stmp3/Youlong.Xia/snowIodaBundle/ioda-bundle/build/bin to do such a coversion:
 ioda-upgrade-v2-to-v3.x iodav2file iodav3file. Although we still not figure out how to use v3 converter but it should work. Please test it and see it it works. I will continue to check how to setup environment for v3.

**Comment by jiaruidong2017** [comment]
@YoulongXia-NOAA That v2 file was generated by using old script with the variable name `snowDepth`. The script is `/scratch1/NCEPDEV/da/Youlong.Xia/ioda-bundle/build/bin/ghcn_snod2ioda.py`. I am wondering, would you simply replace `snowDepth` with `totalSnowDepth` in the script so that we can generate the v1 file with the old script?

**Comment by YoulongXia-NOAA** [comment]
@CoryMartin-NOAA, thank you for your suggestion. It works now. @jiaruidong2017 @ClaraDraper-NOAA, see /scratch2/NCEPDEV/stmp3/Youlong.Xia/OfflineConverters_v2land/v3, I have use v3 converter to create both ghcn and smap data with v3 format. For GHCN it has only two values when maskout is used. I also create a file with missing data for ghcn. For SMAP, I created it for --maskmissing only. The input data is also there. @jiaruidong2017, please check if this is what you need. Thank you for your patience.

**Comment by jiaruidong2017** [comment]
Thanks @YoulongXia-NOAA for your efforts. However, the GHCN should have 5452 reports with valid snow depth values. Would you please use `/scratch2/NCEPDEV/land/data/DA/snow_depth/GHCN/processing/ghcnd-stations.txt` and rerun your processing scripts?

**Comment by jiaruidong2017** [comment]
@YoulongXia-NOAA Regarding the smap soil moisture data, there are only 962 reports in `smap_ioda_20230501.nc`, while there are 10,927 reports in the `smap_smc_ioda_20191215.nc` from JEDI fv3-bundle. Consider the situation from GHCN, do you think there is anything missing?

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, for smap data, I used SMAP_L2_SM_P_E_44044_A_20230501T020405_R18290_001.h5, and maskout missing values. you can use h5dump to see a hour period covering.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, after I used your ghcnd-stations.txt and it produced 5452 values. Please check it.

**Comment by YoulongXia-NOAA** [comment]
@jiaruidong2017, if JEDI fv3-bundle smap data was produced by @ClaraDraper-NOAA, as she told you, she will produce it for you.   I have produced both maskout and default smap9km and smapNRT data. If the files include missing values, it has ten thousands to 27 thousands data points.   All v3 files are in /scratch2/NCEPDEV/stmp3/Youlong.Xia/OfflineConverters_v2land/v3. I am done.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 just subset the data with something like `ncks` if it is too big of a dataset

**Comment by ClaraDraper-NOAA** [comment]
I can't tell from the discussion above if you still need the SMAP data, or have sorted it out. If you do need it, I'm in the process of copying Zofia's downloaded SMAP files across to: 

/scratch2/NCEPDEV/land/data/DA/soil_moisture/SMAP/v5

She does not have the date you need, however if you check the README she provides clear instructions for how to download the data. Note: each file has a small component of a swath, and there will be some files with no valid data over land, so make sure you quickly plot up your file to make sure there's valid data in it.

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017, if JEDI fv3-bundle smap data was produced by @ClaraDraper-NOAA, as she told you, she will produce it for you. I have produced both maskout and default smap9km and smapNRT data. If the files include missing values, it has ten thousands to 27 thousands data points. All v3 files are in /scratch2/NCEPDEV/stmp3/Youlong.Xia/OfflineConverters_v2land/v3. I am done.

@YoulongXia-NOAA Thank you very much for your hardworking, and it's great help.

**Comment by jiaruidong2017** [comment]
> @jiaruidong2017 just subset the data with something like `ncks` if it is too big of a dataset

@CoryMartin-NOAA The new SMAP data (with file size of 54KB) is much smaller than the SMAP data currently used in JEDI (with file size of 217KB).

**Comment by jiaruidong2017** [comment]
> I can't tell from the discussion above if you still need the SMAP data, or have sorted it out. If you do need it, I'm in the process of copying Zofia's downloaded SMAP files across to:
> 
> /scratch2/NCEPDEV/land/data/DA/soil_moisture/SMAP/v5
> 
> She does not have the date you need, however if you check the README she provides clear instructions for how to download the data. Note: each file has a small component of a swath, and there will be some files with no valid data over land, so make sure you quickly plot up your file to make sure there's valid data in it.

@ClaraDraper-NOAA I plan to use the SMAP soil moisture data generated by @YoulongXia-NOAA. Do you have any suggestions which one is better,  `smap9km_ioda_20230501.nc` with 962 reports or `smapNRT_ioda_20230501.nc` with 2671 reports?

**Comment by ClaraDraper-NOAA** [comment]
@jiaruidong2017 It's up to you - but I'd just use whichever file is smallest.

**Comment by jiaruidong2017** [comment]
@ClaraDraper-NOAA Okay, thanks.
