### ISSUE TITLE
bufr@12 only provides with single precision library - ioda-converter update needed

### ISSUE THREAD

**Issue by climbfuji** [JCSDA-internal/ioda-converters#1276]
## Description
The bufr library version 12+, requested for PR https://github.com/JCSDA-internal/ioda-converters/pull/1221, only provides a single precision library and headers (known as `_4`). The mixed precision (4-byte integer, 8-byte floats, known as `_d`) and the double precision library (8-byte integer, 8-byte floats, known as `_8`) are no longer supported.

ioda-converters currently uses the `_d` version. According to the `bufr@12` release notes, a workaround exists to support the legacy versions that will require minor changes to ioda-converters: https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases. A better solution would be to update the ioda-converters to use the `_4` version directly.

Note that `bufr@12` will be the default (or only) bufr version in spack-stack-1.5.0, which is anticipated for end of August. An intermediate spack-stack-1.4.1 install will be made available in the next week that provides `bufr@12` for development and testing.

## Requirements

A spack-stack installation with `bufr@12`.

## Acceptance Criteria (Definition of Done)

ioda works with the `bufr_4` library and headers

## Dependencies
n/a

**Comment by PatNichols** [comment]
@climbfuji You might want to notify the noaa developers. Their release notes only mention a change to integers.
https://noaaemc.github.io/NCEPLIBSbufr/md__home_runner_work_NCEPLIBS_bufr_NCEPLIBS_bufr_bufr_docs_ReleaseNotes.html

**Comment by rmclaren** [comment]
Covered by PR #1221

**Comment by climbfuji** [comment]
Oh great, then I'll link the PR to this issue so that it closes it when it is merged - thanks!
