### ISSUE TITLE
Creating ioda-converters for NCEP data

### ISSUE THREAD

**Issue by smaticka** [JCSDA-internal/ioda-converters#1280]
## Description

A pathway is needed to be able to use data available by NCAR NCEP for various instruments (e.g. atms_n20, atms_npp, amsua-A,..). Pathway includes: obtaining data from ncep/cheyenne, creation of ioda-converters (using remapping functionality from Emily Liu), storing in r2d2, and adjustment to yaml for use in jedi. 

## Acceptance Criteria (Definition of Done)
When the NCEP data is functional in the jedi system.

**Comment by BenjaminRuston** [comment]
thanks @smaticka the converter is already in place and if any modification are necessary hopefully they will be small.

The new addition is a skylab issue now, as the yaml will do into the `skylab/obs/ufo` directory.

will close this for now, we may need to modify the conversion yaml but we have a pathway to successfully create a ioda file
