### ISSUE TITLE
Python API read WGOSLID issue and output WSI for stationIdentification

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#1281]
## Description

Use newly produced obs snow product gdas.t06z.snocvr.tm00.bufr_d on 20230501 to work on WSI as station identification. WSI include the four WIGOS components:  WGOSIDS, WGOSISID, WGOSISNM, WGOSLID and WSI will be WGOSIDS-WGOSISID-WGOSISNM -WGOSLID such as 0-20000-0-82403. If any component is missing, LSTN is used instead as a good backup. When python API reads WGOSLID and it shows that RuntimeError: Could not allocate string object!. This issue needs to be solved.

## Requirements

Use python API 

## Acceptance Criteria (Definition of Done)

The v3 ioda data is produced and ctest passes within ioda-bundle.

## Dependencies

No

**Comment by YoulongXia-NOAA** [comment]
@rmclaren, just create a new issue. 
I tested the python API for all four components:   WGOSIDS, WGOSISID, WGOSISNM, WGOSLID and printed them out. The first three have values and missing data but the last one has errors.
WGOSIDS:  [0 -- -- -- -- -- 0 0 0 -- -- -- -- 0 0 0 0 -- -- -- -- 0 0 0 0 -- -- --
WGOSISID:  [756 -- -- -- -- -- 756 756 20000 -- -- -- -- 756 756 20000 756 -- -- --
WGOSISNM: [1 -- -- -- -- -- 1 1 0 -- -- -- -- 1 1 0 1 -- -- -- -- 1 1 1 1 -- -- --
WGOSLID: The error below:

 Traceback (most recent call last):
  File "bufr_ncep_snocvr_api.py", line 98, in <module>
    snow_bufr_to_ioda()
  File "bufr_ncep_snocvr_api.py", line 38, in snow_bufr_to_ioda
    sid = r.get('stationIdentification')
RuntimeError: Could not allocate string object!

I am not sure the reason. The test python code is  bufr_ncep_snocvr_api.py in /scratch1/NCEPDEV/da/Youlong.Xia/test/pythonAPI on Hera. In that directory also has testinput directory with bufr file. If your time is available, please make a quick test and check.

**Comment by YoulongXia-NOAA** [comment]
@rmclaren I cannot read the WGOSLID. Mitch from the EMC obsproc team told me that it is 16-byte character string. I am not sure if the python API can only read 8-byte character string or something else. I can start to look how to combine these three strings into a single string and then output it.

**Comment by rmclaren** [comment]
The python API will haver the same restrictions on these fields as the YAML api would have. I have to look into how UFR even encodes 16 byte elements as usually elements are limited to a max of 8 bytes.

**Comment by emilyhcliu** [comment]
@YoulongXia-NOAA Thanks for spotting the issues with strings.  I will do some testing with WIGOS ID as well.

**Comment by rmclaren** [comment]
Just FYI I just created a pull request for ioda that fixes some of the issues with writing strings and datetime objects:

https://github.com/JCSDA-internal/ioda/pull/1032

**Comment by emilyhcliu** [comment]
Thanks, Ron.

Nick has a problem with SID (string type) from BUFR for ADPSFC.
The SID from ADPUPA is OK.

The station ID (SID) from ADPSFC has a mix of numbers or alphabets in the
SIDs (e.g., "12345" or "ABCDF")
The station ID (SID) from ADPUPA has all numbers in a string (e.g."12345")

I will ask Nick to do the test with your feature branch.

Emily


*Emily Huichun Liu*
Physical Scientist
Modeling and Data Assimilation Branch - DA & QC
NOAA/NWS/NCEP Environmental Modeling Center
National Centers for Weather and Climate Prediction (NCWCP)
5830 University Research Court
College Park, MD 20740
Phone: 301-683-3639
Cell: 410-948-6256

**Comment by ilianagenkova** [comment]
@rmclaren , thanks for the heads up, I'll let you and Emily plan how to proceed, let me know if my input is needed. For what is worth, when one is reading the WIGOS IDs, the 4 components don't need to be "combined" into one. I don't think this helps you, but wanted to clarify it

**Comment by rmclaren** [comment]
Illiana is the WGOSLID just the combination of the other WGOS id's?

**Comment by emilyhcliu** [comment]
@rmclaren The WGOSID (WSI) information from Mitchell's presentation.
https://docs.google.com/presentation/d/1bovpMATF0dp2yVZ-bK8l7-n2lYmipOk4xTwv9xo5DPk/edit#slide=id.p4

**Comment by YoulongXia-NOAA** [comment]
@emilyhcliu, as it is 16 byte string, @rmclaren python API cannot handle it. Even bufr2ioda.x can also handle it so that it produced the weird character. This is what Ron talked about from both obsproc and his side. @ilianagenkova, this is WGOSLID only (not WSI). If we want to move WSI direction or use WGOSLID, we cannot avoid this issue. If obsproc team cannot use 8 bytes for WGOSLID, we have to work together to solve this issue.

**Comment by YoulongXia-NOAA** [comment]
@rmclaren, if your python api works for WGOSLID, please let me know so that I can test it. Thank you

**Comment by ilianagenkova** [comment]
@rmclaren , just noticed you wanted to tag me .
WIGOSLID is the 4th component of the WIGOS ID. The first 3 are numeric, the 4th and long one is character string.

**Comment by rmclaren** [comment]
thanks illiana

**Comment by YoulongXia-NOAA** [comment]
@rmclaren @emilyhcliu, now I used GDAS spack-stack and its bufr version is  bufr/11.7.1.  I am planning to test long string branch [feature/query_long_str](https://github.com/JCSDA-internal/ioda-converters/tree/feature/query_long_str) and checkout it to my local repository. How to load bufr version 12? If I cannot load it, where is build bufr v12 on Hera I can use? If there is no any build already, I have to build it myself, could you please tell me how build it with what modules will be used for build?

**Comment by srherbener** [comment]
bufr@12.0.0 is available in spack-stack-1.4.1 on Hera: https://spack-stack.readthedocs.io/en/1.4.1/PreConfiguredSites.html#noaa-rdhpcs-hera

Note that the path for loading spack-stack-1.4.1 looks correct for Intel, but the path for GNU contains spack-stack.1.4.0. It might be the case that spack-stack-1.4.1 is only available for Intel compilers.

**Comment by YoulongXia-NOAA** [comment]
@srherbener, Aha, I saw it. thank you. @rmclaren just gave me the modules he used (spack-stack-1.4.1) as suggested and I am using them to build my ioda-bundle. Thanks for both of you.

**Comment by YoulongXia-NOAA** [comment]
@srherbener, Ron has told me below:

module load jedi-fv3-env/unified-dev
module load ewok-env/unified-dev
module load soca-env/unified-dev

Thank you, @rmclaren.

**Comment by srherbener** [comment]
Thanks @rmclaren for clarifying the module versions, and sorry about the confusion. We are planning to converge on a consistent naming for the environment modules in the upcoming spack-stack-1.5.0 release (early September).

@YoulongXia-NOAA are you able to build ioda-bundle now?

**Comment by YoulongXia-NOAA** [comment]
@srherbener, Yes, I am trying to build it by using Ron's query_long_str branch and test his python API for WGOSILID of my snocvr data

**Comment by YoulongXia-NOAA** [comment]
@rmclaren, thank you. My paython API works using your feature [feature/query_long_str](https://github.com/JCSDA-internal/ioda-converters/tree/feature/query_long_str) and  NCEPLIB-bufr feature/expose_readlc_c.  I keep 4 WIGOS components data type as the original bufr files. I used the names below: 
       int stationWIGOSIdComponent1(Location) ;
                stationWIGOSIdComponent1:_FillValue = 2147483647 ;
                string stationWIGOSIdComponent1:long_name = "Station WIGOSId Component 1" ;
        int stationWIGOSIdComponent2(Location) ;
                stationWIGOSIdComponent2:_FillValue = 2147483647 ;
                string stationWIGOSIdComponent2:long_name = "Station WIGOSId Component 2" ;
        int stationWIGOSIdComponent3(Location) ;
                stationWIGOSIdComponent3:_FillValue = 2147483647 ;
                string stationWIGOSIdComponent3:long_name = "Station WIGOSId Component 3" ;
        string stationWIGOSIdComponent4(Location) ;
                string stationWIGOSIdComponent4:_FillValue = "" ;
                string stationWIGOSIdComponent4:long_name = "Station WIGOSId Component 4" ;
If  any components are missing, I keep it as missing as original bufr files. I also output stationIdentification using LSTN.  As NCEPLIB-bufr feature/expose_readlc_c and feature/query_long_str are not merged in their own develop branch, I cannot create a PR. But At least, it works. From my example, I did not find that its run is slower as you told before perhaps as my bufr data is small.
