### ISSUE TITLE
[Bug] test_iodaconv_prepbufr_ncep_api_adpsfc2ioda is failing on S4 when using bufr@12.0.0

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#1292]
## Current behavior (describe the bug)

I tested bufr v12.0 on S4 using jedi-bundle, including ioda-converters, Intel/Impi and spack-stack-1.4.1. All of the jedi-bundle tests passed except for one ioda-conveters test: `test_iodaconv_prepbufr_ncep_api_adpsfc2ioda' which dumped out this error message:
```
Command: "/usr/bin/bash" "/data/users/sherbener/jedi/build-intel/bin/iodaconv_comp.sh" "netcdf" "/data/users/sherbener/jedi/venv/bin/python3.9 testinput/prepbufr_adpsfc_api.py" "prepbufr_adpsfc_api.nc" "0.0"
Directory: /data/users/sherbener/jedi/build-intel/iodaconv/test
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" start time: Jul 12 20:41 UTC
Output:
----------------------------------------------------------
 
 ***********BUFR ARCHIVE LIBRARY ABORT**************
 BUFRLIB: NEMTBB - ITAB (      0) NOT FOUND IN TABLE B                                               
 ***********BUFR ARCHIVE LIBRARY ABORT**************

<end of output>
Test time =   0.68 sec
----------------------------------------------------------
Test Failed.
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" end time: Jul 12 20:41 UTC
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" time elapsed: 00:00:00
----------------------------------------------------------
```

Not sure if this is a fault in the bufr library or perhaps a usage issue. Here are release notes for bufr v12, and perhaps this error is related to the instructions for using the bufr_4 component. We are currently using the bufr_d component.

https://noaa-emc.github.io/NCEPLIBS-bufr/md__home_runner_work_NCEPLIBS_bufr_NCEPLIBS_bufr_bufr_docs_ReleaseNotes.html

Check out PR #1290 to see the exact CMake configuration changes I used to test bufr v12.0.

## To Reproduce

> What computer are you running on?

S4

> What compilers/modules are you using?

spack-stack-1.4.1
Intel/Impi

> Steps to reproduce the behavior

1. build jedi-bundle including ioda-converters
    a. ecbuild -DBUILD_IODA_CONVERTERS=ON <path-to-source>
2. ctest

## Expected behavior

All tests pass

**Comment by srherbener** [comment]
I'm seeing this same failure with bufr@11.7.1. Same instructions for reproducing the error except load spack-stack-1.4.0 instead of spack-stack-1.4.1. This may not be an issue with bufr@12.0.0.

**Comment by srherbener** [comment]
I just now tested all develop branches in jedi-bundle on S4, Intel/Impi and all tests passed including the test reported in this issue. So, now it looks like the issue is the switch from bufr_d to bufr_4, noting that the same error occurs regardless of the bufr library version.

**Comment by BenjaminRuston** [comment]
ok,,, so is this resolved @srherbener as long as the correct library is linked

**Comment by srherbener** [comment]
I think this is an issue with the CMake configuration, where if you switch the bufr library after successfully building and testing with a particular bufr library version in place, then the iodaconv code doesn't rebuild/relink and the fault appears.

I've started testing this on S4 by running various combinations of bufr library versions (11.7.1 vs 12.0.0) and either the develop or feature/bufr-12.0-config branches in ioda-converters. I'm using jedi-bundle and all other repos are referencing develop branches. Before each test, I'm clearing out the idoaconv build directory to start with a clean slate. I think if all these tests pass, then we should close this issue, and open a new issue about the CMake configuration not rebuilding/relinking the newly introduced bufr library.

| bufr library version | iodaconv branch | test status |
|--------------------|------------------|-----------|
| 11.7.1 | develop | PASS |
| 11.7.1 | feature/bufr-12.0-config | PASS |
| 12.0.0 | feature/bufr-12.0-config | Running |

**Comment by srherbener** [comment]
Okay, after running around in circles a bit, it looks like the issue is with the bufr@12.0.0 library.

It's quite possible that there is a CMake issue where switching the bufr library doesn't cause the code using that library to update (rebuild, relink, whatever is necessary). This was confusing the debug effort, but hopefully the testing above is clear.

Perhaps we need @rmclaren's update https://github.com/JCSDA-internal/ioda-converters/pull/1221 to address this issue?

**Comment by rmclaren** [comment]
So I'm trying to build everything with that spack stack on Hera but all my unit tests fail.. ugg. I don't have any issues getting this stuff to run locally using GNU.

**Comment by srherbener** [comment]
Unfortunately, I don't have access to Hera. @CoryMartin-NOAA do you have any tips for running on Hera? Thanks!

Here are instructions for spack-stack-1.4.0: https://spack-stack.readthedocs.io/en/1.4.0/PreConfiguredSites.html#noaa-rdhpcs-hera

and for spack-stack-1.4.1: https://spack-stack.readthedocs.io/en/1.4.1/PreConfiguredSites.html#noaa-rdhpcs-hera

**Comment by srherbener** [comment]
One thing: If you are running ioda-bundle, the above instructions should work.

However, if you are running jedi-bundle you need to make sure your jedi-bundle is up-to-date and you need to run `module unload crtm` before running ecbuild and let CRTM be built as part of the jedi-bundle.

**Comment by rmclaren** [comment]
For some reason things get a lot more sensitive when it comes to type safety when I compile with spack stack on hera. For example it really doesn't like the implementation of DataObject::_setData(.. enable_if<__number__>). I made code changes to avoid these problems and most unit tests now run... 

I have problems with the python based tests, however. They can't find numpy even though I've loaded that module and imports ok when I do things manually on the command line...

**Comment by CoryMartin-NOAA** [comment]
@rmclaren that usually mean the python version ecbuild finds != the python you use at runtime

**Comment by rmclaren** [comment]
I figured it was something like that... Keep ending up in configuration hell somehow...

**Comment by srherbener** [comment]
@rmclaren we have been adding `-D Python3_EXECUTABLE=$(which python3)` option to ecbuild to help make sure that the python you build with is the same as the python you run with.

**Comment by rmclaren** [comment]
@srherbener Thanks that worked... Wonder how you managed to run it without running into "Floating point exception"s.

**Comment by rmclaren** [comment]
There was a strange problem with NCEPLIB-bufr nemdefs function not returning the same result sometimes so I added a work around. Should fix the test that was failing...

**Comment by rmclaren** [comment]
I also added some changes that make the code more robust on different compilers.

**Comment by srherbener** [comment]
Thanks for the updates @rmclaren! I'm seeing the `test_iodaconv_prepbufr_ncep_api_adpsfc2ioda` pass on S4 now when using bufr@12.0.0. In fact all jedi-bundle tests are passing.
