### ISSUE TITLE
Write or update a converter for surface AQ observations

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/ioda-converters#1297]
## Description

Write or update a ioda-converter to ingest either airnow or open AQ observations.
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/airnow2ioda_nc.py

## Requirements

For pm2.5 if the model output doesn't produce pm2.5 we would need to add a VADER transform.
@jeromebarre can help with this

## Acceptance Criteria (Definition of Done)

The converter can take O3, PM2.5, NO2, SO2 (maybe CO) and data is tested in UFO

## Dependencies

TBD

**Comment by weiwilliam** [comment]
Work on ozone first. Data were reported in different units.
I consulted with OpenAQ people, and the value in mg m-3 was converted under 'standard' ambient conditions.
The 'standard' varies by agency or instrument setting. 
I will focus on ppm data for now.
