### ISSUE TITLE
Add more information in the python/yaml for Radiosonde data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#1298]
## Description
For radiosonde data (e.g. NC002101, NC002102, ...etc), we need to add the following:
- [ ] Drift latitude/longitude  (based on the CLATH/LATDH, CLONH/LONDH)
- [ ] Launch DATE/TIME of LAUNCH in dateimte format (Epoch time)
- [ ] Receipt Time in dateimte format (Epoch time)
- [ ] WIGOSID (after Ron has the solution to handle WIGOSID in BUFR converter)

## Requirements
- [ ] Python script for the converter

## Acceptance Criteria (Definition of Done)
- [ ] Compare with ADPUPA PrepBUFR output

## Dependencies

**Comment by PraveenKumar-NOAA** [comment]
Should I use 'General decoder receipt time'?

**Comment by PraveenKumar-NOAA** [comment]
https://meteor.geol.iastate.edu/classes/mt311/extras/Codul-TEMP.pdf

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu extracted the fortran subroutine from the prepBUFR codes and documented how drift LAT/LON are calculated into these codes using height and wind observations.

https://drive.google.com/drive/folders/184SOItgC5wFCbCRKWmIUqKI2UG-EM9oR

**Comment by PraveenKumar-NOAA** [comment]
WMO Manual on Codes - https://library.wmo.int/doc_num.php?explnum_id=10235 (see page 28 for RCTS code details)

**Comment by PraveenKumar-NOAA** [comment]
Another piece of important information: https://doc-14-3s-apps-viewer.googleusercontent.com/viewer/secure/pdf/tclqmpdo6v6v72m6d9hn1lg2fosssu0s/9ettvif4nouccss9686upom8vj61a1m4/1692221325000/gmail/01885681915741257904/ACFrOgC8epEQFrrXA6Vy1UsBEgjTBT9les4vghbIYh1CF9bheQDoU1tnDSXQgEuyLZboaW6j6tmEcMWUSYAxWaA_Vf7m_mzedYJ0wVBmdz9ouuGZ1vNHv94DCAHdIy4=?print=true&nonce=s91985907shig&user=01885681915741257904&hash=suhqpi5fa317l4cuq6qivhbpqa0fu9h5

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA we may reassign this to a new epic as @emilyhcliu is recommending closing the longstanding Epics and replace them with more current and GDASapp focused ones

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston @emilyhcliu thanks, this is taken care in an another issue. I can close this issue.
