### ISSUE TITLE
Validation of [3D]-RTMA ADPSFC Data Generated Using bufr2ioda

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1318]
## Description

- The purpose of this issue is to validate the [3D]-RTMA ADPSFC data generated using the YAML in #1315.

- The output NetCDF file is generated using the following adpsfc BUFR file: 
_rtma_ru.t0000z.adpsfc.tm00.bufr_d for 2023061000 and subset
NC000101 -- MTYP 000-101 SYNOPTIC - FIXED LAND (BUFR)_

- The input BUFR and output NetCDF file will be plotted using Python and other tools, and statistical analysis will be performed for the comparison.

- The following three observations pressure, temperature, and wind will be used for the validation.

## Requirements

- Plotting script to plot BUFR and NetCDF files.

## Acceptance Criteria (Definition of Done)

- Agreement between the BUFR and NetCDF data.

## Dependencies

- There are no dependencies.

**Comment by PraveenKumar-NOAA** [comment]
Plots are generated using the input BUFR and output NetCDF files.

**Pressure plots:** _BUFR and IODA_

![bufr_pressure_RTMA_ADPSFC](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/442776b2-f291-4150-87e9-7c0b9ec7ac66)

![ioda_pressure_RTMA_ADPSFC](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/36b47239-64ee-4488-a8b0-1423b8ba8310)


**Temperature plots:** _BUFR and IODA_

![bufr_temp_RTMA_ADPSFC](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/afa10406-316a-4b68-93e8-33b179cc00aa)


![ioda_temp_RTMA_ADPSFC](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/066d326f-341b-4247-a568-9178da2b1f9a)


**Wind plots:** _BUFR and IODA_

![bufr_wind_RTMA_ADPSFC](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/299110f0-7a58-4137-9070-c052f8acfc62)

![ioda_wind_RTMA_ADPSFC](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/ff7805fa-845c-476c-8f94-c3228c44e1cd)

**Comment by MatthewMorris-NOAA** [comment]
Why are there no/few obs over CONUS? Also, why are there more obs in the IODA figures for each variable?

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA there are no/few obs over CONUS as these plots contain data only for one ADPSFC subset, NC000101. The extra counts in IODA plots are the missing values, 160 for pressure, 6 for temp, and 57 for wind.

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA Okay, thanks for the explanation. In that case, this looks good to me!

**Comment by PraveenKumar-NOAA** [comment]
Completed and closed.
