### ISSUE TITLE
Missing "Missing Value"

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#1345]
## Current behavior (describe the bug)

Not filling in missing values in some circumstances.

## To Reproduce

1) Run the test **test_iodaconv_bufr_ncep_prepbufr_adpupa_api**.
2) ncdump the result: **_ncdump ./test/testrun/prepbufr_adpupa_api.nc_**
3) Inspect the output for message 13 (specificHumidty). It should have a Missing value mixed in with the non-missing values, but it does not.

## Expected behavior

Missing v alue should be present as there is a 0 count element mixed in with the non-missing values.

**Comment by PraveenKumar-NOAA** [comment]
@rmclaren there are seventeen QOB fields with 0 counts (missing) in the prepbufr file and I am getting all of them into the output ioda file.

**Comment by rmclaren** [comment]
This issue should be fixed in pull request #1344
