### ISSUE TITLE
Modify satbias converter to follow new file convention

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA-internal/ioda-converters#1349]
## Description
In order to generalize the satbias and satbias_cov I/O in UFO, we need to refactor the format of the satbias netCDF/IODA files. This issue will track the updates to the existing GSI to satbias converter, as well as a python script that will 'translate' between the old and new format for people to not lose work in the process when things are being updated.

## Requirements

Coordinated with UFO for the aircraft VarBC code sprint as well as work in #804 

## Acceptance Criteria (Definition of Done)
This should be a coordinated merge with UFO

## Dependencies
See above, #804 as well as https://github.com/JCSDA-internal/ufo/issues/2993

**Comment by BenjaminRuston** [comment]
this can be closed correct @huishao-r

**Comment by BenjaminRuston** [comment]
@CoryMartin-NOAA think this is done correct, should we close and open a new one if needed

**Comment by CoryMartin-NOAA** [comment]
Lets do it
