### ISSUE TITLE
add a converter for modis water leaving radiance data

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/ioda-converters#1353]
## Description
I'm going to add aqua-MODIS L2 data from https://oceandata.sci.gsfc.nasa.gov/directdataaccess/Level-2/Aqua-MODIS/ to the dataset
this data just has remote sensing reflectance we can drive water leaving radiances from it, so we do not have the TOA radiance issue like pace here.

**Comment by travissluka** [comment]
note that once these files are ready, an r2d2 ingest issue will need to be opened to get the files put into r2d2
