### ISSUE TITLE
Validation of [3D]-RTMA AIRCFT Data Generated Using the bufr2ioda

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1373]
## Description

- The purpose of this issue is to validate the [3D]-RTMA AIRCFT data generated using the YAML in #1359 

- The output NetCDF file is generated using the following BUFR file/subset:
   rtma_ru.t0000z.aircft.tm00.bufr_d
  | NC004006 | A55200 | MTYP 004-006  Automated European AMDAR (BUFR)            |

- The input BUFR and output NetCDF file will be plotted using Python and other tools, and statistical analysis will be performed for the comparison

- The temperature and wind obs will be used for the validation

## Requirements

- _bufr2ioda.x_
- Plotting script(s) to plot BUFR and NetCDF files

## Acceptance Criteria (Definition of Done)

- Agreement between the BUFR and NetCDF data

## Dependencies

- There are no dependiencies

**Comment by PraveenKumar-NOAA** [comment]
Plots are generated using the input BUFR and output NetCDF files.
**Temperature plots: BUFR and IODA:**

![bufr_temperature_nc004006](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/e757a97a-81ae-4763-93b5-f7fa1f0637f7)

![ioda-temperature_nc004006](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/979364fb-123f-46af-b319-47992c3bc5a1)

**Comment by PraveenKumar-NOAA** [comment]
Plots are generated using the input BUFR and output NetCDF files.
**Wind plots: BUFR and IODA:**

![bufr_wind_nc004006](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/1ce54b23-85b0-455f-957c-71f69b168708)

![ioda-wind_nc004006](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/3fdda866-567b-4aed-8e51-32396eadcd91)

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA @nicholasesposito please check these validation plots for the [3D]-RTMA AIRCFT data.

**Comment by MatthewMorris-NOAA** [comment]
The plots look good!

**Comment by nicholasesposito** [comment]
Looks good to me!

**Comment by PraveenKumar-NOAA** [comment]
A few more validation plots were created using the following AIRCFT subset: 
- NC004103 --- MTYP 004-103 All other automated AMDAR (BUFR)

**Temperature plots: BUFR and IODA:**

![bufr_temperature_nc004103](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/f1873b74-72ed-410c-9e6c-55448ea427c8)

![ioda-temperature_nc004103](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/9df7218f-4a95-4d66-b6cb-c5758f6b367d)

**Wind plots: BUFR and IODA:**

![bufr_wind_nc004103](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/ca7d2201-8aea-407a-bf52-b056d2b4ae52)

![ioda-wind_nc004103](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/4dd15d5a-98df-44cb-9ee6-a5a836e78c90)

**Comment by nicholasesposito** [comment]
Looks good

**Comment by MatthewMorris-NOAA** [comment]
The plots look good. Do you know why there are a few more obs in the IODA figures?

**Comment by PraveenKumar-NOAA** [comment]
> The plots look good. Do you know why there are a few more obs in the IODA figures?

@MatthewMorris-NOAA thanks, these number of obs are probably less than 0.05% in IODA figures and I think this is due to some of the variables type change, like an integer to float conversion.

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA  A few more validation plots that were created using the ioda-converters [3D]-RTMA AIRCAR YAML and for the following subset:

NC004004 --- MTYP 004-004 Automated MDCRS (ARINC to NCEP) (BUFR)

**Temperature plots: BUFR and IODA:**

![bufr_temperature_nc004004](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/5b6cdbb3-0fce-4562-9d3f-d89a5e0febf6)

![ioda-temperature_nc004004](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/e48ef1e7-17e8-47c9-bfed-6cdc456a54ba)


**Wind plots: BUFR and IODA:**

![bufr_wind_nc004004](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/386d529d-6b4f-4174-b90b-31c081f297c1)

![ioda-wind_nc004004](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/e16cd17a-8d47-4e89-8e89-0ea898b13601)

**Comment by MatthewMorris-NOAA** [comment]
Overall, the figures look good.  My only question is why there are fewer obs in the BUFR wind speed figure relative to the other figures?

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA thanks, I will check it out.

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA the length of wind data is 77074 in bufr data, which is similar to what listed in ioda plot above. There are a total of 137 missing values in wind data and are not counted into the bufr plot.  

wind= [4.6]
wind= [9.3]
wind= [--]
wind= [1.]
wind= [3.1]

The statistics are same in both plots, hence there are no issues with the aircar yaml and validation plots.

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA Thanks for the info! Looks good!

**Comment by PraveenKumar-NOAA** [comment]
Completed and closed.
