### ISSUE TITLE
Set minimum version for NCEPLIB-bufr

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#1380]
## Current behavior (describe the bug)

Will look for any version of NCEPLIB-bufr and then fail if its not found.

## To Reproduce

Download and compile ioda-converters on machine with NCEPLIB-bufr older than 12.0.0

## Expected behavior

Ignore bufr (which is optional) when the installed version is too old.

**Comment by PatNichols** [comment]
@rmclaren Can I close this issue? It looks like the above PR fixed it. Thanks!

**Comment by rmclaren** [comment]
Sure

**Comment by PatNichols** [comment]
Fixed with above PR
