### ISSUE TITLE
create a ioda-converter ctest for ATMS data

### ISSUE THREAD

**Issue by smaticka** [JCSDA-internal/ioda-converters#1388]
## Description

The new `ioda-converter` `bufr2nc_fortran.x` is used to convert `ncep` data, so a new corresponding `ctest` is need to confirm the instruments are properly coverted. 

the old converter is `bufr2ioda.x` which used the `ctest` `test_iodaconv_bufr_ncep_atms`.

**Comment by BenjaminRuston** [comment]
think we can close this @smaticka
