### ISSUE TITLE
Get an array of string values that contains the subset ID for each element using python api converter

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#1428]
## Description
Some of the converters require knowledge about subset IDs to do the conversions. If possible, please devise a way to get an array of string values that contains the subset ID for each element

## Requirements
This I believe is a new feature.

## Acceptance Criteria (Definition of Done)
- [ ] Write the feature (@rmclaren will do this)
- [ ] Test the feature with aircft/aircar data (@nicholasesposito will do this)

## Dependencies
- None

**Comment by rmclaren** [comment]
Please move this issue to https://github.com/NOAA-EMC/bufr-query

**Comment by nicholasesposito** [comment]
Closing to move to [bufr-query Issue #36](https://github.com/NOAA-EMC/bufr-query/issues/36)
