### ISSUE TITLE
Description of dynamic error use for GNSSRO

### ISSUE THREAD

**Issue by haydenlj** [JCSDA-internal/ioda-converters#1431]
## Description
We have demonstrated an application of dynamic error in JEDI Skylab using GNSS-RO data.  For this example, the adaptive observation errors are computed in the converter using the local spectral width (LSW) property and the standard deviation of the observation itself for the upper levels.

The following steps are applied to each RO profile:

1. Apply basic QC (remove negative bending angle obs, missing bending angle obs, obs with bad latitude, obs with large geoid undulation, and obs with bad Earth radius)
2. Calculate relative LSW as bending angle error / bending angle * 100
3. Set LSW cap of 40%
4. Calculate exponential fit of bending angle between 40 and 60 km
5. Calculate STD4060 as standard deviation of difference between bending angle and exponential fit
6. Set STD4060 cap of 40%
7. Calculate relative error by plugging height in meters (relative to the cutoff point), LSW in %, and STD4060 in % into the provided polynomials. The LSW polynomial is applied from 0-10 km, the STD4060 polynomial is applied from 30-60 km, and the minimum relative error (1.25%) is applied from 10-30 km
8. Error is calculated from the relative error as relative error / 100 * bending angle

The error is included in the IODA file for each RO profile and then ingested by JEDI, our testing used the Skylab demonstrator. 

## Requirements

- [x] #1432
        - [ ] Test month (Aug 2021; COSMIC-2)
        - [ ] September 2022
                - [ ] COSMIC2
                - [ ] Geooptics
                - [ ] Kompsat5
                - [ ] PAZ
                - [ ] Spire
- [x] Modify converter to produce: 
        - [ ] LSW (%)
        - [ ] STD4060 (%)
        - [ ] Hybrid error
        https://github.com/JCSDA-internal/ioda-converters/blob/feature/hybrid_err/src/gnssro/gnssro_bufr2ioda.py

- [x] Plot hybrid error statistics to verify calculations
![Screen Shot 2023-12-13 at 10 59 35 AM](https://github.com/JCSDA-internal/ioda-converters/assets/99764299/0b7f5b90-c95b-48b
![Screen Shot 2023-11-13 at 11 51 06 AM](https://github.com/JCSDA-internal/ioda-converters/assets/99764299/845f6eac-ef17-405d-8613-a265bef20227)
3-bcac-70b1276324f1)

- [x] Test that reading error from a file works in Skylab
- [x] Test QC additions to converter
![Screen Shot 2023-11-17 at 11 12 59 AM](https://github.com/JCSDA-internal/ioda-converters/assets/99764299/f61b2b0c-2637-48fe-8dae-083b8a7662ac)

- [ ] Run experiments:
       - [ ] Control
       - [ ] Hybrid Error
- [ ] Experiment comparison

## Acceptance Criteria (Definition of Done)
The capability to read LSW from GNSSRO bufr files has been added to the converter
https://github.com/JCSDA-internal/ioda-converters/pull/1394 
The dynamic error use in Skylab has been demonstrated and fully tested

## Dependencies
none

**Comment by fcvdb** [comment]
The capability to read LSW from GNSSRO bufr files has been added to the converter in PR
https://github.com/JCSDA-internal/ioda-converters/pull/1394
Closing this issue.
