### ISSUE TITLE
Add Muon Space data functionality in JEDI

### ISSUE THREAD

**Issue by smaticka** [JCSDA-internal/ioda-converters#1439]
## Description
Ocean surface data of `wind speed retrieval` (no direction) is available from `Muon Space` as `netCDF4` files.
A converter is needed to bring the data into `IODA` format to be used in `JEDI`.

## Acceptance Criteria (Definition of Done)
Successfully processes Muon Space data into IODA format that creates data that is reliable and usable in JEDI. 

## Dependencies
A Skylab `/obs/ufo/` yaml is also needed to process the IODA-converted data. 
Since wind is only available as speed (no direction), then a filter will be needed to (likely) pull the direction from the background data and apply it to the wind speed from Muon.

**Comment by BenjaminRuston** [comment]
@smaticka think we can call this completed for now correct, and open new issues as needed?

if you concur please close ;0)
