### ISSUE TITLE
Validation of [3D]-RTMA ADPUPA Data Generated Using the bufr2ioda

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#1451]
## Description

- The purpose of this issue is to validate the [3D]-RTMA ADPUPA data generated using the YAML in https://github.com/JCSDA-internal/ioda-converters/issues/1450

- The output NetCDF files are generated using the following BUFR file/subset:
rtma.t00z.prepbufr.tm00/ ADPUPA
rtma.t00z.adpupa.tm00.bufr_d and NC002001

- The input BUFR and output NetCDF file will be plotted using Python and other tools, and statistical analysis will be performed for the comparison

- The temperature, wind, and pressure obs will be used for the validation

## Requirements

- bufr2ioda.x
- Plotting script(s) to plot BUFR and NetCDF files

## Acceptance Criteria (Definition of Done)

- Agreement between the BUFR and NetCDF data

## Dependencies

- There are no dependencies

**Comment by PraveenKumar-NOAA** [comment]
**ADPUPA BUFR Validation:** plots were created using the input BUFR and output IODA/NetCDF files for the following observations: temperature, pressure, and wind. 

Temperature plots: 
**BUFR** 
![bufr_rtma_adpupa_temp](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/aef93723-2975-4706-a681-3a5325af74a9)

**IODA**
![ioda-rtma_adpupa_temp](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/aca2cb4a-a383-41d3-ad00-a4ff4848cc8e)

Thera were 23297 missing values in the IODA file, and statistics are similar. 

Pressure plots: 
**BUFR** 
![bufr_rtma_adpupa_pressure](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/483e02b5-4f51-4d63-aa8d-80c0f18be5b7)

**IODA**
![ioda-rtma_adpupa_pressure](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/d0437db6-38a8-42a9-b882-b22c0c2f30b4)

Number of total Location 30843
Thera were 19644 missing values in the IODA file, and statistics are similar.  


Wind plots: 
**BUFR** 
![bufr_rtma_adpupa_wind](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/e8d48ffc-55b7-4cfa-abed-2f3be9832f8e)

**IODA**
![ioda-rtma_adpupa_wind](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/a8bbcd7b-31e3-4d77-bfb2-27f9df8583c4)

Number of total Location 30843
Thera were  22572 missing values in the IODA file, and statistics are similar.

**Comment by PraveenKumar-NOAA** [comment]
ADPUPA prepBUFR Validation: plots were created using the input BUFR and output IODA/NetCDF files for the following observations: temperature.

Temperature plots:
**BUFR**
![bufr_rtma_prepbufr_adpupa_temp (3)](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/93de097f-9086-4b8e-9f0a-a28ea3dc1276)



**IODA**
![ioda_rtma_prepbufr_adpupa_temp](https://github.com/JCSDA-internal/ioda-converters/assets/63739712/836f94ad-c8fc-4afa-83f2-e01929fa7b44)

**Comment by PraveenKumar-NOAA** [comment]
@MatthewMorris-NOAA please look at these validation plots for the [3D]-RTMA ADPUPA BUFR and prepBUFR data.

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA The figures look good, but I'm curious about the large # of missing values in the IODA files compared to the BUFR files. What is the cause of this?

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA The figures look good, but I'm curious about the large # of missing values in the IODA files compared to the BUFR files. What is the cause of this?

@MatthewMorris-NOAA I can understand your concern. A group_by variable field is required to use in these YMALs, which creates these extra missing values.
