### ISSUE TITLE
[Bug] ioda validate does not report failures

### ISSUE THREAD

**Issue by PatNichols** [JCSDA-internal/ioda-converters#1468]
## Current behavior (describe the bug)

Due to time constraints, the Data Conventions did not corect several testoutput files for the new conventions.
This required the ioda_validate tests to ignore warning and errors. Thus the ioda_validate tests were of no use. 

If one removes --ignore-errors from the ctest cmakefile, the following 97 tests fail. 

807:iodaconv_validate_testoutput_Rcov_iasi_metop-b_sea.nc4
809:iodaconv_validate_testoutput_abi_g16_obs_2018041500.nc4
812:iodaconv_validate_testoutput_aircraft_prepbufr_acftprofiles.nc
814:iodaconv_validate_testoutput_airnow_2020081306.nc
815:iodaconv_validate_testoutput_amdar_single.nc
816:iodaconv_validate_testoutput_amdar_wmo_multi2.nc
818:iodaconv_validate_testoutput_amsua_aqua_obs_2018041500.nc4
819:iodaconv_validate_testoutput_amsua_metop-b_obs_2020110112.nc4
820:iodaconv_validate_testoutput_amsua_n18_obs_2020110112.nc4
822:iodaconv_validate_testoutput_ascat_ssm.nc
823:iodaconv_validate_testoutput_avhrr_radiance.nc
826:iodaconv_validate_testoutput_bufr_ncep_long_strs.nc
827:iodaconv_validate_testoutput_bufr_query_filtering.nc
828:iodaconv_validate_testoutput_bufr_query_python_to_ioda_test.nc
829:iodaconv_validate_testoutput_bufr_read_2_dim_blocks.nc
832:iodaconv_validate_testoutput_bufr_simple_groupby.nc
835:iodaconv_validate_testoutput_buoy_single.nc
836:iodaconv_validate_testoutput_buoy_wmo_multi.nc
845:iodaconv_validate_testoutput_gdas.t00z.atms_n20.tm00.nc
851:iodaconv_validate_testoutput_gdas.t06z.adpsfc_snow.tm00.nc
852:iodaconv_validate_testoutput_gdas.t12z.1bmhs.metop-b.tm00.nc
853:iodaconv_validate_testoutput_gdas.t12z.acft_profiles.prepbufr.nc
854:iodaconv_validate_testoutput_gdas.t12z.adpsfc.prepbufr.nc
855:iodaconv_validate_testoutput_gdas.t12z.adpsfc.tm00.nc
856:iodaconv_validate_testoutput_gdas.t12z.adpupa.prepbufr.nc
857:iodaconv_validate_testoutput_gdas.t12z.adpupa_bufr.tm00.nc
858:iodaconv_validate_testoutput_gdas.t12z.adpupa_bufr_nc002001.tm00.nc
859:iodaconv_validate_testoutput_gdas.t12z.adpupa_bufr_nc002003.tm00.nc
860:iodaconv_validate_testoutput_gdas.t12z.adpupa_bufr_nc002005.tm00.nc
862:iodaconv_validate_testoutput_gdas.t12z.aircar.tm00.nc
865:iodaconv_validate_testoutput_gdas.t12z.amsua_metop-c_ta.tm00.nc
866:iodaconv_validate_testoutput_gdas.t12z.amsua_n15.tm00.nc
868:iodaconv_validate_testoutput_gdas.t12z.esamua_n18.tm00.nc
869:iodaconv_validate_testoutput_gdas.t12z.esmhs.noaa-19.tm00.nc
872:iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.seven.split.nc
873:iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.filtering.nc
874:iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.nc
875:iodaconv_validate_testoutput_gdas.t18z.satwnd_avhrr.tm00.nc
879:iodaconv_validate_testoutput_giirs_fy4a_obs_2017030208.nc4
880:iodaconv_validate_testoutput_giirs_ssec_ioda.nc4
881:iodaconv_validate_testoutput_gmao_oceanObs.nc
883:iodaconv_validate_testoutput_gnssaro_obs_2021012000.nc
884:iodaconv_validate_testoutput_gnssro_2020-306-2358C2E6.nc
885:iodaconv_validate_testoutput_gnssro_cosmic2_2021080212.nc4
886:iodaconv_validate_testoutput_gnssro_kompsat5_2018041500.nc4
887:iodaconv_validate_testoutput_gnssro_obs_2018041500.nc4
889:iodaconv_validate_testoutput_gnssro_obs_awsopendata_2021080200.nc4
891:iodaconv_validate_testoutput_godae_prof.nc
893:iodaconv_validate_testoutput_godae_trak.nc
895:iodaconv_validate_testoutput_hgodas_insitu.nc
897:iodaconv_validate_testoutput_iasi_metop-b_obs_2020110112.nc4
898:iodaconv_validate_testoutput_iasi_metop-b_obs_2022021912.nc4
899:iodaconv_validate_testoutput_icethk_coperl4.nc
901:iodaconv_validate_testoutput_ioda.NC001007.2020031012.nc
902:iodaconv_validate_testoutput_ioda_dt_global_twosat_phy_l4_20150101_vDT2018.nc
905:iodaconv_validate_testoutput_mhs_metop-b_obs_2020101215.nc4
906:iodaconv_validate_testoutput_mhs_metop-b_obs_2020110112.nc4
907:iodaconv_validate_testoutput_mhs_n19_obs_2020110112.nc4
912:iodaconv_validate_testoutput_mopitt_co.nc
916:iodaconv_validate_testoutput_odb_sonde_16019.nc4
917:iodaconv_validate_testoutput_omi_o3_l2.nc
918:iodaconv_validate_testoutput_omps_o3_nm.nc
919:iodaconv_validate_testoutput_ompsnm_o3_l2.nc
923:iodaconv_validate_testoutput_prepbufr_adpsfc_api.nc
924:iodaconv_validate_testoutput_prepbufr_adpupa_api.nc
925:iodaconv_validate_testoutput_prepbufr_sfcshp_api.nc
926:iodaconv_validate_testoutput_radiosonde_obs_2020093018.nc4
928:iodaconv_validate_testoutput_rass_wmo_multi.nc
929:iodaconv_validate_testoutput_rrfs.t06z.adpsfc.prepbufr.nc
937:iodaconv_validate_testoutput_satbias_amsua_n18.nc4
938:iodaconv_validate_testoutput_satbias_cris_npp.nc4
939:iodaconv_validate_testoutput_satbias_gmi_gpm.nc4
940:iodaconv_validate_testoutput_satbias_ssmis_f16.nc4
941:iodaconv_validate_testoutput_satwind_EUMet.nc
942:iodaconv_validate_testoutput_satwind_Himawari.nc
943:iodaconv_validate_testoutput_satwind_Insat.nc
944:iodaconv_validate_testoutput_satwind_obs_2018041500.nc4
947:iodaconv_validate_testoutput_ship_single.nc
948:iodaconv_validate_testoutput_ship_wmo_multi.nc
950:iodaconv_validate_testoutput_singleob.nc
953:iodaconv_validate_testoutput_smap_sss_rss.nc
955:iodaconv_validate_testoutput_smos_sss_l2.nc
956:iodaconv_validate_testoutput_sonde_wmo_multi.nc
958:iodaconv_validate_testoutput_synop_single.nc
959:iodaconv_validate_testoutput_synop_wmo_multi.nc
961:iodaconv_validate_testoutput_tempo_hcho_troposphere.nc
962:iodaconv_validate_testoutput_tempo_no2_stratosphere.nc
963:iodaconv_validate_testoutput_tempo_no2_total.nc
964:iodaconv_validate_testoutput_tempo_no2_troposphere.nc
965:iodaconv_validate_testoutput_test_glider.nc
966:iodaconv_validate_testoutput_tropess_cris_co.nc
967:iodaconv_validate_testoutput_tropomi_co_total.nc
968:iodaconv_validate_testoutput_tropomi_no2_total.nc
969:iodaconv_validate_testoutput_tropomi_no2_tropo.nc
970:iodaconv_validate_testoutput_vadwinds_wmo_multi.nc
972:iodaconv_validate_testoutput_viirs_bias.nc

**Comment by BenjaminRuston** [comment]
@CoryMartin-NOAA just FYI, here's the list

**Comment by BenjaminRuston** [comment]
will pick this up in newly constructed issue
