### ISSUE TITLE
[New issue] IODA naming convention for TOA reflectance 

### ISSUE THREAD

**Issue by weiwilliam** [JCSDA-internal/ioda-converters#1470]
## Description
The existing GOES ABI converter ([goes_converter.py](https://github.com/JCSDA-internal/ioda-converters/blob/e9d7587928acfa554f2778d743c3960d6874597a/src/goes/goes_converter.py)) uses albedo for reflectance factor.
And there is no reflectance term in share/ioda/yaml/validation/ObsSpace.yaml.

In the CF convention, there are planetary_albedo and surface_albedo.
```
planetary_albedo: 
Albedo is the ratio of outgoing to incoming shortwave irradiance, 
where 'shortwave irradiance' means that both the incoming and outgoing radiation are integrated across the solar spectrum.

surface_albedo:
The surface called "surface" means the lower boundary of the atmosphere. 
```
Both of them are integrated across solar spectrum, which is not the case for ABI or VIIRS data.
Should we update the ObsSpace.yaml with toa_reflectance or toaReflectance or toa_bidirectional_reflectance?
Unsure "bidirectional" is the right term for ABI reflectance factor or VIIRS TOA reflectance.
Bidirectional means it depends on angles of incident (zenith) and measured (scan) radiation. 
Tagging @chengdang and @BenjaminTJohnson for the inputs of terminologies.

Nonetheless, the converted `reflectance factor` for GOES ABI is the same term stored in VIIRS L1b data.
Both of them equal to `reflectance * cos(zenith angle)`, so we can use the same variable name in the converted IODA file.

**Comment by PatNichols** [comment]
@weiwilliam This might be for  @gthompsnJCSDA. If new variables are added we would need to update the data conventions accordingly.

**Comment by gthompsnJCSDA** [comment]
If you all don't mind, I wish to close this issue.  To me, this is not an issue.  There is a data convention name of `albedo` that is intended for use in observed satellite data.  I modified the ioda-converter in question from `reflectance factor` to `albedo` over a year ago I think and find it sufficient for our use.  Instead, what I have not yet done is change my own UFO interface code to CRTM to call the UFO variable the same name.  In my own feature branch for visible wavelengths, the variable is referred to as `reflectance` but I intend to change it to `albedo` as early as this week.

**Comment by weiwilliam** [comment]
@gthompsnJCSDA Thanks for the clarification. Please check my follow-up question in [JCSDA-internal/discussion](https://github.com/orgs/JCSDA-internal/discussions/109).
