### ISSUE TITLE
land converter README markdown update

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#1520]
## Description

the current README in the land converter directory should be removed (and it is out of date anyway)

should be removed:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/land/README.md

rather the updated converters instructions should be updated here:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/README.md

## Requirements

a selection of working converters for land

## Acceptance Criteria (Definition of Done)
a clear README explaining converters in the directory and how to call them

**Comment by BenjaminRuston** [comment]
@ClaraDraper-NOAA and @YoulongXia-NOAA here's the issue to update the README let us make a PR updating this file!

https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/land/README.md

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, @ClaraDraper-NOAA, based on ioda converter development, it should not have a README.md in src/land. You can check compo, marine or any others, there is no README.md there. The only README.md is in https://github.com/JCSDA-internal/ioda-converters/tree/develop, it includes all components where there is land to update. @BenjaminRuston, you may need to remove  README.md from develop/src/land and incorporate its contents into the land part of README.md in develop. Thank you.

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, you may also need to update the README.md in develop for land part. As that README for land part was created by me a long time ago, and you need to modify it to match what you did the updates and current land ioda converters do. Thank you.

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA let's just modify this issue and do the changes needed in this file then:

https://github.com/JCSDA-internal/ioda-converters/blob/develop/README.md

and as you recommend remove the one from the `src/land` directory
