### ISSUE TITLE
Check TROPICS WMO satellite ids

### ISSUE THREAD

**Issue by rhoneyager-tomorrow** [JCSDA-internal/ioda-converters#1571]
I'm looking at the NOAA TROPICS L1B to BUFR converter ([link](https://gitlab.ssec.wisc.edu/tropics_dpc/tropics_bufr_for_noaa/-/blob/master/resource_dir/scripts/run_bufr_encode_tropics.R?ref_type=heads#L457)), and realized that they have assigned different ids to the instruments than what are used in the JCSDA converter ([link](https://github.com/JCSDA-internal/ioda-converters/blob/2dcec8b78fd4b3f93ee688d830ce83a8da9347ea/src/hdf5/tropics_2ioda.py#L38-L44)). I checked the ECMWF catalog ([link](https://codes.ecmwf.int/odb/satelliteidentifier/)), and there is a discrepancy.

| Satellite | ioda-converter satellite id (SAID) | ECMWF satellite id |
| --- | --- | --- |
| TROPICS-01 | 933 | 709 |
| TROPICS-02 | 895 | None (failed to orbit) |
| TROPICS-03 | 896 | 228 |
| TROPICS-04 | 966 | None (failed to orbit) |
| TROPICS-05 | 967 | 263 |
| TROPICS-06 | 968 | 264 |
| TROPICS-07 | 969 | 284 |

@BenjaminRuston, you mentioned that you got these assignments from Jeff Ator. Who has an authoritative source?

**Comment by BenjaminRuston** [comment]
great thanks @rhoneyager-tomorrow think these were some early estimates at those.... 

will try to do a tertiary confirmation

**Comment by BenjaminRuston** [comment]
finally back to this... for an authoritative source this is it for me:
https://space.oscar.wmo.int/instruments

**Comment by BenjaminRuston** [comment]
here are ones we should be interested in:

![image](https://github.com/user-attachments/assets/b6d7d919-541c-4f20-ae4f-d663c8fb72ff)

and for TROPICS:
![image](https://github.com/user-attachments/assets/f952e51c-9bb6-460e-8f90-e1f22f686792)

**Comment by BenjaminRuston** [comment]
oh wait think these IDs are instrument IDs and not the WMO satellite IDs

**Comment by BenjaminRuston** [comment]
yup let's use these numbers:
![image](https://github.com/user-attachments/assets/ef460e63-0631-4436-8c8d-100422786862)
