### ISSUE TITLE
TROPICS converter is reading the wrong QC bits

### ISSUE THREAD

**Issue by rhoneyager-tomorrow** [JCSDA-internal/ioda-converters#1574]
https://github.com/JCSDA-internal/ioda-converters/blob/6f87a0f279e836fd604e5b313a25bd1e54bff80e/src/hdf5/tropics_2ioda.py#L315

I've been debugging why the tropics2ioda converter is not producing the same results as my internal TROPICS/TMS converter. `tropics_2ioda.py` has an off-by-one error. The TROPICS L1B describes the calQualityFlag bitfield with bit positions starting at 1, and as the code is written the bit shift goes one position too far.

Here's a comparison of what the converter is currently doing (top), versus what it should be doing (bottom).

![satelliteAscendingFlag_20240917T00Z_noch](https://github.com/user-attachments/assets/651949c3-ef23-4adc-a5bd-07518c4e69b3)
![flagAscDesc_20240917T00Z_ch1](https://github.com/user-attachments/assets/a1799059-6633-463c-b907-7fc6c1abc1d5)

 The QC flag misread causes two issues:
- The day/night flag is stored as `MetaData/satelliteAscendingFlag`.
- The set_missing_value function (https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/hdf5/tropics_2ioda.py#L298) in this converter is designed to skip QC-bad data and avoid writing it to a ioda file. It is misinterpreting the different flags and is filtering the wrong data. Ex: descending orbits are taken to be failures in the hot QC flag.

**Comment by BenjaminRuston** [comment]
here's after bits are shifted:
![image](https://github.com/user-attachments/assets/a37add8e-18e0-4d3f-a125-13e37950e50a)


and for a single orbit:
![image](https://github.com/user-attachments/assets/b4abc60a-1a4d-48e8-bf5d-b7741b4d26af)

**Comment by BenjaminRuston** [comment]
this essentially made this change:
```
-        i_land = get_normalized_bit(quality_word[:, jchan], bit_index=1)
-        i_intrusion = get_normalized_bit(quality_word[:, jchan], bit_index=2)
-        i_maneuver = get_normalized_bit(quality_word[:, jchan], bit_index=3)
-        i_cold_cal = get_normalized_bit(quality_word[:, jchan], bit_index=4)
-        i_hot_cal = get_normalized_bit(quality_word[:, jchan], bit_index=5)
-        i_asc = get_normalized_bit(quality_word[:, jchan], bit_index=6)
-        i_day = get_normalized_bit(quality_word[:, jchan], bit_index=7)
-        i_forward = get_normalized_bit(quality_word[:, jchan], bit_index=8)
+        i_land = get_normalized_bit(quality_word[:, jchan], bit_index=0)
+        i_intrusion = get_normalized_bit(quality_word[:, jchan], bit_index=1)
+        i_maneuver = get_normalized_bit(quality_word[:, jchan], bit_index=2)
+        i_cold_cal = get_normalized_bit(quality_word[:, jchan], bit_index=3)
+        i_hot_cal = get_normalized_bit(quality_word[:, jchan], bit_index=4)
+        i_asc = get_normalized_bit(quality_word[:, jchan], bit_index=5)
+        i_day = get_normalized_bit(quality_word[:, jchan], bit_index=6)
+        i_forward = get_normalized_bit(quality_word[:, jchan], bit_index=7)
```
