### ISSUE TITLE
OBS1.5.EMC21 IODA-converters development and enhancement

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#276]
The goal is to develop and enhance IODA-converters to process GSI NetCDF diagnostic files to IODA format for UFO development
---

### General-purpose of the GSI NetCDF diagnostics in IODA format
- [ ] Observation information (values, metadata, ... etc)
- [ ] Test references (HofX, ObsBias, ..etc)

**Comment by huishao-r** [comment]
Closed this Epic since it is under AOP20. Please update the title and unlink the AOP epics if reopening this Epic.
