### ISSUE TITLE
Prepare test data set with test references for radiosonde temperature observation

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#279]
@emilyhcliu commented on [Wed May 20 2020](https://github.com/JCSDA/ufo/issues/1079)

Make test data set with test references for radiosonde temperature observation

**Comment by srherbener** [comment]
@emilycliu, could you add an estimate to this issue? Thanks!

**Comment by gthompsnJCSDA** [comment]
I am pretty sure this issue can be closed as we have a number of test datasets during Obs team code sprints.  @emilyhcliu  can re-open the issue if she disagrees
