### ISSUE TITLE
netCDF compression for IODA files?

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA-internal/ioda-converters#286]
@YoulongXia-NOAA noticed that the IODA formatted VIIRS AOD files are larger than the original VIIRS AOD files from NESDIS in netCDF format. We realized that the NESDIS netCDF files use deflate_level=2.

Has there been any discussion on using ZLib lossless compression in IODA for saving file size?

**Comment by srherbener** [comment]
The deflate_level=2 is going pretty light on the compression. The deflate levels for netcdf go from 1 to 9 with 9 being the highest level of compression. In the past, I've found that level 6 is a good tradeoff between compression efficiency and speed of IO. I would recommend changing to deflate_level=6.

I think that we have both szip and zlib available for compression. Is there a preference for one of these?

**Comment by CoryMartin-NOAA** [comment]
zlib is more universally accepted. We went through this with GFSv16 recently, supposedly szip is faster, but less efficient at compression, but is not standard. All netCDF4 installs will support zlib.

Would this need to be chosen in the IODA API or could there be an optional argument to choose the amount of compression used?

**Comment by srherbener** [comment]
The new IODA interface allows you to select between szip and zlib, and it also lets you configure the compression level. We could make level = 6 and zlib be the defaults, if you think that would be helpful.

**Comment by CoryMartin-NOAA** [comment]
I think the algorithm should be zlib by default, yes. As far as the level, I'll defer to you or someone else on what the default value would be. 6 is fine for now I think, and we can always change if needed.

**Comment by markjolah** [comment]
I agree. Stick with zlib, because szip and other options are not so portable.  I think anything from `4-8` could be appropriate, I think `6` sounds reasonable.  Also definitely enable `shuffle` filter by default if `zlib` is enabled.  This reduced file size and improved performance in my (limited) tests, but is in general a great idea with our types of data.
