### ISSUE TITLE
Create google spreadsheet documenting the mapping of BUFR Mnemonics to Unified IODA variables for radiance data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#291]
**Create google spreadsheet that maps BUFR Mnemonics to Unified IODA Variables for radiance data:**

- [ ] IASI
- [ ] AIRS/AMSUA on AQUA
- [ ] CrIS
- [ ] AVHRR
- [ ] ATOVS - AMSUA, MHS, and HIRS
- [ ] ATMS
- [ ] SSMIS
- [ ] SAPHIR
- [ ] SEVIRI
- [ ] ABI (not operational)
- [ ] AHI (not operational)

--- 

Template for IODA-variable spreadsheet can be obtained from the following link:
https://drive.google.com/file/d/1xohTp5ADR1AkO1NgXAdI_9qwrDE__mlG/view?usp=sharing

**Comment by huishao-r** [comment]
@emilyhcliu This issue is past due and I don't see any update. Do you want to keep it? If so, would you please link this to AOP21 issues instead. Converter issues should be under OBS3 for AOP21. Please contact @rhoneyager for the correct Epic.

**Comment by rhoneyager** [comment]
The new epic should be OBS3.2.3. @emilyhcliu Feel free to make sub-epics under this to track different aspects of BUFR-related development.

**Comment by huishao-r** [comment]
Closed this issue since it has no activities for a year. Please resume the issue if needed under AOP21.
