### ISSUE TITLE
ioda old file format to ioda new file format converter

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#320]
To facilitate the migration of converters and UFO obs operators and filters to ioda-engines, we need to be able to convert our existing ioda test data to the new ioda format. The primary feature of the new format is the storage of radiance data as a single 2D variable. We need to have both versions of storage (current - set of vectors, and new - single 2D variable) available so that we don't have to switch everything all at once.

**Comment by rhoneyager** [comment]
First PR is #119, and this will probably entail a sequence of five or so PRs.
