### ISSUE TITLE
Update GODAE/FNMOC converters to ioda-engines.

### ISSUE THREAD

**Issue by aerorahul** [JCSDA-internal/ioda-converters#325]
The marine GODAE/FNMOC python converters will be replaced with the new IODA format dictated by IODA-Engines.

Tagging @guillaumevernieres @srherbener for awareness.

**Comment by guillaumevernieres** [comment]
@aerorahul , thanks for doing that work. Marine obs are not part of the obs group yet, switched the milestone to soca.

**Comment by BenjaminRuston** [comment]
@amfox37  or @guillaumevernieres  do you know anything about this one?  should it be closed and a new one reopened if needed?

**Comment by aerorahul** [comment]
It can be closed.
