### ISSUE TITLE
Consolidate GIIRS converters and tests

### ISSUE THREAD

**Issue by markjolah** [JCSDA-internal/ioda-converters#326]
At present, there are multiple giirs converters under the ssec directory:

* The `giirs_ssec2ioda.py` (branch: [feature/giirs_ssec_perfomance](https://github.com/JCSDA/ioda-converters/tree/feature/giirs_ssec_performance)) is currently running on the NRT system and has received bugfixes for problems encountered with production datafiles.

* The `giirs_lw2ioda.py` is obsolete and un-testable by the develop UFO/CRTM operators. It should probably be retired?

* The code in [`src/ssec/Experimental`](https://github.com/JCSDA/ioda-converters/tree/develop/src/ssec/Experimental) is non-functional and non-tested.  It should be retired or resubmitted with a PR and testing.

**Comment by rhoneyager** [comment]
Need to send back to developers and obs team.

**Comment by srherbener** [comment]
@weihanucar we are interested in cleaning up the GIIRS scripts in the ioda-converters repo. We would like to delete obsolete scripts and make sure the scripts that are not obsolete are functional and maintainable.

It looks like the only script being used on our side is `giirs_ssec2ioda.py`. This is being used in the NRT flow for example. So, from our perspective it seems that all the other scripts can be obsoleted (removed from the repo).

Is this the case on your side at the university? If not, please let us know which scripts need to remain in the repository.

Thanks!
