### ISSUE TITLE
BufrConverter: Tool to create YAML files.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#374]
Investigate writing tool that can read BUFR file table data and aid the user in creating YAML configuration data for that file with a GUI of some kind.

**Comment by BenjaminRuston** [comment]
@emilyhcliu your call is this still its own issue.  This seems a bit broad and vague to me.  Is it covered by other issues, or is there something more specific?

**Comment by rmclaren** [comment]
I'm going to close this issue.
