### ISSUE TITLE
Issue on not fill zero values for snow depth in GHCN some stations

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#378]
I am working GHCN ioda converters for GHCN snow depth. Now I have an issue about not fill zero values for snow depth in GHCN some stations when snow depth is zero.  The data file use the space instead. I do not know if this is missing value or not fill zero value from the data file. Now my python code assumed as that it is missing value. Does anyone has experience to process this situation?

**Comment by YoulongXia-NOAA** [comment]
If who knows the experts in this direction, please assign her/him here so that I can get help.

**Comment by amfox37** [comment]
I believe this potential problem came up in our discussion on Monday, but @tsga indicated it had been addressed. Can you check in with him to make sure about that? Thanks, Andy

**Comment by YoulongXia-NOAA** [comment]
Okay, I will share my python code with @tsga and see if my code also fixes that problem. @tsga, could you please check my python code in feature/ghcn_snowd and see if it has fixed this problem?

**Comment by tsga** [comment]
@YoulongXia-NOAA, let's have a short call, the two of us, and talk about it. I think you already have addressed it, but let's just go over it to make sure.

**Comment by YoulongXia-NOAA** [comment]
Tsega and I have looked at my python code. The code has fixed this issue. So I closed it. Thank you all for your inputs and comments.
