### ISSUE TITLE
Bufr Converter: Add ability to read BUFR sequences.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#384]
Currently the BUFR converter uses the NCEPLib BUFR calls **ufbrep** and **ufbint** to read BUFR mnemonic data. There is however a seperate class of data, sequences, which we do not handle (read using **ufbseq**).

YAML wise we could extend the section mnemonicSets with a new type, **_sequence_**.

**Comment by rmclaren** [comment]
Currently thinking about the following YAML format changes to the BUFR description section.

- Remove mnemonicSets section
- Add sequences section (I'm going to try to eliminate the need for this section).
- Bufr export variables now indicate a path to the Mnemonic so it lists the sequences.
- Bufr export variables now list the indices that are desired to be exported for a specific key.

Here is an example how this might look:

![Screenshot from 2021-02-10 09-03-03.png](https://images.zenhubusercontent.com/5efcacfc3b91075e014181ba/c56529d8-e25e-4e6a-9443-39a2de6caf47)

**Comment by gthompsnJCSDA** [comment]
@rmclaren  So is a sequence the same as what debufr.x reports as a 'replication?'  If I interpret your screen capture correctly, I assume that a sequence of __root__ would be any unchanging header-like data for station ID/name, position info, a radiosonde launch time; but any named sections below root are referring to the repeated info such as a air_temperature at distinct heights of a sonde while it ascends.  Is this correct?

Also, are the final three vars in your exports doing mathematics such as value of ROSEQ3 divided by PCCF?

**Comment by rmclaren** [comment]
Hi Greg,

Let me start by posting a part of a BUFR table as an example:

![image.png](https://images.zenhubusercontent.com/5efcacfc3b91075e014181ba/5912745e-cd6a-4d25-b984-8d047f8812c3)

So in BUFR there are basically two types of mnemonics (basically data field ID's). **Data** mnemonics such as CLATH which are straight forward mnemonics that represent a data field (via a "Table B" descriptor), and **sequence** mnemonics that represent an ordered set of sub-elements (defined by a "Table D" descriptor) where each element can be described by its own own mnemonic either **sequence** or **data** (sequences can be arbitrarily nested).

A simplistic way of thinking about it is that an **data** mnemonic is just a data field, and a **sequence** mnemonic is a list of other mnemonics.

So in this example above the mnemonic NC003010 is a sequence, so is ROSEQ1, ROSEQ2, ROSEQ3, LTLONH etc... The right hand columns tell you what the sequences map to. So far so good, but if you look closely at the right hand column you will see that some of the mnemonics have strange brackets around them "(" or "{" or "[" or even "<". Basically these indicate **replications**. "Delayed Replications" to be exact. Basically this means that the data associated with the mnemonic enclosed mnemonic is repeated a certain number of times (how many times is defined in the data itself [the number of repeats is defined on the fly]). Sometimes you will see a mnemonic wrapped in quotes with a number after it "ABCDE"5, this indicates a fixed length replication (the number of repeats is predefined). So no, sequences and replications are not the same thing. Usually they put sequences inside the brackets so sometimes the call it a replication sequence (its really just a sequence that is repeated).

Ok good, but what did I mean by the **__root__** sequence. In our previous example the mnemonic NC003010 is a little special. If you look at the BUFR table data you'll quickly realize that its describing a tree like data structure. In this tree the mnemonic NC003010 is the root (or central trunk if you want to think of it that way). The sequences are the branches and the data fields form the leaves. The sequence NC003010 is often referred to as a **subset** (the string "NC003010" is the subset identifier). A message in a file may have many **subsets** defined (the above example is very simple in that it only has 1), many of them having subtle differences from each other (it usually depends on the instrument that generated the data). When I say **__root__** I mean this root sequence (no matter the sequence [subset] identifier). So I believe you were on the right track with your description earlier.

What does the string "ROSEQ3/PCCF" mean? Think of it like a **path** string. ROSEQ3 is a sequence and PCCF is a data field contained within that sequence. So the string says goto the sequence called ROSEQ3 (sequence of refractivity data) and get the data associated with the mnemonic PCCF. Lets call that data the refractivity_percent_confidence and call it a day :)

**Comment by rmclaren** [comment]
Unfortunately this issue turned into a rather big deal as it necessitates some rather extensive extensions to the NCEPLIB-bufr library. Please see issue #589.

**Comment by rmclaren** [comment]
Current State As of Today:

- Updated so that it uses the new interface in the NCEPLIB-bufr library.
  - YAML file now used query strings and no longer have a mnemonicSets section.
  - Basic retrieval of data works (repeated sequences of all kinds should basically work).
- What I'm working on. **
  - Working on adding support for CCITT IA5 character fields.
  - Updating existing features to be useful in the new non-mnemonic paradigm and be compatible with CCITT IA5 fields.
- Things I need to do after the stuff I'm working on.
  - Support for the for fields so you can make datasets that make sense in the light of repeated sequences (not hard as most of the leg work is done).

**Comment by rmclaren** [comment]
Issue addressed by PR #1006.
