### ISSUE TITLE
ghcn_snod test fails due to file not found.

### ISSUE THREAD

**Issue by aerorahul** [JCSDA-internal/ioda-converters#393]
https://github.com/JCSDA-internal/ioda-converters/blob/cfa4344fd5a0845c7b889ac50ac5ae538898efeb/test/CMakeLists.txt#L496

This test will always fail because the `doc/fix/ghcn-stations.txt` is not present in the `CMAKE_BINARY_DIR`

**Comment by YoulongXia-NOAA** [comment]
Will take a look soon when hera returns tomorrow. Thank you.

**Comment by YoulongXia-NOAA** [comment]
Hi Rahul,

I just did on hera: 
git checkout develop
git pull
git checkout feature/smap_ssm
git merge develop

and then did:
ecbuild, make, make install, and ctest command. The last two tests are:

Start 36: test_iodaconv_ghcn_snod
36/37 Test #36: test_iodaconv_ghcn_snod ..............   Passed    4.08 sec
      Start 37: test_iodaconv_smap_ssm
37/37 Test #37: test_iodaconv_smap_ssm ...............   Passed    0.87 sec

100% tests passed, 0 tests failed out of 37

Label Time Summary:
iodaconv    =  29.16 sec*proc (36 tests)
script      =  29.16 sec*proc (36 tests)

Total Test time (real) =  29.62 sec

I checked /scratch2/NCEPDEV/marine/Youlong.Xia/ioda-converters/build/ =  ${CMAKE_BINARY_DIR}, doc/fix has file ghcn-stations.txt.  I am not sure the reason that you cannot find it.

**Comment by srherbener** [comment]
I think the issue is that when you build ioda-converters in a bundle ${CMAKE_BINARY_DIR} is set to point to the top of the build area but the ioda-converter CMake configuration is placing the doc/fix files in ${CMAKE_BINARY_DIR}/**iodaconv**/doc/fix. The tests cannot find the files because they expect them to be in ${CMAKE_BINARY_DIR}/doc/fix.

When you build ioda-converters stand alone (not in a bundle), the CMake configuration is placing the doc/fix files in ${CMAKE_BINARY_DIR}/doc/fix and then the tests work.

**Comment by YoulongXia-NOAA** [comment]
I am not familiar with that part. Stephen, could you please help to fix it?

**Comment by srherbener** [comment]
I can, but I won't be able to get to this for a while. I'm extremely busy with assisting the OBS code sprint and getting the IODA PRs in place.

**Comment by YoulongXia-NOAA** [comment]
Okay, Stephen. Do not worry this issue and do your work first. Let me git clone the bundle and see if I am able to fix it. Which bundle do I need to clone?

**Comment by srherbener** [comment]
@YoulongXia-NOAA, use jcsda-internal/ioda-bundle and add this line after the similar line for the ioda repository:

```
ecbuild_bundle( PROJECT iodaconv GIT "https://github.com/JCSDA-internal/ioda-converters.git"   BRANCH develop UPDATE )
```
Thanks for giving this a shot.
