### ISSUE TITLE
Bufr Converter: Add transform to make it possible to transform longitude 0-360  to -180-180 and vise versa.

### ISSUE THREAD

**Issue by rmclaren** [JCSDA-internal/ioda-converters#395]
Unfortunately there is currently no easy way transform longitude that are represented as 0-360 into -180-180 via the YAML configuration. We should add a transform to make this possible.

**Comment by gthompsnJCSDA** [comment]
@rmclaren  You may wish to close this issue, because you have tackled and solved this problem.

**Comment by rmclaren** [comment]
Actually this problem is not solved. I will need to add a special transform to make this possible.

**Comment by BenjaminRuston** [comment]
@gthompsnJCSDA there is no movement on this, closing until a plan is made

**Comment by rmclaren** [comment]
Please keep this issue open.

**Comment by BenjaminRuston** [comment]
@rmclaren again an issue can be added or opened when there is a plan for when it's going to be addressed.  Would be good to distribute the work if we can, is there anyone else who could be added to the issue to work on it?
