### ISSUE TITLE
IODA converter example to be added

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#396]
I have opened the [feature/converter-example](https://github.com/JCSDA-internal/ioda-converters/tree/feature/converter_example) branch on JCSDA-internal/ioda-converters.

The purpose is to add an sample of how the ioda converter would be. 

In the branch, there is:
- a README file dictating how to run the converter, information about the input, output, yaml input, and environment file.
- an input data directory and bufr file
- an output data directory and sample output 
- sample yaml file used with the converter
- a sample file that sets the environment required to run the converter. It is what can be used on Hera. 

The branch was pushed at 4:52pm EST on 1/13/21

**Comment by nicholasesposito** [comment]
Additional information:
When the feature/converter-example branch is checked out, the project is in the CONVERTER_EXAMPLE directory.

The README and HERA environment file are both in the main directory.
There is also the yaml used with the converter in the main directory, and it is named "bufr_adpsfc.yaml"
The input data is in the DATA/ directory and is named "adpsfc"
The output directory is named testoutput/ and there is sample output named "ioda_encoder_result_adpsfc.nc"

**Comment by aerorahul** [comment]
1. Please don't include the HERA file.  This is not a place for it.
2. Name the testinput file for adpsfc bufr as the original; e.g. gdas.t00z.adpsfc.bufr_tm00 
3. name the testoutput file for adpsfc netcdf as e.g. gdas.t00z.adpsfc.nc
4. The Input and output data needs to be in testinput and testoutput directories.
5. The README.md should be updated in the bufr directory.

**Comment by CoryMartin-NOAA** [comment]
Just for my understanding/clarification, is this supposed to parallel the existing test/example that @rmclaren has (https://github.com/JCSDA-internal/ioda-converters/blob/develop/test/testinput/bufr_mhs.yaml and https://github.com/JCSDA-internal/ioda-converters/blob/a6140dc9107817f8dd23b4c57a50ef54ceba0dbc/test/CMakeLists.txt#L450) but for adpsfc?

**Comment by nicholasesposito** [comment]
Cory, yes, this will be parallel to it. I'll probably name it "test_iodaconv_bufr_adpsfc2ioda".
Rahul, will do. Working on it now.

**Comment by nicholasesposito** [comment]
Rahul - ignore most of my previous email. I added all of the changes, minus the ctest. I took the README out because yes, it should be explained in the contents of the bufr directory. The input yaml/bufr and output nc are in the testinput and testoutput directories, respectively. The environment file has been removed.

I made the changes to add the ctest to test/CMakeLists.txt, but I couldn't get it to work. I think I'm missing something, I've tried numerous combinations of things, including getting rid of the "Command" and changing around the ARGS. I couldn't determine any additional files to add this test to after looking around for awhile. ecbuild and make don't seem to make a difference in getting the test to show up. Any ideas? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@nicholasesposito as far as I can tell it looks like you added the new test correctly. Let me checkout the branch and see if it is there for me.

**Comment by aerorahul** [comment]
@nicholasesposito 
your branch is stale.
You are using the "newer" format for yaml with the old code.
Please update your branch and fix the yaml file.

**Comment by aerorahul** [comment]
@nicholasesposito 
I merged `develop` in your branch and fixed the `bufr_adpsfc.yaml` file.
The test fails because `nccmp` fails.  It failed because the reference output file is has a `coordinate of latitude longitude` on `datetime` variable.  it should not.
I fixed that too.

See branch `feature/converter_example-fixed`
