### ISSUE TITLE
Replace/modify ioda_conv_ncio for ioda-engines

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA-internal/ioda-converters#399]
Most of these converters are python-based and they leverage the ioda_conv_ncio module included in this repository. If it's relatively easy enough, the best/fastest way to update all the converters is to keep the scripts the same and modify the module they call to use the ioda-engines python bindings rather than the netCDF I/O and setup routines defined in ioda_conv_ncio.py

**Comment by srherbener** [comment]
@CoryMartin-NOAA, thanks for submitting this issue. @rhoneyager and I are meeting this week to discuss doing exactly what you are suggesting. The BuildNetcdf routine in ioda_conv_ncio.py appears quite amenable to converting to using the ioda-engines Python API.

**Comment by CoryMartin-NOAA** [comment]
Going to use the TROPOMI NO2 converter as a first attempt to modify ioda_conv_ncio, and then will try it with the GSI ncdiag converter next.
