### ISSUE TITLE
The CI test configuration is not building and testing the new EMC converter.

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#407]
The new EMC converter is a C++ implementation that can convert a number of radiance and conventional obs types provided in BUFR and prepBUFR files. It is set up to build and test optionally when eckit, bufr, oops and ioda libraries are available (since these are dependencies).

I believe that eckit and bufr are being built in the CI testing configuration, and it looks like ioda and oops need to be added.

@mer-a-o can you help us get this fixed? Thanks!

**Comment by mer-a-o** [comment]
@srherbener Do we want to have a bundle of ioda-converters, ioda, and oops for ioda-converters Codbuilds?

**Comment by srherbener** [comment]
@mer-a-o let's use ioda-bundle as we discussed in the core team meeting today. The ioda converters build is enabled with `BUILD_IODA_CONVERTERS=ON`. Example:
```
ecbuild -DBUILD_IODA_CONVERTERS=ON path_to_source
```

Let me know if you need anything else. Thanks for helping with this!

**Comment by srherbener** [comment]
@mer-a-o, another detail is that the following modules need to be accessible:

- bufr
- gsl-lite

ioda-bundle provides the other dependencies for the converters:

- eckit
- oops
- ioda (which includes ioda engines)
