### ISSUE TITLE
Implement and Validate BUFR to IODA Conversion for Scatterometer Winds

### ISSUE THREAD

**Issue by JeffreyKSmith-NOAA** [JCSDA-internal/ioda-converters#412]
Create Python driver and YAML file to use bufr2ioda.x to convert scatterometer winds BUFR files to IODA format. Validate the conversion.

**Comment by JeffreyKSmith-NOAA** [comment]
A first attempt has been created and the output has been validated. A discussion of what fields are to be transferred to the IODA netCDF file is needed.

**Comment by ilianagenkova** [comment]
@JeffreyKSmith-NOAA provided output from converting ASCAT winds from prepbufr file.

**Comment by JeffreyKSmith-NOAA** [comment]
BUFR to IODA conversion script and YAML file for scatterometer winds was adjusted to use PREPBUFR data. The satwinds BUFR to IODA validation script was adapted for scatterometer winds. Validation script shows agreement between the BUFR and the IODA files.

**Comment by gthompsnJCSDA** [comment]
@ilianagenkova   I am moving this issue into "Backlog" and assigning to myself to keep updated.  Can one of you two provide me an update and where I can see the yaml and test data file so we can check this box and close the issue this month?

**Comment by ilianagenkova** [comment]
I validated the output provided by @JeffreyKSmith-NOAA  (shared on Hera). 
Jeff, do you still have that data around. I deleted by copy b/c I was hogging Hera recently.

**Comment by JeffreyKSmith-NOAA** [comment]
To answer your question, I would have to remember what data I gave you...

-
Jeff Smith
Scientific Programmer/Analyst
IMSG at NOAA/NWS/NCEP/EMC
5830 University Research Court, Room 2096
College Park, MD 20740
301-938-4537
***@***.***

"Any fool can write code that a computer can understand. Good programmers
write code that humans can understand." - Martin Fowler

**Comment by ilianagenkova** [comment]
@gthompsnJCSDA , 
@JeffreyKSmith-NOAA's files are on Hera:
 /home/Jeffrey.Smith/my_scat/ascat_processing_20210212210753 
I will email you the files, in case you don't have Hera account yet.
