### ISSUE TITLE
Initial implementation for ASCAT Level 2 NRT Soil Moisture Normalized converter

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#415]
## Description

Provide an initial implementation for ASCAT Level 2 Soil Moisture Normalized converter in support the community land DA task.

To finally add the capacity of converting native netcdf format ASCAT soil moisture data including its errors and pre-qc flag to ioda-converters standard netcdf format, a new python converter code needs to be added.  The instructions needs to be added in README.md file, and input and output files need to be added in testinput and testoutput subdirectory, and the corresponding CMakeLists.txt files need to be revised and/or added. 

## Requirements

A new python code needs to be added.

## Acceptance Criteria (Definition of Done)

The code needs to be written, tested, and committed to github feature branch, a new PR needs to be pulled and the reviewers needed to asked, and the feature branch needs to be merged into the development branch.
 
## Dependencies

No

Does this block progress on other issues?
 No

**Comment by YoulongXia-NOAA** [comment]
ASCAT level 2 soil moisture websites:
25km - https://vnavigator.eumetsat.int/product/EO:EUM:DAT:METOP:SOMO25, https://navigator.eumetsat.int/product/EO:EUM:DAT:METOP:SOMO25

12.5km -  https://navigator.eumetsat.int/product/EO:EUM:DAT:METOP:SOMO12

**Comment by YoulongXia-NOAA** [comment]
SMOS Level 2 NRT Soil Moisture Normalized:
Unit: 0-100%

The example of filename for 25km:
W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,METOPA+ASCAT_C_EUMP_20201111013300_72972_eps_o_250_ssm_l2.nc

The example of filename for 12.5km:
W_XX-EUMETSAT-Darmstadt,SURFACE+SATELLITE,METOPA+ASCAT_C_EUMP_20201111132100_72979_eps_o_125_ssm_l2.nc

File format: netcdf

**Comment by YoulongXia-NOAA** [comment]
Pre-QC procedure:

If  Wetland_flag >15%  (Dharssi et al., 2011) or topography_flag > 20% ( Dharssi et al., 2011)
pre-qcflag = 1        ! quality is poor and not in use

then

pre-qcflag = 0   ! good quality

**References:**
Dharssi, I., K. Bovis, B. Macpherson, and C. Jones, 2011: Operational assimilation of ASCATsurface soil wetness at the Met Office, Hydrol. Earth Syst. Sci., 15, 2729–2746.

**Question:** Can we add Wetland_flag and topography_flag in ioda-converters standard netcdf output in as extra variable in @MetaData so that the land DA users can make QC in UFO part?

**Comment by YoulongXia-NOAA** [comment]
**ASCAT Level 2 NRT soil moisture user guide and handbook:**

https://www-cdn.eumetsat.int/files/2020-07/ASCAT%20User%20Guide.pdf
https://www-cdn.eumetsat.int/files/2020-04/pdf_ascat_lev2_soil_moisture.pdf
https://www-cdn.eumetsat.int/files/2020-04/pdf_soilmoisture_prod_hb.pdf
https://www-cdn.eumetsat.int/files/2020-04/pdf_ascat-b_l2_soil_moisture_pvr.pdf

**Comment by aerorahul** [comment]
@YoulongXia-NOAA 
The code block:
```
If Wetland_flag >15% or topography_flag > 20% ( Dharssi et al., 2011)
   pre-qcflag = 1 ! quality is poor and not in use
else
pre-qcflag = 0 ! good quality
```

reads like a filter and should be implemented in the UFO.  

Where are the Wetland_flag and topography_flag variables being read in from?  If they are in the original dataset, then transferring this data to the IODA netcdf is fine.

**Comment by YoulongXia-NOAA** [comment]
These flags are read from ASCAT input file. Can I transfer these two flags into ioda netcdf file in @metadata? I looked at all output netcdf files in testouput directory, and I found only  one file containing zenith angle in @metadata but no other flags are outputted there. These input data include both satellite and in-situ observations. If you suggest me to include them in output file, I will work on that way. This is what Clara Draper at GSL would like me to do.

**Comment by aerorahul** [comment]
@YoulongXia-NOAA 
Yes, absolutely do transfer the data from the ASCAT input file to the IODA netCDF file.
That is the purpose of the converter to translate/transfer from the input (ASCAT) to output (IODA).  The only restriction imposed is to not add information that could be perceived as subjective.

**Comment by YoulongXia-NOAA** [comment]
Okay, originally I thought that I can transfer obs value, error and pre-qc flag, lat, lon, time to ioda format netcdf file. Now you told me that I can transfer some flags to ioda format netcdf file. That is great. I can do that and ask you to review when I pull a PR in future.

**Comment by YoulongXia-NOAA** [comment]
I will use WetlandFraction and TopographyComlexity as the two flags' names. This may be needed to to ask Greg to add them to his ioda_ObsConventions document.

**Comment by ClaraDraper-NOAA** [comment]
Thanks Youlong, Can you please also add the soil_moisture_error too (if you have not already)?

**Comment by YoulongXia-NOAA** [comment]
Yes, it is one of the three needed variables (observed value, error and pre-qc), already in list.

**Comment by ClaraDraper-NOAA** [comment]
Perfect, thanks.
