### ISSUE TITLE
NCAR needs path to migrate their ioda test files to the new ioda format

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#419]
@srherbener commented on [Thu Feb 04 2021](https://github.com/JCSDA-internal/ioda/issues/85)

NCAR has built up a repository of test files (including ioda obs files) over the past year and need a path for migrating this data set to the new ioda format which will be introduced in the upcoming JEDI 1.1.0 release.

Other partners may also have this issue.

Options for addressing this issue:

- Update ioda converters to output the new ioda format and regenerate the files
- Create a "old ioda" to "new ioda" converter and run it on the data set
    - See jcsda-internal/ioda-converters#320 for some details about this approach

It could be that a combination of these approaches may be the best answer. It's possible that the ability to re-run a converter for some of the files is not feasible.

**Comment by srherbener** [comment]
Sorry, I built this in the wrong repo so I used the github move issue to place it here.

**Comment by srherbener** [comment]
Who from the OBS team should be assigned to this?

**Comment by svahl991** [comment]
Tagging @liujake and @snyderdad on this issue.

**Comment by snyderdad** [comment]
My understanding is that converters from old to new IODA format are in place (via #320 ?).  They're working for us at present, though we haven't migrated all activities to IODAv2, in part owing to performance issues that are still outstanding. 

@jjguerrette , @jamiebresch , please correct if I am wrong.

**Comment by liujake** [comment]
Yes. Our old ioda files were converted to ioda-v2 format. This issue can be closed.
