### ISSUE TITLE
Add support to user defined variables and attributes when using the new c++ converter 

### ISSUE THREAD

**Issue by cyberbass** [JCSDA-internal/ioda-converters#420]
## Description

Need the capability to add certain variables or attributes created by the user rather than transferring from their bufr equivalents. 

For example: 
1. Add metadata such as`platformCategory` or `instrumentName` for designated platform/instrument as a global attribute to the output netcdf file. 
2. Add variable such as: `Center Wavelength` to specify the wavelength of each radiance channel.

## Requirements
None

## Acceptance Criteria (Definition of Done)

Capable of defining and adding variables when output the ioda netcdf file. 

## Dependencies

None

**Comment by cyberbass** [comment]
Working on converting the MHS bufr data to ioda format following the new naming convention. Current working yaml and sample outputs can be found on s4 under the following path:

Yaml:
```
/data/users/nchen/CodeSprintDec20/build/ioda-bundle/iodaconv/test/testinput/bufr_mhs.yaml
```

Output:
```
/data/users/nchen/CodeSprintDec20/build/ioda-bundle/iodaconv/test/testrun/gdas.t18z.1bmhs.tm00.nc
```

**Comment by cyberbass** [comment]
@rhoneyager @srherbener Do you have some quick instructions so that I can start to look if we can add some global attributes first?

**Comment by huishao-r** [comment]
@cyberbass This work is not particular for radiance. You may use OBS1.2.2 for the Epic. In addition, please update the title and your description to indicate what converter you are talking about, e.g., BUFR converter

**Comment by srherbener** [comment]
@cyberbass, as we discussed in last Thursday's meeting (2/4/2021), we don't want to be introducing new obs variables via YAML, but it is okay to add global attributes and supplementary meta data (such as channel wavelength) that are not available in the input BUFR. 

Note that meta data is typically added as a 1D variable that is indexed by the relevant dimension of the obs data it is describing. Say you have radiance obs data which (eventually) is 2D, nlocs X nchans. Then the wavelength metadata would be a 1D variable dimensioned by nchans. The variable would be called something like channel_wavelength@MetaData for now, but eventually we want to use @gthompsnJCSDA's naming convention.

Take a look in the ioda repository for examples:

- `src/engines/Examples/Basic` for C++
- `src/enginesExamples/Ptyhon` for Python

Look at the Attributes related examples to see how a global attribute is added.

I'm happy to help further if you have more questions.

**Comment by cyberbass** [comment]
@srherbener Thanks Steve! I am doing as you described above and looking into the ioda repo for examples.

**Comment by rmclaren** [comment]
Please take a look at simular issue #377.

Basically the result of today's meeting we agreed to add a "globals" section to the ioda section in the YAML file. We also said that we would add a new variable type, mapping variable to the exports/variable section.

On second though about mapping, it might be more appropriate to have the mapping as a transform instead of another variable type so the YAML would read as follows:

exports:
    variables:
        my_variable:
           mnemonic: SAID
           transforms:
               mapping:
                   _1 : Geos 16
                   _2 : Geos 17
                   ....

              ..or..
               mapping:
                   file : ./path/to/my/dictionary.yaml

**Comment by cyberbass** [comment]
Global attributes added to the ioda file with preliminary code commited to branch: 
```
feature/bufr2ioda-global_attributes
```
