### ISSUE TITLE
Create google spreadsheet documenting the mapping of BUFR mnemonics to Unified IODA variables for ozone data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#424]
## Description

**Create google spreadsheet that maps BUFR Mnemonics to Unified IODA Variables for ozone data:**
- [ ] SBUV (not operational)
- [ ] GOME (not operational)
- [ ] OMI
- [ ] OMPS Nadir
- [ ] OMPS Total Column
- [ ] OMPS Limb (under development)

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by jeromebarre** [comment]
What is the status of this? BUFR mnemonics is specific to NCEP and is not really part of the joint effort accross agencies. IODA converters for Ozone instruments would still need to be developped for non NCEP applications.

**Comment by jeromebarre** [comment]
Again what is the status on this? Should we close? Or move this to AOP2022. I suggest we create a EMC pipeline for AOP 2022. See other O3 related issues.
