### ISSUE TITLE
NOAA EMC Observation Data (BUFR/PrepBUFR) to IODA Conversion Software Development

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#425]
### **What is it?**
- C++ tool that converts BUFR file to IODA ObsGroup object (saving to as NetCDF if desired).
- YAML file is used to describe the mapping between the input and the output.
- Supports simple transformations of “export” data so that the units of the data can be converted to the desired representation.
- Compiles to a library that can be used by other applications.
- Creates convenient executable bufr2ioda.x <yaml path>.
- Source found in [ioda-converters/src/bufr](https://github.com/JCSDA-internal/ioda-converters/tree/develop/src/bufr)

### **Why do we need it?**

- Data observation processing gathers data from various sources and generates BUFR encoded data (like PREPBUFR files). In the past the target applications (models and simulations) would use these files directly. This meant each endpoint needed to write code to get the data they needed.
- The JEDI application framework takes care of reading and filtering of the source data for the endpoints (using IODA and UFO components). It handles its internal data as ioda::ObsGroup objects, but only has the capability to read these from NetCDF files. It is extensible with new data backends, however.
- Obs Processing needs to have the ability to provide these JEDI based applications with the data they need, but all the infrastructure is built around BUFR. Up until recently this was handled with python programs the translated the data to the NetCDF format. It’s a lot of work to create a program for each data type, however, and python is relatively slow to run.
- The BUFR converter is a fast format converter which only needs some configuration to work. In the long term it can be integrated into JEDI IODA as another data backend removing the need for a pre-processing step.

### **Documentation**

[BUFR Converter explained](https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/bufr/README.md)

**How-to Documentation**
- How to run BUFR Converter on [Hera](https://docs.google.com/document/d/18j78LwUe_nYMWCHZUmpjP0FDO6gYO4CEN9JIjSJBqNU/edit?usp=sharing) and [Orion](https://docs.google.com/document/d/13u88bY6jTrnwRDYy4MQe4ml2luNV6itpzktdoRYC8_w/edit?usp=sharing)

- [How to build/install NCEPLIB-bufr and IODA-Converters with feature/query](https://docs.google.com/document/d/1_AvC3Ebt3R5EeMtHgl1nwKLEPXy-2J9nIqpDJvCL7ME/edit?usp=sharing) - updated on July 30, 2021

**Presentations by Ron Mclaren:**

- [BUFR Converter - IODA-Engines based Ingester @ JEDI Discussion](https://drive.google.com/file/d/1Qir_GVwLyihu0RjUaP7sOxOy3Gv8nT5o/view?usp=sharing) - - Feb 03, 2021

- [BUFR Converter - IODA-Engines based Ingester @ MDAB-DAQC Group Meeting](https://drive.google.com/file/d/1E5w-kHB6fC8llEre-c1mzHPIPW_dRG22/view?usp=sharing) - Feb 10, 2021

- [feature/query Introduction](https://docs.google.com/presentation/d/1q-_-pB5z3yBflwyDo6EWXn4CXE9tZlMC0TdMqIrcs08/edit?usp=sharing) - July, 20, 2021

### **Resources**
- [JEDI Documentation (latest)](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/)
- [ECMWF ODB Database](https://apps.ecmwf.int/odbgov/unionall/)
- [NOAA NCEP BUFR Tables](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/)

### Task List 
[feature/query](https://docs.google.com/spreadsheets/d/1D68rWHCvuv3dOpZUGAGMqDdHqQD6c9VexMnJRf_QoXU/edit?usp=sharing)

---

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by huishao-r** [comment]
@emilyhcliu I updated the Epic to AOP21 Epics, given this work is continued under OBS3.

**Comment by srherbener** [comment]
Sorry about the addition of jcsda-internal/ioda/issues/383 to this epic. I hit the wrong button. I'll remove it now.
