### ISSUE TITLE
NOAA EMC BUFR to IODA Conversion Software Support and Enhancement for Satellite Derived Winds

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#426]
## Description

This Epic is to support and enhance the BUFR/PrepBUFR to IODA (bufr2ioda) conversion software development (Epic #425) through the following work for satellite-derived winds (AMV and Scatterometeor winds) used in the current GDAS operational system :

- Extract BUFR Mnemonics and related information (variable definition, dimension, and unit) used by GDAS analysis (GSI) from the BUFR file
- Create variable mappings between BUFR Mnemonics and the [Unified IODA Naming Convention](https://docs.google.com/spreadsheets/d/1aD4I02JZwvB1nANFT-oxmYq6m28CuyhernDlLEsq79s/edit?usp=sharing)
- Maintain the YAML files ([old BUFR format](https://github.com/JCSDA-internal/ioda-converters/blob/develop/tools/run_satwnds/satwnds_old_subset_template.yaml) and [new BUFR format](https://github.com/JCSDA-internal/ioda-converters/blob/develop/tools/run_satwnds/satwnds_new_subset_template.yaml)) that contain the mapping information between the BUFR Mnemonics (input) and the Unified IODA Naming Convention (output) for each data type.
- Test the bufr2ioda conversion software with the YAML file for each data type
- Verify the conversion for each data type
- Enhance the bufr2ioda software if desired
- Use BUFR from Tank instead of Dump for BUFR to IODA conversion (QC work between Tank and Dump will be implemented in UFO)
- Need to figure out how to deal with satellite wind data processed through prepbufr (https://github.com/JCSDA-internal/ioda-converters/issues/426#issuecomment-786731971)

### **Sub-Epics** 

- [Atmospheric Motion Vector Winds](https://github.com/JCSDA-internal/ioda-converters/issues/445)
- [Scatterometer Winds](https://github.com/JCSDA-internal/ioda-converters/issues/446)

### **Documentation**

- [NOAA EMC satellite-derived winds processing and data types](https://docs.google.com/presentation/d/1D44f69vNfuu8l7iHOw2IYvixN2bQlrLN4-cuW6RgNGY/edit?usp=sharing)
- [How to process NCEP EMC satellite-derived AMV winds to IODA](https://github.com/JCSDA-internal/ioda-converters/blob/develop/tools/run_satwnds/README.md)
- [Iliana's slides for satellite wind bufr converter and splitting (Feb 08, 2021)](https://drive.google.com/file/d/1jL1aOcb7Qz5shx0_SmoniWiUkSXGh1rD/view?usp=sharing) --- contains information about  dates switching from the old BUFR format to the new BUFR format for some subset types

### **Resources**

- [WMO OSCAR - List of All Instruments](https://www.wmo-sat.info/oscar/instruments)
- [WMO OSCAR - List of All Satellites](https://www.wmo-sat.info/oscar/satellites)
- [ECMWF ODB Database](https://apps.ecmwf.int/odbgov/unionall/)
- [NOAA NCEP BUFR Tables](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix/)
- [Observational Data Processing at NCEP](https://www.emc.ncep.noaa.gov/emc/pages/infrastructure/obs-data-processing.php)

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of this issue.

What problem needs to be fixed? What new capability needs to be added?

If this is a bug, describe the current behavior.

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

What must be done before this can be done?
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - add this issue as a dependency to other ZenHub issues as appropriate

**Comment by emilyhcliu** [comment]
The satellite-derived AMV wind has its own bufr dump file.  However, there are also satellite-derived AMV winds in prepbufr as well

Using 20210219 00Z prepbufr and satellite wind bufr dump file as examples:

Subset in satellite wind bufr (AMV winds) dump file - gdas.t00z.satwnd.tm00.bufr_d

Get satellite wind subsets by doing the following:
**split_by_subset.x** gdas.t00z.satwnd.tm00.bufr_d 
```
################################################
    TYPE    MESSAGES       SUBSETS         BYTES
################################################
NC005044        1002         48901       9786404
NC005045         658         32199       6443788
NC005046        1101         53860      10778694
NC005067        5080        137125      50462070
NC005068         604         16256       5982312
NC005069        8456        228215      83983314
NC005070          53          3478        482826
NC005071          61          4248        589518
NC005080         184         12512       1736592
NC005091         250         55385       2455070
NC005024        1693         82808      16571904
NC005025          12           549        109910
NC005026        1213         59269      11861244
NC005030        2131        506016      21211580
NC005031         473        125244       4687526
NC005032        5592       1606545      55726432
NC005034         882        217882       8770618
NC005039         223         57281       2178790
```
Get satellite wind from prepbufr file by doing the following:
**split_by_subset.x gdas.t00z.prepbufr**
```
################################################
    TYPE    MESSAGES       SUBSETS         BYTES
################################################
ADPUPA           317          1309       2728682
AIRCAR          1742        162670      17320754
AIRCFT           336         32345       3336380
SATWND          1532        205011      15253542
VADWND            60          1631        583726
ADPSFC          1454        154629      14446774
SFCSHP           197         26327       1955780
GPSIPW             5           607         33048
RASSDA             7           181         67366
ASCATW          1520        246165      15098146
SYNDAT             1            41          5548
------------------------------------------------
   TOTAL        7171        830916      70829746
################################################
```

**Comment by ilianagenkova** [comment]
@emilyhcliu  Link to the [updated table](https://docs.google.com/presentation/d/15eKxI6MaP4ACiL2V8-asZU1qp7VF04NyugO26VnvVNQ/edit?usp=sharing) on switching dates from old to new bufr and subtypes

**Comment by BenjaminRuston** [comment]
@emilyhcliu and @ilianagenkova this is a sub-epic?

is this still being used to organize the work, or has a new set of issues been raised?

**Comment by ilianagenkova** [comment]
@BenjaminRuston , this is the "umbrella" for all satellite winds.
It points/splits to #446 (scaterometer winds) and #445  (AMVs). 

#445 is now collecting all AMV-related issues that were worked on (by a few of us at EMC). Is that approach acceptable? 
#446 - less work is done there, but I was planning to follow the same approach.

Please advise what's better from tracking point of view. thanks!

**Comment by BenjaminRuston** [comment]
@ilianagenkova,,, I have been adding the umbrella issue to a sub-epic pipeline.  Think it the correct spot and hope to work with you on some of this soon.

**Comment by symoore90** [comment]
Closing because epic is completed
