### ISSUE TITLE
BufrConverter:  add support of prioritized list of mnemonics

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#431]
## Description

A number of incoming BUFR files have possibility of more than one representation of the same basic piece of data and passing all possibilities into ObsSpace then requiring further codes to pick which one seems burdensome.  One really strong example of this situation are a "coarse" lat/lon or more high-res lat/lon represented in BUFR mnemonics as CLAT or CLATH for latitude for example.  Another example is a conventional observation station elevation in radiosonde data has 3 possible mnemonics:  HSMSL, HBMSL, and HEIT (height above mean sea level, height of barometer above sea level, and just height respectively).  If one station in a radiosonde file uses the second one, not the first, but others fill in a different variable, it would need additional processing steps to choose which one becomes stationElevation@MetaData for example. 

## Requirements

A potential solution for this in yaml representation would look like the following:

```
    exports:
          variables:
              stationElevation:
                mnemonic:  [HBMSL, HSMSL, HEIT]
```

## Acceptance Criteria (Definition of Done)

The first one (non-missing) in the ordered list is accepted as the data value in the new variable.

**Comment by gthompsnJCSDA** [comment]
Update... Making some progress on this task using branch feature/allow_multi_mnemonics

**Comment by gthompsnJCSDA** [comment]
Update... This is now working.  Branch: feature/allow_multi_moments that also contains a merge of Ron McLaren's bufr_standard_wmo_support permits this to happen.

Next step needed will become a separate issue.  The work so far has considered only a single observation in BUFR in which one mnemonic is prioritized over another from a list, but the problem with many reports in a single file is that some countries' weather services may use one mnemonic like CLAT (coarse-resolution latitude) and another country may use CLATH and each individual observation in a batch may bounce back and forth.  The solution implemented above would force to using first one found for al subsequent obs.

**Comment by rmclaren** [comment]
Probably should not close the issue until it has been merged into the develop branch.

**Comment by gthompsnJCSDA** [comment]
> Probably should not close the issue until it has been merged into the develop branch.

Yeah, good point, thanks.

**Comment by gthompsnJCSDA** [comment]
This was actually successfully implemented as an intermediate step. However, the goal has changed to permit the more complicated case of a large bufr file with many different sources of data for which a different mnemonic is used and can change sporadically in a full collection of bufr messages. In that case, we need to grab the first one in a prioritized list, not enforce the same one throughout the full set of messages. Therefore, I shall close this issue as issue #440 captures the new concept as work-in-progress with Ron McLaren.
