### ISSUE TITLE
Aircrft data prepbufr mnemonics used in GSI

### ISSUE THREAD

**Issue by dmerkova** [JCSDA-internal/ioda-converters#447]
## Description
Need to identify data in prepbufr that are used in GSI code.
list mnemonics used for all types of aircraft data (obs types 131-135)
read_prepbufr.f90 is the reading procedure for prepbufr data
Mnemonics used for aircraft data (observation types 131-134: 
```
  data hdstr  /'SID XOB YOB DHR TYP ELV SAID T29'
  data hdstr2 /'TYP SAID T29 SID'/
  data obstr  /'POB QOB TOB ZOB UOB VOB PWO MXGS HOVI CAT PRSS TDO PMO' /
  data drift  /'XDR YDR HRDR                    '/
  
  data qcstr  /'PQM QQM TQM ZQM WQM NUL PWQ PMQ'/
  data oestr  /'POE QOE TOE NUL WOE NUL PWE     '/
! data satqcstr  /'RFFL QIFY QIFN EEQF'/
  data satqcstr  /'QIFN'/
  data prvstr /'PRVSTG'/
  data sprvstr /'SPRVSTG'/
  data levstr  /'POB'/ 
  data aircraftstr /'POAF IALR'/    ! phase of aircraft flight and vertical velocity
  data maxtmintstr  /'MXTM MITM'/
  data owavestr  /'HOWV'/
  
```
These are mnemonics used generally for all observation, but POAF (Phase of flight) and IALR (vertical velocity) **is** needit for qc (resp bias correction) 

SID contains aircraft tail number unique for each aircraft.  It is used maily for prep-processing when checking QC but to go on it will be more used forward.

@emilyhcliu, @aerorahul

**Comment by BenjaminRuston** [comment]
@dmerkova can this be closed, think the mnemonics have been identified and other issues have been introduced to carry on with the work

**Comment by huishao-r** [comment]
Closed this issue since it is not active. Please reopen it if this is active again.
