### ISSUE TITLE
NOAA EMC PrepBUFR to IODA Conversion Software Support and Enhancement for Conventional ADPUPA Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#450]
### NCEP ADPUPA Data

[NCEP PrepBUFR Table](https://github.com/JCSDA-internal/ioda-converters/blob/develop/doc/bufr_table_samples/aircraft.prepbufr.table.txt)

[NCEP ADPUPA Data Info](https://docs.google.com/presentation/u/0/d/1WBK4CCZceYzeN_C7W7a7mAZ9BdW9mPMfmzhWLVcDNyo/edit)

### List of Tasks

Create YAML files based on types
- [ ] ADPUPA
- [ ] Validate IODA output with reference data from GSI
- [ ] Create unit test file with reduced size

**Comment by symoore90** [comment]
Closing because epic is completed
