### ISSUE TITLE
NOAA EMC PrepBUFR to IODA Conversion Software Support and Enhancement for Conventional AIRCAR/AIRCFT Data

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#451]
### NCEP Aircraft Data

[NCEP Aircraft PrepBufr Table](https://github.com/JCSDA-internal/ioda-converters/blob/develop/doc/bufr_table_samples/aircraft.prepbufr.table.txt)

[NCEP Aircraft Data Info](https://docs.google.com/presentation/d/10y7vIYFl6M3sK27lrVcob63eCvvEoDWeBr2_tFyor_U/edit?usp=sharing)

prepbufr_acft_profiles contains two subsets
AIRCAR - MDCRS, ACARS
AIRCFT - AIREP, RIREP, AMDAR, TMDAR

### List of Tasks: 
- [ ] AIRCAR 
- [ ] AIRCFT

**Comment by PatNichols** [comment]
@emilyhcliu Can we close this issue?

**Comment by nicholasesposito** [comment]
Yes, this has been done. Apologies, I didn't realize this was in another one of the "issues tabs". I'll go through and close some others too.
