### ISSUE TITLE
Update bufr2ioda.x to read time variable in prepbufr files.

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#459]
The bufr2ioda converter currently does not have a way of handling this, so this is something that needs looking into. Thank you.

### Description

Prepbufr files only have one time variable within them.
The variable has the mnemonic "DHR" which is defined as "OBSERVATION TIME MINUS CYCLE TIME" .

The bufr2ioda converter currently does not have a way of handling this.

### Requirements

 If possible, please add the capability to convert this to year, month, day, hour, and minute variables. The bufr mnemonics for these are below, as and the description should be YEAR, MONTH, DAY, HOUR, MINUTES. It should be noted that the bufr files do not contain a "seconds" variable.
year = YEAR          
month = MNTH
day = DAYS
hour = HOUR
minute = MINU. 

### Dependencies
- None

**Comment by nicholasesposito** [comment]
@PraveenKumar-NOAA @emilyhcliu @rmclaren 
Correct me if I'm wrong, but do we have an updated/finished issue/PR for this? I could have sworn we did.

**Comment by PraveenKumar-NOAA** [comment]
@nicholasesposito there is an open issue for this, created by Emily.

**Comment by nicholasesposito** [comment]
This has been superseded by #1090 and can be closed.
