### ISSUE TITLE
Add mnemonic GNAPS to  satwnds_new_subset_template.yaml

### ISSUE THREAD

**Issue by ilianagenkova** [JCSDA-internal/ioda-converters#461]
### **Objective** - Adding GNAPS to satwnds_new_subset_template.yaml 
---

### **Background Info** 

Mnemonics GNAP (in old bufr satwnd files) and GNAPS (in new bufr satwnd files) determine now to interpret the multiple PCCF occurrences in a satwnd bufr file. 
For example, 
if  GNAPS=4  the PCCF will contain the Common quality index (QI) without forecast
if  GNAPS=5 the PCCF will contain QI without forecast
if GNAP=4  the PCCF contains the Expected Error
if GNAP=5  the PCCF conatins the QI (Quality Indicator) excluding the forecast. 

Therefore, we can't rely on hardwired order (as it is in GSI now) to interpret what PCCF holds. For example in read_satwnd.f90 : 
call ufbseq(lunin,amvqic,2,4,iret, 'AMVQIC') ! AMVQIC:: GNAPS PCCF
       qifn = amvqic(2,2) ! QI w/ fcst does not exist in this BUFR
       ee = amvqic(2,4) ! NOTE: GOES-R's ee is in [m/s]

satwnds_old_subset_template.yaml already includes the GNAP mnemonic, i.e. "generating_application"

Here we are adding GNAPS to satwnds_new_subset_template.yaml 

### **Working Branch:**
[feature/iodaconv_GNAPS](https://github.com/JCSDA-internal/ioda-converters/tree/feature/iodaconv_GNAPS
)

**Comment by emilyhcliu** [comment]
@ilianagenkova Thanks for working on this.  Please test on your branch and check if the output IODA contains GNAPS as expected.  If so, you can do a pull request based on your branch.

**There is one more thing related to this update and requires your attention.**
In February, you created a table ([Iliana's presentation on February 8, 2021](https://drive.google.com/file/d/1jL1aOcb7Qz5shx0_SmoniWiUkSXGh1rD/view)) that documents the switching dates from the old to the new BUFR format for various data types.  The table is a bit outdated for some of the data types.  Could you please update the information in the table.  I think the switching dates will need to include cycle information (e.g. 00Z)  as well.  Thanks!
