### ISSUE TITLE
bufr2ioda.x can not read CCITT IA5 formatted variables correctly

### ISSUE THREAD

**Issue by YanHao-NOAA** [JCSDA-internal/ioda-converters#468]
## Description
bufr2ioda.x can not read CCITT IA5 formatted variables correctly at this point, char strings is read as float. (e.g., RPID, SHPC8 etc.)

**Comment by PraveenKumar-NOAA** [comment]
I think it has been fixed by Ron recently. I am going to try with one of the CCITT IA5 Mnemonics in my prepbufr yaml today.

**Comment by rmclaren** [comment]
You need the feature/query branch's for NCEPLIB-bufr and Ioda Converter. Not really "fixed" in the develop branch yet.

**Comment by PraveenKumar-NOAA** [comment]
Got it, both repos have a branch with the same name.

Thank you for the clarification Ron.

Praveen Kumar
***@***.***/NCEP/EMC
5830 University Research Ct., Rm. 2069
College Park, MD 20740
Phone: (301) 683-3715
Mobile: (201) 657-3096

**Comment by PraveenKumar-NOAA** [comment]
I can't clone the feature/query brach of the ioda-bundle. Below is the error message I received while cloning this branch: 
fatal: Remote branch feature/query not found in upstream origin

**Comment by srherbener** [comment]
> I can't clone the feature/query brach of the ioda-bundle. Below is the error message I received while cloning this branch:
> fatal: Remote branch feature/query not found in upstream origin

The branch `feature/query` does not exist in the ioda-bundle repo, but does exist in the ioda-converters repo. Did you mean to checkout `feature/query` in your clone of ioda-converters instead?

**Comment by PraveenKumar-NOAA** [comment]
Yes, in my clone of the ioda-bundle. Can I use: 
 git clone -b feature/query https://github.com/JCSDA-internal/ioda-converters
?

**Comment by PraveenKumar-NOAA** [comment]
It worked. Should I use the same  installation command as used for the ioda-bundle?

**Comment by PraveenKumar-NOAA** [comment]
There is no bufr2ioda.x executable in the build directory.

**Comment by srherbener** [comment]
@PraveenKumar-NOAA I'm not sure I'm quite following what you are doing, but I hope the following will help.

You should be able to do the commands below to get the ioda-converters to build (ie, get the bufr2ioda.x executable created).

```
git clone https://github.com/jcsda-internal/ioda-bundle.git
cd ioda-bundle

# edit the CMakeLists.txt file
# on the line: 
#    `ecbuild_bundle( PROJECT iodaconv GIT "https://github.com/JCSDA-internal/ioda-converters.git" BRANCH develop UPDATE )`
#    change `develop` to `feature/query`

mkdir build
cd build
ecbuild -DBUILD_IODA_CONVERTERS=ON ..
make -j4

# you should have the bufr2ioda.x executable at this point

ctest
```

**Comment by rmclaren** [comment]
Also don't forget that there is an external dependency to NCEPLIB-bufr feature/query. So what I do is checkout build and install NCEPLIB-bufr feature/query somewhere. On ecbuild I then add the extra argument. I then call ecbuild as follows:

ecbuild -DCMAKE_PREFIX_PATH=<place where I install my libraries like NCEPLIB-bufr> -DCMAKE_BUILD_TYPE=Debug -DBUNDLE_SKIP_ECKIT=OFF -DBUILD_IODA_CONVERTERS=ON ..

**Comment by BenjaminRuston** [comment]
closing thanks!
