### ISSUE TITLE
Improvements needed to handle satellite radiance bufr data

### ISSUE THREAD

**Issue by cyberbass** [JCSDA-internal/ioda-converters#474]
## Description
This is a summary of issues found when working on: 
https://github.com/JCSDA-internal/ufo/issues/899

1. When trying to convert AVHRR, CrIS, IASI, SEVERI data, data fields such as brightness temperature, latitude/longitude, solar zenith angle will be fully or partially filled with a fill value of 9.9999e10. 
Test data path: /data/users/eliu/bufr_samples/
Test yaml example:  /data/users/nchen/CodeSprintDec20/src/ioda-bundle/iodaconv/test/testinput/bufr_cris_new_format.yaml
2. The channel numbers needs to be specified in the yaml file and there is no way to infer the number of channels during run time. It also will not report any error when the specified number of channels exceeds the total number of channels for that specific sensor. The converter will automatically fill the data field with a fill value of 9.9999e10 without notifying the user.  
3. When a large number of channels (1500 - 2000) were specified for sensors like ATMS, CrIS or IASI, the code will require a large number of memory (over ~8GB) and may be terminated by s4. 

## Requirements

None

## Dependencies

Does this block progress on other issues?
 - blocks https://github.com/JCSDA-internal/ufo/issues/899

**Comment by rmclaren** [comment]
Comments:
1: The value 10e10 is the "missing" value. So you will see that whenever there is missing data. Rahul added an issue #406 which I believe would cover this.
2: This is actually a general problem with NCEPLIB-bufr. I'm working to replace this API so the user will no longer need to be aware of details like how many channels there are, etc...
3: Seems like you must be trying to read delayed-sequences this way. This is currently not supported (you can sometimes get the delayed sequences by defining an insane number of channels to try to capture all the data, but this is really a very baaaadddd idea! Please wait for proper support for delayed sequences. #384
