### ISSUE TITLE
prepBUFR ADPUPA Mnemonics 

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#477]
## Description
To provide ADPUPA data type support for prepBUFR to IODA conversion: Mnemonics, BUFR Tables, Variable Names, and corresponding Units.

| ------------------------   USER DEFINITIONS FOR TABLE-A TABLE-B TABLE D   ---------------------|
|------------------------------------------------------------------------------------------------------|

| MNEMONIC | NUMBER | DESCRIPTION                                              |
|----------|--------|----------------------------------------------------------|
| ADPUPA   | A48102 | UPPER-AIR (RAOB, PIBAL, RECCO, DROPS) REPORTS            |
||||
| HEADR    | 348001 | REPORT HEADER SEQUENCE                                   |
| SIRC     | 002013 | RAWINSONDE SOLAR & INFRARED RADIATION CORR. INDICATOR    |
| PRSLEVEL | 348002 | PRESSURE LEVEL SEQUENCE (EXCEPT GOESND, AIRCFT/AIRCAR)   |
| SST_INFO | 348158 | SEA TEMPERATURE INFORMATION                              |
| PREWXSEQ | 348013 | PRESENT WEATHER SEQUENCE                                 |
| CLOUDSEQ | 348014 | OBSERVED CLOUD SEQUENCE # 1                              |
| VSSO     | 008002 | VERT. SIGNIFICANCE (SFC OBSERVATION)                     |
| CLAM     | 020011 | CLOUD AMOUNT                                             |
| CLTP     | 020012 | CLOUD TYPE                                               |
| HOCB     | 020013 | HEIGHT OF BASE OF CLOUD                                  |
| HOCT_SEQ | 348015 | HEIGHT OF TOP OF CLOUD SEQUENCE                          |
| HOCT     | 020014 | HEIGHT OF TOP OF CLOUD                                   |
| CLOU2SEQ | 348029 | OBSERVED CLOUD SEQUENCE # 2                              |
| TOCC     | 020010 | CLOUD COVER (TOTAL)                                      |
| HBLCS    | 020201 | HEIGHT ABOVE SURFACE OF BASE OF LOWEST CLOUD SEEN        |
| SWINDSEQ | 348031 | SURFACE WIND SEQUENCE                                    |
| WDIR1    | 011200 | SURFACE WIND DIRECTION                                   |
| WSPD1    | 011201 | SURFACE WIND SPEED                                       |
| AFIC_SEQ | 348038 | AIRCRAFT ICING SEQUENCE                                  |
| AFIC     | 020041 | AIRFRAME ICING                                           |
| HBOI     | 020194 | HEIGHT OF BASE OF ICING                                  |
| HTOI     | 020195 | HEIGHT OF TOP OF ICING                                   |
| TURB3SEQ | 348039 | TURBULENCE SEQUENCE # 3                                  |
| DGOT     | 011031 | DEGREE OF TURBULENCE                                     |
| HBOT     | 011032 | HEIGHT OF BASE OF TURBULENCE                             |
| HTOT     | 011033 | HEIGHT OF TOP OF TURBULENCE                              |
| SID      | 001194 | STATION IDENTIFICATION                                   |
| XOB      | 006240 | LONGITUDE                                                |
| YOB      | 005002 | LATITUDE                                                 |
| DHR      | 004215 | OBSERVATION TIME MINUS CYCLE TIME                        |
| ELV      | 010199 | STATION ELEVATION                                        |
| TYP      | 055007 | PREPBUFR REPORT TYPE                                     |
| T29      | 055008 | DATA DUMP REPORT TYPE                                    |
| TSB      | 055009 | REPORT SUBTYPE (HAS VARIOUS MEANINGS DEPENDING ON TYPE)  |
| ITP      | 002195 | INSTRUMENT TYPE                                          |
| SQN      | 050001 | REPORT SEQUENCE NUMBER                                   |
| PROCN    | 050003 | PROCESS NUMBER FOR THIS MPI RUN (OBTAINED FROM SCRIPT)   |
| RPT      | 004214 | REPORTED OBSERVATION TIME                                |
| TCOR     | 004216 | INDICATOR WHETHER OBS. TIME IN "DHR" WAS CORRECTED       |
| RSRD_SEQ | 348081 | RESTRICTIONS ON REDISTRIBUTION SEQUENCE                  |
| RSRD     | 035200 | RESTRICTIONS ON REDISTRIBUTION                           |
| EXPRSRD  | 035201 | EXPIRATION OF RESTRICTIONS ON REDISTRIBUTION             |
| CAT      | 008193 | PREPBUFR DATA LEVEL CATEGORY                             |
| P___INFO | 348141 | PRESSURE INFORMATION                                     |
| Q___INFO | 348142 | SPECIFIC HUMIDITY INFORMATION                            |
| T___INFO | 348143 | TEMPERATURE INFORMATION                                  |
| Z___INFO | 348144 | HEIGHT INFORMATION                                       |
| W___INFO | 348145 | WIND INFORMATION                                         |
| P__EVENT | 348171 | PRESSURE EVENT SEQUENCE                                  |
| POB      | 007245 | PRESSURE OBSERVATION                                     |
| PQM      | 007246 | PRESSURE (QUALITY) MARKER                                |
| PPC      | 007247 | PRESSURE EVENT PROGRAM CODE                              |
| PRC      | 007248 | PRESSURE EVENT REASON CODE                               |
| Q__EVENT | 348172 | SPECIFIC HUMIDITY EVENT SEQUENCE                         |
| QOB      | 013245 | SPECIFIC HUMIDITY OBSERVATION                            |
| QQM      | 013246 | SPECIFIC HUMIDITY (QUALITY) MARKER                       |
| QPC      | 013247 | SPECIFIC HUMIDITY EVENT PROGRAM CODE                     |
| QRC      | 013248 | SPECIFIC HUMIDITY EVENT REASON CODE                      |
| TDO      | 012244 | DEWPOINT TEMPERATURE OBSERVATION (NOT ASSIMILATED)       |
| T__EVENT | 348173 | TEMPERATURE EVENT SEQUENCE                               |
| TOB      | 012245 | TEMPERATURE OBSERVATION                                  |
| TQM      | 012246 | TEMPERATURE (QUALITY) MARKER                             |
| TPC      | 012247 | TEMPERATURE EVENT PROGRAM CODE                           |
| TRC      | 012248 | TEMPERATURE EVENT REASON CODE                            |
| TVO      | 012243 | NON-Q. CONTROLLED VIRTUAL TEMP OBS (NOT ASSIMILATED)     |
| Z__EVENT | 348174 | HEIGHT EVENT SEQUENCE                                    |
| ZOB      | 010007 | HEIGHT OBSERVATION                                       |
| ZQM      | 010246 | HEIGHT (QUALITY) MARKER                                  |
| ZPC      | 010247 | HEIGHT EVENT PROGRAM CODE                                |
| ZRC      | 010248 | HEIGHT EVENT REASON CODE                                 |
| W__EVENT | 348175 | WIND EVENT SEQUENCE                                      |
| UOB      | 011003 | U-COMPONENT WIND OBSERVATION                             |
| VOB      | 011004 | V-COMPONENT WIND OBSERVATION                             |
| WQM      | 011240 | U-, V-COMPONENT WIND (UOB/VOB) (QUALITY) MARKER          |
| WPC      | 011241 | U-, V-COMPONENT WIND (UOB/VOB) EVENT PROGRAM CODE        |
| WRC      | 011242 | U-, V-COMPONENT WIND (UOB/VOB) EVENT REASON CODE         |
| P__BACKG | 348191 | PRESSURE BACKGROUND SEQUENCE                             |
| POE      | 007250 | PRESSURE OBSERVATION ERROR                               |
| PFC      | 007249 | FORECAST (BACKGROUND) PRESSURE VALUE                     |
| Q__BACKG | 348192 | SPECIFIC HUMIDITY BACKGROUND SEQUENCE                    |
| QOE      | 013250 | RELATIVE HUMIDITY OBSERVATION ERROR                      |
| QFC      | 013249 | FORECAST (BACKGROUND) SPECIFIC HUMIDITY VALUE            |
| T__BACKG | 348193 | TEMPERATURE BACKGROUND SEQUENCE                          |
| TOE      | 012250 | TEMPERATURE OBSERVATION ERROR                            |
| TFC      | 012249 | FORECAST (BACKGROUND) TEMPERATURE VALUE                  |
| Z__BACKG | 348194 | HEIGHT BACKGROUND SEQUENCE                               |
| ZFC      | 010249 | FORECAST (BACKGROUND) HEIGHT VALUE                       |
| W__BACKG | 348195 | WIND BACKGROUND SEQUENCE                                 |
| WOE      | 011245 | U-, V-COMPONENT WIND (UOB/VOB) OBSERVATION ERROR         |
| UFC      | 011243 | FORECAST (BACKGROUND) U-COMPONENT WIND VALUE             |
| VFC      | 011244 | FORECAST (BACKGROUND) V-COMPONENT WIND VALUE             |
| P__POSTP | 348211 | PRESSURE POSTPROCESSING SEQUENCE                         |
| PAN      | 007251 | ANALYZED PRESSURE VALUE                                  |
| POETU    | 007254 | ANALYSIS-TUNED PRESSURE OBSERVATION ERROR                |
| PVWTG    | 033204 | ANAL VARIATIONAL QC WEIGHT ON PRESS. OBS BASED ON GUESS  |
| PVWTA    | 033205 | ANAL VARIATIONAL QC WEIGHT ON PRESS. OBS BASED ON ANAL   |
| Q__POSTP | 348212 | SPECIFIC HUMIDITY POSTPROCESSING SEQUENCE                |
| QAN      | 013251 | ANALYZED SPECIFIC HUMIDITY VALUE                         |
| QOETU    | 013254 | ANALYSIS-TUNED RELATIVE HUMIDITY OBSERVATION ERROR       |
| QVWTG    | 033210 | ANAL VARIATIONAL QC WEIGHT ON MOIST. OBS BASED ON GUESS  |
| QVWTA    | 033211 | ANAL VARIATIONAL QC WEIGHT ON MOIST. OBS BASED ON ANAL   |
| ESBAK    | 013242 | FORECAST(BACKGROUND) SATURATION SPECIFIC HUMIDITY VALUE  |
| T__POSTP | 348213 | TEMPERATURE POSTPROCESSING SEQUENCE                      |
| TAN      | 012251 | ANALYZED TEMPERATURE VALUE                               |
| TOETU    | 012254 | ANALYSIS-TUNED TEMPERATURE OBSERVATION ERROR             |
| TVWTG    | 033206 | ANAL VARIATIONAL QC WEIGHT ON TEMP. OBS BASED ON GUESS   |
| TVWTA    | 033209 | ANAL VARIATIONAL QC WEIGHT ON TEMP. OBS BASED ON ANAL    |
| Z__POSTP | 348214 | HEIGHT POSTPROCESSING SEQUENCE                           |
| ZAN      | 010251 | ANALYZED HEIGHT VALUE                                    |
| W__POSTP | 348215 | WIND POSTPROCESSING SEQUENCE                             |
| UAN      | 011246 | ANALYZED U-COMPONENT WIND VALUE                          |
| VAN      | 011247 | ANALYZED V-COMPONENT WIND VALUE                          |
| WOETU    | 011253 | ANALYSIS-TUNED WIND OBSERVATION ERROR                    |
| WVWTG    | 033212 | ANAL VARIATIONAL QC WEIGHT ON WIND OBS BASED ON GUESS    |
| WVWTA    | 033213 | ANAL VARIATIONAL QC WEIGHT ON WIND OBS BASED ON ANAL     |
| RF10M    | 011225 | 10 METER WIND REDUCTION FACTOR                           |
| PCLIMATO | 348231 | PRESSURE CLIMATOLOGY SEQUENCE                            |
| PCL      | 007252 | CLIMATOLOGICAL PRESSURE VALUE                            |
| PCS      | 007253 | STANDARD DEVIATION OF CLIMATOLOGICAL PRESSURE VALUE      |
| QCLIMATO | 348232 | SPECIFIC HUMIDITY CLIMATOLOGY SEQUENCE                   |
| QCL      | 013252 | CLIMATOLOGICAL SPECIFIC HUMIDITY VALUE                   |
| QCS      | 013253 | STANDARD DEV OF CLIMATOLOGICAL SPECIFIC HUMIDITY VALUE   |
| TCLIMATO | 348233 | TEMPERATURE CLIMATOLOGY SEQUENCE                         |
| TCL      | 012252 | CLIMATOLOGICAL TEMPERATURE VALUE                         |
| TCS      | 012253 | STANDARD DEVIATION OF CLIMATOLOGICAL TEMPERATURE VALUE   |
| ZCLIMATO | 348234 | HEIGHT CLIMATOLOGY SEQUENCE                              |
| ZCL      | 010252 | CLIMATOLOGICAL HEIGHT VALUE                              |
| ZCS      | 010253 | STANDARD DEVIATION OF CLIMATOLOGICAL HEIGHT VALUE        |
| WCLIMATO | 348235 | WIND CLIMATOLOGY SEQUENCE                                |
| UCL      | 011248 | CLIMATOLOGICAL U-COMPONENT WIND VALUE                    |
| UCS      | 011250 | STANDARD DEVIATION OF CLIMATOLOGICAL U-COMP WIND VALUE   |
| VCL      | 011249 | CLIMATOLOGICAL V-COMPONENT WIND VALUE                    |
| VCS      | 011251 | STANDARD DEVIATION OF CLIMATOLOGICAL V-COMP WIND VALUE   |
| PFC__MSQ | 348241 | MODEL PRESSURE FORECAST SEQUENCE                         |
| PFCMOD   | 007255 | MODEL PRESSURE FORECAST VALUE (GLOBAL MODEL SEE PFC)     |
| QFC__MSQ | 348242 | MODEL SPECIFIC HUMIDITY FORECAST SEQUENCE                |
| QFCMOD   | 013255 | MODEL S. HUMIDITY FORECAST VALUE (GLOBAL MODEL SEE QFC)  |
| TFC__MSQ | 348243 | MODEL TEMPERATURE FORECAST SEQUENCE                      |
| TFCMOD   | 012255 | MODEL TEMPERATURE FORECAST VALUE (GLOBAL MODEL SEE TFC)  |
| ZFC__MSQ | 348244 | MODEL HEIGHT FORECAST SEQUENCE                           |
| ZFCMOD   | 010255 | MODEL HEIGHT FORECAST VALUE (GLOBAL MODEL SEE ZFC)       |
| WFC__MSQ | 348245 | MODEL WIND FORECAST SEQUENCE                             |
| DRFTINFO | 348155 | PROFILE LEVEL TIME/LOCATION INFORMATION                  |
| XDR      | 006241 | PROFILE LEVEL LON (FOR RAOB/PIBAL BASED ON BALLOON DFT)  |
| YDR      | 005241 | PROFILE LEVEL LAT (FOR RAOB/PIBAL BASED ON BALLOON DFT)  |
| HRDR     | 004218 | PROFILE LVL TIME-CYCLE (FOR RAOB/PIBAL, BASED ON B DFT)  |
| W1_EVENT | 348185 | WIND {DIRECTION/SPEED(kts)} EVENT SEQUENCE               |
| DDO      | 011001 | WIND DIRECTION OBSERVATION (NOT ASSIMILATED)             |
| FFO      | 011252 | WIND SPEED OBSERVATION (kts) (NOT ASSIMILATED)           |
| DFQ      | 011218 | WIND DIRECTION(DDO)/SPEED(FFO or SOB) (QUALITY) MARKER   |
| DFP      | 011219 | WIND DIRECTION(DDO)/SPEED(FFO or SOB) EVENT PGM CODE     |
| DFR      | 011220 | WIND DIRECTION(DDO)/SPEED(FFO or SOB) EVENT REASON CODE  |
| SSTEVENT | 348184 | SEA TEMPERATURE EVENT SEQUENCE                           |
| SST1     | 022043 | SEA TEMPERATURE                                          |
| SSTQM    | 022246 | SEA TEMPERATURE (QUALITY) MARKER                         |
| SSTPC    | 022247 | SEA TEMPERATURE EVENT PROGRAM CODE                       |
| SSTRC    | 022248 | SEA TEMPERATURE EVENT REASON CODE                        |
| MSST     | 002038 | METHOD OF SEA SURFACE TEMPERATURE MEASUREMENT            |
| SSTBACKG | 348203 | SEA TEMPERATURE BACKGROUND SEQUENCE                      |
| SSTOE    | 022250 | SEA TEMPERATURE OBSERVATION ERROR                        |
| SSTFC    | 022249 | FORECAST (BACKGROUND) SEA TEMPERATURE VALUE              |
| SSTPOSTP | 348223 | SEA TEMPERATURE POSTPROCESSING SEQUENCE                  |
| SSTAN    | 022251 | ANALYZED SEA TEMPERATURE VALUE                           |
| DBSS_SEQ | 348018 | DEPTH BELOW SEA SURFACE SEQUENCE                         |
| DBSS     | 007062 | DEPTH BELOW SEA SURFACE                                  |
| PRWE     | 020003 | PRESENT WEATHER                                          |

| MNEMONIC | SEQUENCE                                                          |
|----------|-------------------------------------------------------------------|
| ADPUPA   | HEADR  SIRC  {PRSLEVEL}  \<SST_INFO\>  \<PREWXSEQ\>  {CLOUDSEQ}       |
| ADPUPA   | \<CLOU2SEQ\>  \<SWINDSEQ\>  \<AFIC_SEQ\>  \<TURB3SEQ\>                    |

| MNEMONIC | SEQUENCE                                                          |
|----------|-------------------------------------------------------------------|
| HEADR    | SID  207003  XOB  YOB  207000  DHR  ELV  TYP  T29  TSB  ITP  SQN  |
| HEADR    | PROCN  RPT  TCOR  \<RSRD_SEQ\>                                      |
| PRSLEVEL | CAT  \<P___INFO\>  \<Q___INFO\>  \<T___INFO\>  \<Z___INFO\>  \<W___INFO\>   |
| PRSLEVEL | \<DRFTINFO\>  [W1_EVENT]                                            |
| SST_INFO | [SSTEVENT]  MSST  \<SSTBACKG\>  \<SSTPOSTP\>  \<DBSS_SEQ\>              |
| PREWXSEQ | PRWE                                                              |
| CLOUDSEQ | VSSO  CLAM  CLTP  HOCB  \<HOCT_SEQ\>                                |
| CLOU2SEQ | TOCC  HBLCS                                                       |
| SWINDSEQ | WDIR1  WSPD1                                                      |
| AFIC_SEQ | AFIC  HBOI  HTOI                                                  |
| TURB3SEQ | DGOT  HBOT  HTOT                                                  |
| RSRD_SEQ | RSRD  EXPRSRD                                                     |
| P___INFO | [P__EVENT]  <P__BACKG>  <P__POSTP>                                |
| Q___INFO | [Q__EVENT]  TDO  <Q__BACKG>  <Q__POSTP>                           |
| T___INFO | [T__EVENT]  TVO  <T__BACKG>  <T__POSTP>                           |
| Z___INFO | [Z__EVENT]  <Z__BACKG>  <Z__POSTP>                                |
| W___INFO | [W__EVENT]  <W__BACKG>  <W__POSTP>                                |
| P__EVENT | POB  PQM  PPC  PRC                                                |
| Q__EVENT | QOB  QQM  QPC  QRC                                                |
| T__EVENT | TOB  TQM  TPC  TRC                                                |
| Z__EVENT | ZOB  ZQM  ZPC  ZRC                                                |
| W__EVENT | UOB  VOB  WQM  WPC  WRC                                           |
| P__BACKG | POE  PFC  <PFC__MSQ>                                              |
| Q__BACKG | QOE  QFC  <QFC__MSQ>                                              |
| T__BACKG | TOE  TFC  <TFC__MSQ>                                              |
| Z__BACKG | ZFC  <ZFC__MSQ>                                                   |
| W__BACKG | WOE  UFC  VFC  <WFC__MSQ>                                         |
| P__POSTP | PAN  <PCLIMATO>  POETU  PVWTG  PVWTA                              |
| Q__POSTP | QAN  <QCLIMATO>  QOETU  QVWTG  QVWTA  ESBAK                       |
| T__POSTP | TAN  <TCLIMATO>  TOETU  TVWTG  TVWTA                              |
| Z__POSTP | ZAN  <ZCLIMATO>                                                   |
| W__POSTP | UAN  VAN  <WCLIMATO>  WOETU  WVWTG  WVWTA  RF10M                  |
| PFC__MSQ | PFCMOD                                                            |
| QFC__MSQ | QFCMOD                                                            |
| TFC__MSQ | TFCMOD                                                            |
| ZFC__MSQ | ZFCMOD                                                            |
| PCLIMATO | PCL  PCS                                                          |
| QCLIMATO | QCL  QCS                                                          |
| TCLIMATO | TCL  TCS                                                          |
| ZCLIMATO | ZCL  ZCS                                                          |
| WCLIMATO | UCL  UCS  VCL  VCS                                                |
| DRFTINFO | 207003  XDR  YDR  207000  HRDR                                    |
| W1_EVENT | DDO  FFO  DFQ  DFP  DFR                                           |
| SSTEVENT | SST1  SSTQM  SSTPC  SSTRC                                         |
| SSTBACKG | SSTOE  SSTFC                                                      |
| SSTPOSTP | SSTAN                                                             |
| DBSS_SEQ | DBSS                                                              |
| HOCT_SEQ | HOCT                                                              |

| MNEMONIC | SCAL | REFERENCE   | BIT | UNITS                    |-------------|
|----------|------|-------------|-----|--------------------------|-------------|
| SIRC     |    0 |           0 |   4 | CODE TABLE               |-------------|
| PRWE     |    0 |           0 |   9 | CODE TABLE               |-------------|
| VSSO     |    0 |           0 |   6 | CODE TABLE               |-------------|
| CLAM     |    0 |           0 |   4 | CODE TABLE               |-------------|
| CLTP     |    0 |           0 |   6 | CODE TABLE               |-------------|
| HOCB     |   -1 |         -40 |  11 | METER                    |-------------|
| HOCT     |   -1 |         -40 |  11 | METER                    |-------------|
| TOCC     |    0 |           0 |   7 | PERCENT                  |-------------|
| HBLCS    |    0 |           0 |   4 | CODE TABLE               |-------------|
| WDIR1    |    0 |           0 |   9 | DEGREES TRUE             |-------------|
| WSPD1    |    1 |           0 |  12 | M/S                      |-------------|
| AFIC     |    0 |           0 |   4 | CODE TABLE               |-------------|
| HBOI     |   -1 |         -40 |  16 | METER                    |-------------|
| HTOI     |   -1 |         -40 |  16 | METER                    |-------------|
| DGOT     |    0 |           0 |   4 | CODE TABLE               |-------------|
| HBOT     |   -1 |         -40 |  16 | METERS                   |-------------|
| HTOT     |   -1 |         -40 |  16 | METERS                   |-------------|
| SID      |    0 |           0 |  64 | CCITT IA5                |-------------|
| XOB      |    2 |      -18000 |  16 | DEG E                    |-------------|
| YOB      |    2 |       -9000 |  15 | DEG N                    |-------------|
| DHR      |    5 |    -2400000 |  23 | HOURS                    |-------------|
| ELV      |    0 |       -1000 |  17 | METER                    |-------------|
| TYP      |    0 |           0 |  10 | CODE TABLE               |-------------|
| T29      |    0 |           0 |  10 | CODE TABLE               |-------------|
| TSB      |    0 |           0 |  14 | CODE TABLE               |-------------|
| ITP      |    0 |           0 |   8 | CODE TABLE               |-------------|
| SQN      |    0 |           0 |  19 | NUMERIC                  |-------------|
| PROCN    |    0 |           0 |   7 | NUMERIC                  |-------------|
| RPT      |    5 |           0 |  22 | HOURS                    |-------------|
| TCOR     |    0 |           0 |   3 | CODE TABLE               |-------------|
| RSRD     |    0 |           0 |   9 | FLAG TABLE               |-------------|
| EXPRSRD  |    0 |           0 |   8 | HOURS                    |-------------|
| CAT      |    0 |           0 |   6 | CODE TABLE               |-------------|
| POB      |    1 |           0 |  14 | MB                       |-------------|
| PQM      |    0 |           0 |   5 | CODE TABLE               |-------------|
| PPC      |    0 |           0 |   5 | CODE TABLE               |-------------|
| PRC      |    0 |           0 |  10 | CODE TABLE               |-------------|
| QOB      |    0 |           0 |  16 | MG/KG                    |-------------|
| QQM      |    0 |           0 |   5 | CODE TABLE               |-------------|
| QPC      |    0 |           0 |   5 | CODE TABLE               |-------------|
| QRC      |    0 |           0 |  10 | CODE TABLE               |-------------|
| TOB      |    1 |       -2732 |  14 | DEG C                    |-------------|
| TQM      |    0 |           0 |   5 | CODE TABLE               |-------------|
| TPC      |    0 |           0 |   5 | CODE TABLE               |-------------|
| TRC      |    0 |           0 |  10 | CODE TABLE               |-------------|
| ZOB      |    0 |       -1000 |  17 | METER                    |-------------|
| ZQM      |    0 |           0 |   5 | CODE TABLE               |-------------|
| ZPC      |    0 |           0 |   5 | CODE TABLE               |-------------|
| ZRC      |    0 |           0 |  10 | CODE TABLE               |-------------|
| UOB      |    1 |       -4096 |  13 | M/S                      |-------------|
| VOB      |    1 |       -4096 |  13 | M/S                      |-------------|
| WQM      |    0 |           0 |   5 | CODE TABLE               |-------------|
| WPC      |    0 |           0 |   5 | CODE TABLE               |-------------|
| WRC      |    0 |           0 |  10 | CODE TABLE               |-------------|
| POE      |    2 |           0 |  14 | MB                       |-------------|
| PFC      |    1 |           0 |  14 | MB                       |-------------|
| QFC      |    0 |           0 |  16 | MG/KG                    |-------------|
| QOE      |    1 |           0 |  10 | PERCENT DIVIDED BY 10    |-------------|
| TFC      |    1 |       -2732 |  14 | DEG C                    |-------------|
| TOE      |    1 |           0 |  10 | DEG C                    |-------------|
| ZFC      |    0 |       -1000 |  17 | METER                    |-------------|
| WOE      |    1 |           0 |  10 | M/S                      |-------------|
| UFC      |    1 |       -4096 |  13 | M/S                      |-------------|
| VFC      |    1 |       -4096 |  13 | M/S                      |-------------|
| PAN      |    1 |           0 |  14 | MB                       |-------------|
| POETU    |    2 |           0 |  14 | MB                       |-------------|
| PVWTG    |    0 |           0 |   7 | PERCENT                  |-------------|
| PVWTA    |    0 |           0 |   7 | PERCENT                  |-------------|
| QAN      |    0 |           0 |  16 | MG/KG                    |-------------|
| QOETU    |    1 |           0 |  10 | PERCENT DIVIDED BY 10    |-------------|
| QVWTG    |    0 |           0 |   7 | PERCENT                  |-------------|
| QVWTA    |    0 |           0 |   7 | PERCENT                  |-------------|
| ESBAK    |    0 |           0 |  16 | MG/KG                    |-------------|
| TAN      |    1 |       -2732 |  14 | DEG C                    |-------------|
| TOETU    |    1 |           0 |  10 | DEG C                    |-------------|
| TVWTG    |    0 |           0 |   7 | PERCENT                  |-------------|
| TVWTA    |    0 |           0 |   7 | PERCENT                  |-------------|
| ZAN      |    0 |       -1000 |  17 | METER                    |-------------|
| UAN      |    1 |       -4096 |  13 | M/S                      |-------------|
| VAN      |    1 |       -4096 |  13 | M/S                      |-------------|
| WOETU    |    1 |           0 |  10 | M/S                      |-------------|
| WVWTG    |    0 |           0 |   7 | PERCENT                  |-------------|
| WVWTA    |    0 |           0 |   7 | PERCENT                  |-------------|
| RF10M    |    4 |           0 |  16 | NUMERIC                  |-------------|
| PCL      |    1 |           0 |  14 | MB                       |-------------|
| PCS      |    1 |           0 |  14 | MB                       |-------------|
| QCL      |    0 |           0 |  16 | MG/KG                    |-------------|
| QCS      |    0 |           0 |  16 | MG/KG                    |-------------|
| TCL      |    1 |       -2732 |  14 | DEG C                    |-------------|
| TCS      |    1 |           0 |  10 | DEG C                    |-------------|
| ZCL      |    0 |       -1000 |  17 | METER                    |-------------|
| ZCS      |    0 |           0 |  10 | METER                    |-------------|
| UCL      |    1 |       -4096 |  13 | M/S                      |-------------|
| VCL      |    1 |       -4096 |  13 | M/S                      |-------------|
| UCS      |    1 |           0 |  10 | M/S                      |-------------|
| VCS      |    1 |           0 |  10 | M/S                      |-------------|
| PFCMOD   |    1 |           0 |  14 | MB                       |-------------|
| QFCMOD   |    0 |           0 |  16 | MG/KG                    |-------------|
| TFCMOD   |    1 |       -2732 |  14 | DEG C                    |-------------|
| ZFCMOD   |    0 |       -1000 |  17 | METER                    |-------------|
| XDR      |    2 |      -18000 |  16 | DEG E                    |-------------|
| YDR      |    2 |       -9000 |  15 | DEG N                    |-------------|
| HRDR     |    5 |    -2400000 |  23 | HOURS                    |-------------|
| DDO      |    0 |           0 |   9 | DEGREES TRUE             |-------------|
| FFO      |    0 |           0 |   9 | KNOTS                    |-------------|
| DFQ      |    0 |           0 |   5 | CODE TABLE               |-------------|
| DFP      |    0 |           0 |   5 | CODE TABLE               |-------------|
| DFR      |    0 |           0 |  10 | CODE TABLE               |-------------|
| SST1     |    2 |           0 |  15 | KELVIN                   |-------------|
| SSTQM    |    0 |           0 |   5 | CODE TABLE               |-------------|
| SSTPC    |    0 |           0 |   5 | CODE TABLE               |-------------|
| SSTRC    |    0 |           0 |  10 | CODE TABLE               |-------------|
| MSST     |    0 |           0 |   3 | CODE TABLE               |-------------|
| SSTOE    |    1 |           0 |  10 | KELVIN                   |-------------|
| SSTFC    |    2 |           0 |  15 | KELVIN                   |-------------|
| SSTAN    |    2 |           0 |  15 | KELVIN                   |-------------|
| DBSS     |    1 |           0 |  17 | METER                    |-------------|
| PRWE     |    0 |           0 |   9 | CODE TABLE               |-------------|
| TVO      |    1 |       -2732 |  14 | DEG C                    |-------------|
| TDO      |    1 |       -2732 |  14 | DEG C                    |-------------|

**Comment by emilyhcliu** [comment]
@PraveenKumar-NOAA The table above is great.  The next step is to extract those mnemonics be written into prepbufr file.

**Comment by PraveenKumar-NOAA** [comment]
I have taken care of this using a text file and a spread-sheet document into a separate issue.
