### ISSUE TITLE
BUFR ADPUPA Mnemonics

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#478]
## Description
To provide ADPUPA data type support for BUFR to IODA conversion: Mnemonics, Subsets, BUFR Tables, Variable Names, and corresponding Units. 

| ------------   USER DEFINITIONS FOR TABLE-A TABLE-B TABLE D   ------------- |
|-----------------------------------------------------------------------------------|

| MNEMONIC | NUMBER | DESCRIPTION                                                                         |
|-------------|----------|----------------------------------------------------------|
| NC002001   | A63218  | MSG TYPE 002-001  RAWINSONDE - FIXED LAND             |
| NC002002  | A63219  | MSG TYPE 002-002  RAWINSONDE - MOBIL LAND            |
| NC002003  | A63220  | MSG TYPE 002-003  RAWINSONDE - SHIP                         |
| NC002004  | A63221  | MSG TYPE 002-004  DROPWINSONDE                                |
| NC002005  | A63222 | MSG TYPE 002-005  PIBAL                                                    |
| NC004005 | A63235 | MSG TYPE 004-005  RECCO                                                  |

| MNEMONIC | SEQUENCE                                                                                                |
|-------------|---------------------------------------------------------------------|
| NC002001  | YYMMDD  HOUR  {RCPTIM}  {BID}  UASID  {UARID}  {UARLV}  \<UASDG\>  |
|                     | {UARDCS}  {RAWRPT}  {UACLD}  \<UAADF\>  WMOB  WMOS  WMOR                      |
| NC002002 | YYMMDD  HOUR  {RCPTIM}  {BID}  UASID  {UARID}  {UARLV}  \<UASDG\>  |
|                     | {UARDCS}  {RAWRPT}  {UACLD}  RSML  QCEVR                                                         |
| NC002003 | YYMMDD  HOUR  {RCPTIM}  {BID}  UASID  {UARID}  {UARLV}  \<UASDG\>               |
|                     | {UARDCS}  {RAWRPT}  {UACLD}  \<UAADF\>  RSML  WMOR                                      |
| NC002004 | YYMMDD  HOUR  {RCPTIM}  {BID}  UASID  {UARID}  {UARLV}  \<UASDG\>               |
|                     | {UARDCS}  {RAWRPT}  \<UAADF\>  RSML  WMOR                                                       |
| NC002005 | YYMMDD  HOUR  {RCPTIM}  {BID}  UASID  {UARID}  {UARLV}  \<UASDG\>              |
|                     | {UARDCS}  {RAWRPT}  {UACLD}  \<UAADF\>  RSML  QCEVR  WMOB  WMOS         |
|                     | WMOR                                                                                                                             |
| NC004005 | YYMMDD HHMM  RCPTIM  BID  AFRID  {RAWRPT}  AFTMP  AFWND                     |
|                     | {AFCLD}  \<AFICG\>  AFMST  \<ARSWD\>  ARPHT                                                        |
|                     | DGOT  PRWE  HOVI  PMSL  QMST  SST1  DAYW                                                       |
                                                                                                                        

| MNEMONIC | SEQUENCE                                                          |
|----------|-------------------------------------------------------------------|
| RCPTIM   | RCTS  RCYR  RCMO  RCDY  RCHR  RCMI                                |
| BID      | SEQNUM  BUHD  BORG  BULTIM  BBB                                   |
| RAWRPT   | RRSTG                                                             |
| AFRID    | RPID  CORN  CLAT  CLON  FLVL  PSAL                                |
| AFTMP    | QMAT  TMDB                                                        |
| AFWND    | QMWN  WDIR  WSPD                                                  |
| AFCLD    | CLAM  CLTP  HOCB  HOCT                                            |

| MNEMONIC | NUMBER | DESCRIPTION                                                                         |
|------------|--------|-------------------------------------------------------------|
| YYMMDD   | 301011 | DATE -- YEAR, MONTH, DAY                                 |
| HOUR     | 004004 | HOUR                                                     |
| RCPTIM   | 352003 | REPORT RECEIPT TIME DATA                                 |
| BID      | 352001 | BULLETIN ID DATA                                         |
| UASID    | 361121 | RADIOSONDE/OZONESONDE STATION ID DATA                    |
| UARID    | 361122 | RADIOSONDE REPORT ID DATA                                |
| UARLV    | 361123 | RADIOSONDE REPORT LEVEL DATA                             |
| UASDG    | 361129 | RADIOSONDE SOUNDING SYSTEM DATA                          |
| UARDCS   | 361131 | RADIOSONDE REPORT DIAGNOSTIC DATA                        |
| RAWRPT   | 352002 | RAW REPORT                                               |
| UACLD    | 361128 | RADIOSONDE CLOUD DATA                                    |
| UAADF    | 361130 | RADIOSONDE 101AA "ADDITIONAL DATA" DATA                  |
| WMOB     | 001001 | WMO BLOCK NUMBER                                         |
| WMOS     | 001002 | WMO STATION NUMBER                                       |
| WMOR     | 001003 | WMO REGION NUMBER                                        |
| RSML     | 001197 | RADIOSONDE SHIP, DROP, OR MOBIL STATION ID               |
| QCEVR    | 033024 | STATION ELEVATION QUALITY MARK (FOR MOBIL STATIONS)      |
| HHMM     | 301012 | TIME -- HOUR, MINUTE                                     |
| AFRID    | 362030 | AIRCRAFT REPORT ID DATA                                  |
| AFTMP    | 362032 | AIRCRAFT TEMPERATURE DATA                                |
| AFWND    | 362033 | AIRCRAFT WIND DATA                                       |
| AFCLD    | 362036 | AIRCRAFT CLOUD DATA                                      |
| AFICG    | 362035 | AIRCRAFT ICING DATA                                      |
| AFMST    | 362034 | AIRCRAFT MOISTURE DATA                                   |
| ARSWD    | 362040 | RECCO SURFACE WIND DATA                                  |
| ARPHT    | 362039 | RECCO MANDATORY LEVEL PRESSURE/HEIGHT DATA               |
| PRWE     | 020003 | PRESENT WEATHER                                          |
| QMST     | 033218 | SDMEDIT QUALITY MARK FOR SEA SURFACE TEMPERATURE         |
| SST1     | 022043 | SEA TEMPERATURE                                          |
| DAYW     | 004193 | DAY OF THE WEEK                                          |
| DGOT     | 011031 | DEGREE OF TURBULENCE                                     |
| HOVI     | 020001 | HORIZONTAL VISIBILITY                                    |
| PMSL     | 010051 | PRESSURE AT MEAN SEA LEVEL                               |
| RCTS     | 008202 | RECEIPT TIME SIGNIFICANCE                                |
| RCYR     | 004200 | YEAR   - TIME OF RECEIPT                                 |
| RCMO     | 004201 | MONTH  - TIME OF RECEIPT                                 |
| RCDY     | 004202 | DAY    - TIME OF RECEIPT                                 |
| RCHR     | 004203 | HOUR   - TIME OF RECEIPT                                 |
| RCMI     | 004204 | MINUTE - TIME OF RECEIPT                                 |
| SEQNUM   | 035195 | CHANNEL SEQUENCE NUMBER                                  |
| BUHD     | 035021 | BULLETIN BEING MONITORED (TTAAii)                        |
| BORG     | 035023 | BULLETIN BEING MONITORED (CCCC)                          |
| BULTIM   | 035022 | BULLETIN BEING MONITORED (YYGGgg)                        |
| BBB      | 035194 | BULLETIN BEING MONITORED (BBB)                           |
| RRSTG    | 058008 | RAW REPORT STRING                                        |
| RPID     | 001198 | REPORT IDENTIFIER                                        |
| CORN     | 033215 | CORRECTED REPORT INDICATOR                               |
| CLAT     | 005002 | LATITUDE (COARSE ACCURACY)                               |
| CLON     | 006002 | LONGITUDE (COARSE ACCURACY)                              |
| FLVL     | 007197 | FLIGHT LEVEL                                             |
| PSAL     | 007196 | PRESSURE ALTITUDE RELATIVE TO MEAN SEA LEVEL             |
| QMAT     | 033193 | SDMEDIT QUALITY MARK FOR TEMPERATURE                     |
| TMDB     | 012101 | TEMPERATURE/DRY BULB TEMPERATURE                         |
| QMWN     | 033195 | SDMEDIT QUALITY MARK FOR WIND                            |
| WDIR     | 011001 | WIND DIRECTION                                           |
| WSPD     | 011002 | WIND SPEED                                               |
| CLAM     | 020011 | CLOUD AMOUNT                                             |
| CLTP     | 020012 | CLOUD TYPE                                               |
| HOCB     | 020013 | HEIGHT OF BASE OF CLOUD                                  |
| HOCT     | 020014 | HEIGHT OF TOP OF CLOUD                                   |

| MNEMONIC | SCAL | REFERENCE   | BIT | UNITS                    |-------------|
|----------|------|-------------|-----|--------------------------|-------------|
| YEAR     |    0 |           0 |  12 | YEAR                     |-------------|
| MNTH     |    0 |           0 |   4 | MONTH                    |-------------|
| DAYS     |    0 |           0 |   6 | DAY                      |-------------|
| HOUR     |    0 |           0 |   5 | HOUR                     |-------------|
| DAYW     |    0 |           0 |   3 | CODE TABLE               |-------------|
| WMOB     |    0 |           0 |   7 | NUMERIC                  |-------------|
| WMOS     |    0 |           0 |  10 | NUMERIC                  |-------------|
| WMOR     |    0 |           0 |   3 | CODE TABLE               |-------------|
| DGOT     |    0 |           0 |   4 | CODE TABLE               |-------------|
| HOVI     |   -1 |           0 |  13 | METERS                   |-------------|
| PMSL     |   -1 |           0 |  14 | PASCALS                  |-------------|
| SST1     |    2 |           0 |  15 | DEGREES KELVIN           |-------------|
| PRWE     |    0 |           0 |   9 | CODE TABLE               |-------------|
| QMST     |    0 |           0 |   4 | CODE TABLE               |-------------|
| RCTS     |    0 |           0 |   6 | CODE TABLE               |-------------|
| RCYR     |    0 |           0 |  12 | YEAR                     |-------------|
| RCMO     |    0 |           0 |   4 | MONTH                    |-------------|
| RCDY     |    0 |           0 |   6 | DAY                      |-------------|
| RCHR     |    0 |           0 |   5 | HOUR                     |-------------|
| RCMI     |    0 |           0 |   6 | MINUTE                   |-------------|
| SEQNUM   |    0 |           0 |  32 | CCITT IA5                |-------------|
| BUHD     |    0 |           0 |  48 | CCITT IA5                |-------------|
| BORG     |    0 |           0 |  32 | CCITT IA5                |-------------|
| BULTIM   |    0 |           0 |  48 | CCITT IA5                |-------------|
| BBB      |    0 |           0 |  48 | CCITT IA5                |-------------|
| RRSTG    |    0 |           0 |  64 | CCITT IA5                |-------------|
| RPID     |    0 |           0 |  64 | CCITT IA5                |-------------|
| CORN     |    0 |           0 |   3 | CODE TABLE               |-------------|
| CLAT     |    2 |       -9000 |  15 | DEGREES                  |-------------|
| CLON     |    2 |      -18000 |  16 | DEGREES                  |-------------|
| FLVL     |    1 |       -4000 |  20 | METERS                   |-------------|
| PSAL     |    1 |       -4000 |  20 | METERS                   |-------------|
| QMAT     |    0 |           0 |   4 | CODE TABLE               |-------------|
| TMDB     |    2 |           0 |  16 | DEGREES KELVIN           |-------------|
| QMWN     |    0 |           0 |   4 | CODE TABLE               |-------------|
| WDIR     |    0 |           0 |   9 | DEGREES TRUE             |-------------|
| WSPD     |    1 |           0 |  12 | METERS/SECOND            |-------------|
| CLAM     |    0 |           0 |   4 | CODE TABLE               |-------------|
| CLTP     |    0 |           0 |   6 | CODE TABLE               |-------------|
| HOCB     |   -1 |         -40 |  11 | METERS                   |-------------|
| HOCT     |   -1 |         -40 |  11 | METERS                   |-------------|

**Comment by PraveenKumar-NOAA** [comment]
Extracted all the ADPUPA Mnemonics information required for BUFR to IODA conversion.

**Comment by gthompsnJCSDA** [comment]
Praveen:  I may have a couple more of my own files to add, but it would be greatly helpful if you picked out only the very specific mnemonics used for only one obs-type rather than grouping all ADPUPA into a single batch.  When we run bufr2ioda.x, at some point, we are likely to have one stream of incoming data type (sonde for example, separated from aircraft obs) and using a yaml meant only for sonde data.

If you view my feature branch: `feature/add_conventional_unittests` then you will see I documented each data type singularly, provided a table of sample values, and a dump of bufr mnemonics, plus the yaml intended to be a starting point for each data type.  I will be returning to this work in the next 2 months to resolve some gaps.

Example for one data type at a time is here...
https://github.com/JCSDA-internal/ioda-converters/blob/feature/add_conventional_unittests/doc/bufr_table_samples/sonde_bufr_mnemonics.txt

intended to be parsed using ...
https://github.com/JCSDA-internal/ioda-converters/blob/feature/add_conventional_unittests/test/testinput/sonde_wmoBUFR2ioda.yaml
