### ISSUE TITLE
Work on IMS snow and ice cover ioda-converter from IMS ascii file

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#479]
## Description

Development of IMS snow and ice cover ioda-converters from IMS ascii file

- Capability to covert 24km, 4km, and 1km ascii data into ioda NetCDF file
- Several options need to be tested: (1) Reading lat/lon from the binary files provided by NSIDC/NIC, (2) Projecting lat/lon using pyproj, (3) Converting the indices into snow cover and ice cover within ioda-converters, separately, (4) Converting the indices into snow cover and ice cover within ioda-converters together, (5) Converting the indices directly into ioda NetCDF format by excluding sea and outside of region points, and (6) Converting the indices directly into ioda NetCDF format

## Concerns

- data size including two big-sized binary files (15MB for each), one big-sized ascii file (38MB), and one big-sized output file (1.7GB)
- CPU time to processing data for a given day
- Approach to output data form (e.g., snow cover, ice cover, or indices)  

## Solution

- Reduce data size
- Due to the different mask for snow cover and ice, how to output them into a file with the smallest data size
- Speed up processing time

## Requirements

Ioda-converter for this product need to be developed based on the land DA users' request

## Acceptance Criteria (Definition of Done)

What does it mean for this to be finished?

## Dependencies

No
 - add issue dependencies in ZenHub as appropriate

Does this block progress on other issues?
 - No

**Comment by gthompsnJCSDA** [comment]
Just a few quick comments:
1) please indicate an estimate on the effort. Our usual practice is a full point is 1/2 of a day.
2) is the output netcdf4 file expected to be over 1GB while the ASCII file is only 38MB?  Hopefully that won't be the case.
3) you might wish to add a Milestone of end of April for example as a target finish date.

**Comment by YoulongXia-NOAA** [comment]
Greg, thank you. The response is below:
1.  added
2. It as such a case as it add 7 more data array: snowCover@ObsError, snowCover@PreQC, snowCover@PreQC, float time@MetaData(nlocs) ; float latitude@MetaData(nlocs) ;  float longitude@MetaData(nlocs) ;  char datetime@MetaData(nlocs, ndatetime) ;  int record_number@MetaData(nlocs) ; This makes the data size large.  Clara Draper at PSL will initiate a meeting with the related scientists and see how to reduce data size.
3.  added.

**Comment by YoulongXia-NOAA** [comment]
Note that nlocs = 6144x6144, a big array.

**Comment by YoulongXia-NOAA** [comment]
ASCII file has only one array with values (0, 1, 2, 3, or 4) and 30-line headers. I need to add lat/lon, and the other variables are in standard ioda-converters setup.

**Comment by gthompsnJCSDA** [comment]
Some considerations:
1) you have twice stated the snowCover@PreQC.  There should be no need for record_number or the time arrays as they are not important/necessary - only DateTime is needed.  I am also imagining the grid of values has a lot of zeroes in it, which should help netCDF compression make the files smaller.
2) an estimate of 10.5 days is really big.  The estimate should be based on actual work time you expect to spend so that is 84 hours effort.

**Comment by YoulongXia-NOAA** [comment]
if I keep only 100% or 0 snow cover and mask the others out, the data size is reduced 452MB. After the data is gzipped, the data size becomes 65MB.  I will discuss with my collaborators and colleagues to see if I can remove record_number and time array. For twice stated the snowCover@PreQC, it should be only one.

**Comment by YoulongXia-NOAA** [comment]
Using writer.BuildNetcdf rather than writer.ExtractObsData to reduce runtime by 50% when maskout is used for snow cover converter. When all data are written out, the runtime is reduced by 70%. As code performance improvement will be addressed for ioda-converter team next year, my code is fine for current development work and leave it for future improvement.

**Comment by YoulongXia-NOAA** [comment]
Use 

lons = lons.astype('float32')
lats = lats.astype('float32')
vals = 0.0*data.astype('float32')
errs = 0.0*data.astype('float32')
qflg = 0*vals.astype('int32')

The output data size is reduced from 497MB to 415MB.  It is not reduced by 50% as expected. All variables has been set as float32 or int32 except for time and datetime as they are objects. I do not know how to set them.

**Comment by YoulongXia-NOAA** [comment]
The reason remains unclear but it may be associated with the ioda-converters libraries.  We may solve this issue in Ioda-Coverters version 2 (ioda-2), hopefully.

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA moving this from new issue (limbo) to backlog (it will be worked on).  Has the initial converter been completed and now an update to IODA v2 is needed?  @amfox37  do you know?

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA and @amfox37  I now see issue #629 which is close so going to close this issue.  Please reopen if this in incorrect.
