### ISSUE TITLE
ioda-converters make install failed

### ISSUE THREAD

**Issue by lliu1220** [JCSDA-internal/ioda-converters#480]
## Current behavior (describe the bug)

passed ecbuild and make, failed at 

make install:

CMake Error at cmake_install.cmake:46 (file):
  file cannot create directory: /usr/local/lib64/cmake/iodaconv.  Maybe need
  administrative privileges.

make: *** [install] Error 1

**Comment by lliu1220** [comment]
ctest failed at:
The following tests FAILED:
          1 - iodaconv_chem_coding_norms (Failed)
          2 - iodaconv_gsi-ncdiag_coding_norms (Failed)
          3 - iodaconv_land_coding_norms (Failed)
          4 - iodaconv_lib-python_coding_norms (Failed)
          5 - iodaconv_marine_coding_norms (Failed)
          6 - iodaconv_metar_coding_norms (Failed)
          7 - iodaconv_ncep_coding_norms (Failed)
          8 - iodaconv_ssec_coding_norms (Failed)
          9 - iodaconv_wrfda-ncdiag_coding_norms (Failed)
         10 - iodaconv_singleob_coding_norms (Failed)
         26 - test_iodaconv_ncep_bufr (Failed)
Errors while running CTest

**Comment by travissluka** [comment]
using `-DCMAKE_INSTALL_PREFIX=` when you run `ecbuild` should allow you specify the installation path to something local. Out of curiosity though why are you trying to do a `make install` ? The only time I've ever seen an install is for the TravisCI soca/soca-science tests.

**Comment by srherbener** [comment]
@lliu1220 if you are only wanting to do development, you can do that work without installing the ioda-converters package. Instead you can use ioda-bundle:
```
git clone https://github.com/jcsda-internal/ioda-bundle
cd ioda-bundle
# edit the CMakeLists.txt file
#   change the ecbuild_bundle(... iodaconv ... ioda-converters.git) to use your feature branch instead
#   of develop
#   For example:
#       ecbuild_bundle( PROJECT ioda-data GIT "https://github.com/JCSDA-internal/ioda-data.git" BRANCH feature/HF_radar UPDATE )
# 

mkdir build
cd build
ecbuild -DBUILD_IODA_CONVERTERS=ON ..
make -j4
ctest

# just run your test
ctest -VV -R test_iodaconv_hfradar
```
Hope this helps!

**Comment by lliu1220** [comment]
@travissluka @srherbener 
Thank you ! that is very helpful.
Will try later.

**Comment by srherbener** [comment]
The ioda-bundle method is relatively new and I now see that the README.md for ioda-converters is out of date and still shows the old way of installing and testing. Sorry about that! I'll fix the README.md file.

**Comment by lliu1220** [comment]
@srherbener 
I followed your instruction, ecbuild passed, make -j4 failed at (develop branch):

[ 81%] Building Fortran object oops/qg/model/CMakeFiles/qg.dir/qg_change_var_interface.F90.o
[ 81%] Building Fortran object oops/qg/model/CMakeFiles/qg.dir/qg_getvalues_interface.F90.o
[ 81%] Building Fortran object oops/qg/model/CMakeFiles/qg.dir/qg_error_covariance_interface.F90.o
[ 81%] Building Fortran object oops/qg/model/CMakeFiles/qg.dir/qg_model_interface.F90.o
[ 81%] Linking CXX shared library ../../../lib/libqg.so
[ 81%] Built target qg
make: *** [all] Error 2

**Comment by lliu1220** [comment]
this issue was fixed.
