### ISSUE TITLE
Gather samples of AMVs data in WMO BUFR format for various tests 

### ISSUE THREAD

**Issue by ilianagenkova** [JCSDA-internal/ioda-converters#487]
GSI reads satellite winds (AMVs ) from so called satwnd dumps, which are NCEP-flavored BUFR files.
Collect samples of AMVs data in WMO BUFR format (as if taken from GTS) for various tests:
- bufr to ioda converters tests
- replacing BUFR mnemonics with corresponding WMO BUFR codes (F-X-Y: #-##-###)
- others

As requested the following data was collected:
- GOES-17 AMVs, VIS, hour long dataset (new BUFR)
- S-NPP VIIRS AMVs, IR, one triplet output (new BUFR)
- NOAA-20 VIIRS AMVs, IR, one triplet output (new BUFR)
- Meteosat-8 and Meteosat-11 AMVs, IR, one hour long dataset (new BUFR)

- Himawari-8 AMVs, IR, one hour long dataset (old BUFR)

The raw data was also dumped into ASCII *out files. 
Utilized BUFR tables are printed out at the bottom of the *out files.

**Comment by gthompsnJCSDA** [comment]
We now have most AMV data in BUFR for the tests we need, therefore I am closing this issue.

**Comment by ilianagenkova** [comment]
@gthompsnJCSDA , thanks!
