### ISSUE TITLE
Update to the existing SSS SMAP (RSS feed in NetCDF) ioda-converter to include SMAP from JPL (in HDF5)

### ISSUE THREAD

**Issue by ShastriPaturi** [JCSDA-internal/ioda-converters#490]
## Description
The existing ioda-converter (smap_sss2ioda.py) is extended to include conversion of SSS SMAP data from JPL in HDF5 format.
This is needed since the SMAP data from RSS feed do not have obs_error included, while SMAP data from JPL do.

**Comment by ShastriPaturi** [comment]
> @ShastriPaturi , I think that work might have been done by @HamidehGMAO already. Did you check with her?

@guillaumevernieres, I have checked with @HamidehGMAO earlier and then submitted this issue. I will wait for her response though, for clarity.

**Comment by HamidehGMAO** [comment]
@ShastriPaturi the current SSS SMAP can convert both RSS and JPL data, I thought we discussed it in our meeting, but maybe I was not clear. I remember we thought it would be great if you could add your SSS converter for SMOS

**Comment by ShastriPaturi** [comment]
The converter already exists.

**Comment by HamidehGMAO** [comment]
> @HamidehGMAO thanks.
> I will close this issue.
> I am adding the SSS converter for SMOS

Great! Thanks @ShastriPaturi
