### ISSUE TITLE
smap_sss2ioda not working  

### ISSUE THREAD

**Issue by mjkagnes123** [JCSDA-internal/ioda-converters#493]
## Current behavior (describe the bug)
Smap_sss2ioda fails with error messages indicating (1) variable types are not matched (integer vs. float) for sss_qc and variable "col" and (2) re.search for institution name (JPL vs. RSS) fails.

**Comment by ShastriPaturi** [comment]
@mjkagnes123, I have a version of smap_sss2ioda that is working for both JPL and RSS feeds.
I will let you know about it tomorrow.

**Comment by mjkagnes123** [comment]
Great! I will be looking forward to it. Thank you!
________________________________
From: Shastri Paturi ***@***.***>
Sent: Thursday, April 8, 2021 8:33 PM
To: JCSDA-internal/ioda-converters ***@***.***>
Cc: Kim, Min-jeong (GSFC-610.1)[MORGAN STATE UNIV.] ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [JCSDA-internal/ioda-converters] smap_sss2ioda not working (#493)


@mjkagnes123<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmjkagnes123&data=04%7C01%7Cmin-jeong.kim%40nasa.gov%7C0e859ebedcce4539590908d8faef2be7%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637535252431283594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PXT1%2B0jz0A%2FrA%2Byc0B4S5RNSRFbmhCUKq8j1HsiKNTE%3D&reserved=0>, I have a version of smap_sss2ioda that is working for both JPL and RSS feeds.
I will let you know about it tomorrow.

**Comment by ShastriPaturi** [comment]
@guillaumevernieres I have a PR opened
