### ISSUE TITLE
Improve performance of bufr to netcdf python scripts.

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#50]
Make sure the conversion is fast and the netcdf file size is minimized.
* netcdf groups may be useful for reducing size
* Clara tried converting 1bamua.gdas.2018041500 and it ran very slowly and crashed after a long time
* I experimented with 1bamua.gdas.2018020100
    * 379,774 obs total
    * After running for 2 days, it was only about 1/2 completed (181,700 obs converted)
    * Removed "replication" extraction (ufbevn, ufbseq, ufbrep calls), entire file converted in 27 minutes
    * Dump text for entire file: one minute!
* Profiling showed that python masked arrays are slow, netcdf writes of masked array data is slow (WriteNcVar), data conversion of floats (bufr) to actual data is slow (bufr_float_to_actual), and reading bufr data is slow (read_subset)
    * Get rid of masked arrays
    * Write complete blocks of data into netcdf (instead of line by line)
    * Minimize conversion of data (only really need to do float pattern to string)
    * Minimize the number of libbufr read calls

**Comment by srherbener** [comment]
There is a BUFR to netcdf converter in github called "pytroll/python-bufr". There is a reference to this converter on the NCEP website. Looks like they wrote their own BUFR parser in C. 
* Faster than the Fortran parser (bufrlib)?
* Is this open source?

**Comment by ytremolet** [comment]
Another set of open source tools that could be useful is ecCodes. See:
https://confluence.ecmwf.int/display/ECC

**Comment by srherbener** [comment]
It's been decided to address the python performance issue by writing compiled code. The EMC converter is the implementation of this. Plus this performance information is out dated. Therefore, I am going to close this issue.
