### ISSUE TITLE
Update yamls and outputs for adpsfc data

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#500]
## Description

The bufr2ioda.x converter is currently undergoing extensive changes. Once the changes are done and testing ends, the yamls will need to be updated. They are:
ioda-converters/test/testinput/bufr_adpsfc.yaml
ioda-converters/test/testinput/bufr_snow_adpsfc.yaml

Once the yamls run with the bufr2ioda.x, they will produce IODA-formatted netCDF files that will be different from the original versions. The following files will have to be updated:
ioda-converters/test/testoutput/gdas.t06z.adpsfc.tm00.nc
ioda-converters/test/testoutput/gdas.t06z.adpsfc_snow.tm00.nc

[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

The new bufr2ioda.x converter will be required to be fully developed when this issue is finished.

## Acceptance Criteria (Definition of Done)

When it is finished, the 4 files mentioned above will be added to the ioda-converters branch. The tests will also have to pass.

## Dependencies

The bufr2ioda.x executable should be finished updating.

**Comment by BenjaminRuston** [comment]
@nicholasesposito I"m closing this issue for now as the files have been added and the ctest were passing. 

please update and reopen if this is incorrect.
