### ISSUE TITLE
Write/test yaml converting adpsfc prepbufr file to IODA

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#502]
## Description

[ ] Write a yaml that can convert the prepbufr file. Use the mnemonics determined in #501 
[ ] Use the yaml to convert into an IODA-formatted netCDF file.
[ ] Add the outputs to the testoutput directory.
[ ] Add tests to the CMakeLists.txt files
[ ] Have the tests pass.

## Requirements

All important mnemonics need to be known. #501  must be finished.

## Acceptance Criteria (Definition of Done)

It will be finished when all files have been checked, pushed, and tests have passed.

## Dependencies

The bufr2ioda.x converter update must be finished.

**Comment by nicholasesposito** [comment]
A yaml file for version 1 has been completed. I am now working on a version 2. The version 2 will reflect all of the changes being done with NCEPLIBS-bufr, and since that is a work in progress, so is the version 2 of the yaml file.

**Comment by nicholasesposito** [comment]
![gdas t12z adpsfc_pb_queries_temperatureAir(1)](https://user-images.githubusercontent.com/62616739/129384147-7e48918e-d818-4bab-ae17-2239a6106db6.jpg)
Above is the first image generated using the queries. It shows Air temperature at the surface. It shows that there is still work that needs to be done on the NCEPLIBS-bufr so that it better reads sequences within square brackets.

Ron told me that those queries for square brackets will likely look like: " */T__INFO/T__EVENT/TOB" so the next update of yaml file will look like that.

**Comment by nicholasesposito** [comment]
The following four images were used as validation for ADPSFC. They matched the GSI. Only Pressure was different from GSI and the reason is being investigated.
![gdas t12z adpsfc_pb_qv3_v](https://user-images.githubusercontent.com/62616739/150575345-b2c86872-9996-41c1-b989-d7485b2a99f4.jpg)
![gdas t12z adpsfc_pb_qv3_u](https://user-images.githubusercontent.com/62616739/150575348-0642be36-e6ee-4d18-8305-e3b52192c7ad.jpg)
![gdas t12z adpsfc_pb_qv3_Tair](https://user-images.githubusercontent.com/62616739/150575349-0d0c9064-f488-4533-8d00-c2266ffbbbbf.jpg)
![gdas t12z adpsfc_pb_qv3_q](https://user-images.githubusercontent.com/62616739/150575352-0d5a3c29-1e93-4193-861c-b8c34773ce30.jpg)

Pressure:
![gdas t12z adpsfc_pb_qv3_Pair](https://user-images.githubusercontent.com/62616739/150575390-832f80a7-216d-423f-8624-fb41fb091e2c.jpg)

**Comment by BenjaminRuston** [comment]
@nicholasesposito OK,, guess I"m figuring it out.. One set of issues for prepBUFR and one set for BUFR dump files?  But it appears this work is done?  Please close if this is so.

**Comment by nicholasesposito** [comment]
Still working out issues with Pressure. Will close once that is done following a PR to add the file to the IODA-converter repository.

**Comment by nicholasesposito** [comment]
The comparisons of GSI vs prepbufr ADPSFC data are provided at #757

**Comment by nicholasesposito** [comment]
PR #904 has been completed. All yamls, inputs and output files have been added. All the tests pass. This will now be closed.
