### ISSUE TITLE
Gather and determine the mnemonic sequences in for ADPSFC bufr files

### ISSUE THREAD

**Issue by nicholasesposito** [JCSDA-internal/ioda-converters#503]
## Description

The mnemonics that are read in by the prepdata code are different than what are in the actual bufr files.
The purpose of the issue is to:
[] Determine the sequence of mnemonics used in an adpsfc bufr file using the bufr table
[] Determine which mnemonics are read in by the obsproc prepdata code.
[] Compare the two and determine which mnemonics are important.

## Requirements

This will be documentation, which will be in the form of a spreadsheet attached at the end.

## Acceptance Criteria (Definition of Done)

It will be finished once all important mnemonics are determined and documented.

## Dependencies
There are no dependencies.

**Comment by nicholasesposito** [comment]
You can find the spreadsheet here:
https://docs.google.com/spreadsheets/d/1QCyNrPn9rox6pUTA1eK-D-FBWLZyVlEeL_jiMXw283U/edit?usp=sharing

**Comment by BenjaminRuston** [comment]
@nicholasesposito is this done?  How is this issue different from #501 ,, appears you've knocked some of these out and they just haven't closed.

**Comment by nicholasesposito** [comment]
I was usually keeping them open until I was sure they were 100% done but it's about that close anyway so I will close it.
