### ISSUE TITLE
[Bug] iodaconv doesn't build with IODA branch feature/ioda-v2

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA-internal/ioda-converters#505]
## Current behavior (describe the bug)

ioda-bundle with option to build ioda-converters fails to build when using IODA feature/ioda-v2 branch but builds with develop.

## To Reproduce

What computer are you running on?
Hera

What compilers/modules are you using?
Intel stack

Steps to reproduce the behavior

1. clone
2. edit CMakeLists.txt
3. ecbuild -DBUILD_IODA_CONVERTERS=ON -DBUILD_PYTHON_BINDINGS=ON -DMPIEXEC_EXECUTABLE=`which srun` -DMPIEXEC_NUMPROC_FLAG="-n"  ../

## Expected behavior
It should compile.

## Additional information (optional)
The error (for several files) is below:

```
/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/dev/ioda-bundle/iodaconv/src/satbias/SatBiasConverter.cpp(47): error: no instance of function template "std::make_shared" matches the argument list
            argument types are: (const char [12], long, long, long)
    newDims.push_back(std::make_shared<ioda::NewDimensionScale<int>>("npredictors",
                      ^
/usr/include/c++/4.8.5/bits/shared_ptr.h(610): note: this candidate was rejected because there is a type mismatch after argument substitution
      make_shared(_Args&&... __args)
      ^

/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/dev/ioda-bundle/iodaconv/src/bufr/IodaEncoder/IodaEncoder.cpp(104): error: no instance of function template "std::make_shared" matches the argument list
            argument types are: (const std::string, std::size_t, std::size_t, std::size_t)
                  auto newDim = std::make_shared<ioda::NewDimensionScale<int>>(scale.name,
                                ^
/usr/include/c++/4.8.5/bits/shared_ptr.h(610): note: this candidate was rejected because there is a type mismatch after argument substitution
      make_shared(_Args&&... __args)
      ^

compilation aborted for /scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/dev/ioda-bundle/iodaconv/src/bufr/IodaEncoder/IodaEncoder.cpp (code 2)
```

**Comment by rhoneyager** [comment]
Found it in https://github.com/JCSDA-internal/ioda/pull/139. We should probably attempt a ioda-converters build alongside CI testing for ioda. The dimension scale specification changed slightly and I wasn't aware that it was being used. See https://github.com/JCSDA-internal/ioda/blob/feature/ioda-v2/src/engines/Examples/Basic/05b-ObsGroupAppend.cpp#L196 for the new calling method.

**Comment by srherbener** [comment]
I'm looking into this now.
