### ISSUE TITLE
Add a converter for marine insitu data from ICOADS

### ISSUE THREAD

**Issue by travissluka** [JCSDA-internal/ioda-converters#506]
## Description

Add a converter to process marine insitu data from ICOADS.
(We currently have a converter for WOD insitu data, but ICOADS is supposedly better, and is updated more frequently with just a 1 month lag)

data source:
https://www.ncei.noaa.gov/access/metadata/landing-page/bin/iso?id=gov.noaa.ncdc:C00606

**Comment by BenjaminRuston** [comment]
@travissluka moving to icebox please close of deprecated or falling under new issues
