### ISSUE TITLE
ADPUPA (NC002001: RAWINSONDE - FIXED LAND) BUFR Mnemonics

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#512]
## Description

The purpose of the issue is to:

- Determine the sequence of mnemonics used in an ADPUPA BUFR file for the NC002001 subset using the BUFR table
https://drive.google.com/drive/folders/1MIKj8TYo32f4sPmcem55nw77C7BXv4LK
- Determine which mnemonics are read-in by the obsproc_prep prepdata codes
-https://docs.google.com/spreadsheets/d/1NxnoAQXkRzWhPs8FxJEllxdkmaM1xiZm4f-XqKwaK1M/edit#gid=1909681487
- Compare the two and determine which mnemonics are important
- Determine important ADPUPA NC002001 mnemonics for the bufr2ioda conversion 
https://docs.google.com/spreadsheets/d/1NxnoAQXkRzWhPs8FxJEllxdkmaM1xiZm4f-XqKwaK1M/edit#gid=0

## Requirements

Documentation, which will be provided in the form of a text file.

## Acceptance Criteria (Definition of Done)

It will be finished once all important mnemonics are determined and documented.

## Dependencies

There are no dependencies.

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA assume this is still in play, moving from the limbo of `new issues` into the going to be addressed `backlog`

**Comment by PraveenKumar-NOAA** [comment]
It has been completed along with rest of the ADPUPA BUFR subsets NC002002,
NC002003, NC002004, NC002005, and NC004005. A PR has been issued for all of
these and merged successfully a few months ago.

Let me know if you have any questions.

Thank you,
Praveen Kumar
***@***.***/NCEP/EMC
5830 University Research Ct., Rm. 2069
College Park, MD 20740
Phone: (301) 683-3715
Mobile: (201) 657-3096

**Comment by BenjaminRuston** [comment]
closed per @PraveenKumar-NOAA  comment above
