### ISSUE TITLE
Discuss IODA variable naming convention - how to adopt and other issues

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA-internal/ioda-converters#519]
## Description

As @DavidSimonin and I are discussing the use of UFO variable_transforms, we have to involve (immediately) the discussion of how to adopt the [IODA variable naming conventions](https://docs.google.com/spreadsheets/d/1EQmJdkqsL3u2-SdpKSA4gkDLd6fCt3iAQ-XNcjz_2M0) and how to deal with a thorny issue of variables that are applicable at/near the surface as well as same variables aloft.  Obvious example: air_pressure and surface_pressure, but also air_temperature and near-surface-temperature (like 2 meters).  Many MetOffice ODB processing uses specific names of variables together with an indicator of its altitude (e.g., dew_point_temperature_surface), but the proposed IODA variable naming convention would be more like: temperatureDewpoint@ObsValue and corresponding attribute to signify near the surface.  But "attributes" are not really part of IODA obs variables, neither are designated units inherently.

This issue is to open a dialogue of a group of us to discuss how we can easily move forward efficiently to include attributes explicitly in incoming IODA data as well as outgoing derived variables happening in the variable_transforms (or other) space.

**Comment by rhoneyager** [comment]
Issue reflects that we had many meetings for discussion.
