### ISSUE TITLE
Handle ocean obs for WAVES simulation

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#53]
Stylianos has sample wave spectra obs data (insitu and satellite measurements) that contains a 2D array of floating point numbers per location. The netcdf obs file will need to be enhanced (as well as the ObsSpace in-memory store) to handle a 2D array element for each location.

**Comment by srherbener** [comment]
@guillaumevernieres, what is the urgency of this issue? We are looking at replacing the vector storage with n-dim array storage in the ObsSpace container now. This change should be sufficient to accommodate the wave spectra data. We would still need to work on the converter script.

**Comment by BenjaminRuston** [comment]
@travissluka closing for now!!!!
