### ISSUE TITLE
Investigate Python/netcdf utilities

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#54]
Rahul recommended that I look at the following utilities for Python and netcdf:
* nco
    * brew install nco
    * utilities for editing netcdf
* PyTables
    * based on HDF5
    * useful for obs handling 
* xarrays
    * arrays with labeling

- [x] nco
- [ ] PyTables
- [ ] xarrays
- [ ] pandas

**Comment by srherbener** [comment]
nco is being installed into the containers now

Still need to look at PyTables.

**Comment by jmccreight** [comment]
@srherbener what's the take on xarray? https://github.com/pydata/xarray?
Does not seem like anyone is using it in ioda-converters, which surprised me. I would guess that the dependencies might be considerable. But it makes life incredibly easy, e.g. lazy operations and out-of- operations using dask.

**Comment by srherbener** [comment]
@jmccreight, Thank you for bringing xarray to our attention. It looks interesting. We started with dictionaries using multiple keys (record, location, variable), where each key is a tuple of 3 or 4 items, and we are concerned about this creating a performance bottleneck. Would xarray allow us to label data with 2 or 3 key values (that are tuples)? If so, would it be faster than using a dictionary approach?

**Comment by CoryMartin-NOAA** [comment]
@srherbener @jmccreight My $0.02: If xarray (or Pandas, or something else/similar) can use compiled C and speed up performance of things like the dictionaries, then I think it might be a great option to pursue. Otherwise if performance is similar, I fear the added dependencies might not be worth it as it will only make it more difficult to port the ioda-converters to other platforms/systems.

**Comment by srherbener** [comment]
@CoryMartin-NOAA, good point! I hope that one of these alternatives pans out for us.

**Comment by aerorahul** [comment]
@srherbener @CoryMartin-NOAA @jmccreight 
My $0.02: `xarray` and `pandas` are both awesome, but, the interfaces are still evolving (AFAIK) and thus puts a heavy burden on the users to keep backward compatibility alive.
I have used both extensively.

**Comment by jmccreight** [comment]
@srherbener @CoryMartin-NOAA @aerorahul 
Thanks for the discussion. That is helpful as I'll being starting an obs converter sometime in the next few weeks (2 weeks vacation increases uncertainty in the start date... but i'll open an issue about it when it gets closer to happening). 

xarray would be my go-to, so now I have context for what's required and the potential pros and cons. I will consider developing an xarray-based-alternative approach for my converter as I develop the converter following existing IODA-converter codes. I'm a bit skeptical that xarray would have much to offer in this case. Generally the out-of-memory scenario is where it xarray+dask shines and I'm guessing that the input and output translation is not generally memory intensive. I dont think the performance will necessarily be better and the API stability and increased level of dependencies are genuine concerns. 

@srherbener I assume the ordered dict tuple usage has an example here:
https://github.com/JCSDA/ioda-converters/blob/fda1a9b58d1ea3059ee083c990e7cdba86f9d297/src/marine/emc_ice2ioda.py.in#L61
 
Let me know if that's correct or if there's something better to look at. When the time comes I can make a case to evaluate your question.

**Comment by srherbener** [comment]
@jmccreight, that's a good example. The script is building a dictionary that has three "indices", as shown on line 61 in your comment, where the first index has just one key value equal to zero. The general format is:
~~~~~~~~
   Dict[record_key][location_key][variable_key]
~~~~~~~~

record_key can be a tuple that holds things like a weather station ID, aircraft flight ID, station elevation, balloon launch time, etc. The idea behind the record is to keep things like a single balloon radiosonde sounding grouped together.

location_key is in general the tuple (x,y,z,t) representing the observation location. For things like satellite instruments which do a vertical integration the location_key would be (x,y,t).

variable_key is a tuple (variable_name, group_name) where group_name is a collection of related values such as observation values, or obs error estimates, or obs QC marks.

The dictionary on line 61 gets passed to a method called ExtractObsData, near the end, to reformat that dictionary into a set of dictionaries more suitable for the next method BuildNetcdf (lines 116, 117 in emc_ice2ioda.py.in).

The primary purpose of the first dictionary and the shuffling around is to accommodate obs types that contain missing data. Radiosonde is an example, as the balloon rises the location changes (x,y,z,t) and at some points typically only T and Q are measured and at other points only U and V are measured. When you put all of this together, U and V are missing where T and Q exist and vice versa.

The ExtractObsData method (source is in src/lib_python/ioda_conv_ncio.py) is walking through the dictionary and lining up all of the variables (obs data) at each unique location. I'm pretty sure this is where the bottleneck exists. It would be great if one of xarray, pandas, PyTables, ect. could help do this task more efficiently.

**Comment by srherbener** [comment]
We have started to incorporate xarray and pandas into our python scripts. Plus it's been well over a year since this has had any activity. Therefore I'm going to close this issue.
