### ISSUE TITLE
Test files are consuming too much space in this repository

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#579]
## Description

The addition of numerous test files, both input and reference files, is bumping up against a repo size limit (50 MB) that we have applied to repositories holding source code.

It's a very good thing that we have lots of tests and test files, but hitting the limit is an indication that we need to manage the test files differently than just checking them into this repository.

One possible solution is to move the test files to the ioda-data repository, which is by design meant to hold and manage test files via git-lfs.

We have temporarily increased the limit to 100 MB until we get the longer term solution in place.

## Requirements

Move the test files out of this repository so it can remain on the 50 MB size limit.

## Acceptance Criteria (Definition of Done)

The ioda-converters repository remains under the 50 MB size limit.

## Dependencies

None

**Comment by travissluka** [comment]
this is related to an issue I opened up a long time ago: https://github.com/JCSDA-internal/ioda-converters/issues/228
