### ISSUE TITLE
python vs python3

### ISSUE THREAD

**Issue by mmiesch** [JCSDA-internal/ioda-converters#583]
@mmiesch commented on [Thu Jul 01 2021](https://github.com/JCSDA-internal/ioda/issues/324)

## Current behavior (describe the bug)

When I run the ioda-converters ctests on my Mac, many fail.  The reason is because some of the python scripts use the `#! /usr/bin/env python` interpreter and others use the `#! /usr/bin/env python3`.

On my Mac (even with Big Sur), `/usr/bin/env python` points to `/usr/bin/python` which is python 2.7.  This is a system utility and I am not able to soft link it to python3, even with root permissions.

Is there any problem with using `/usr/bin/env python3` for all python scripts?  When I do this, the tests pass.

## To Reproduce

> What computer are you running on?
Mac: Big Sur

> What compilers/modules are you using?

```
Currently Loaded Modules:
  1) jedi-clang/12.0.0    7) hdf5/1.12.0           13) eigen/3.3.5           19) fckit/ecmwf-0.9.2
  2) szip/2.1.1           8) pnetcdf/1.12.1        14) bufr/noaa-emc-11.5.0  20) atlas/ecmwf-0.23.0
  3) openmpi/4.1.0        9) netcdf/4.7.4          15) gsl_lite/0.37.0       21) pio/2.5.1-debug
  4) jedi-openmpi/4.1.0  10) nccmp/1.8.7.0         16) pybind11/2.6.2        22) json/3.9.1
  5) zlib/1.2.11         11) nco/4.9.9             17) ecbuild/ecmwf-3.6.1   23) json-schema-validator/2.1.0
  6) udunits/2.2.28      12) boost-headers/1.68.0  18) eckit/ecmwf-1.16.0    24) jedi/clang-openmpi/12.0.0
```

> Steps to reproduce the behavior

1. build ioda-converters
2. run ctest

## Expected behavior

tests pass

**Comment by rickgrubin** [comment]
This issue -- `python` vs. `python3` -- crops up now and again. It is not unique to **macOS**, it shows up elsewhere (**_cheyenne_** is an example). On the mac, linking `/usr/bin/python` to `python3` would cause some things to break in interesting and confusing ways -- even if you could do it, the results would be less than entertaining.

For **macOS**, use [brew / python3](https://docs.brew.sh/Homebrew-and-Python#python-3x) -- it is built for compatibility with _XCode_ and the system-installed `python3` libraries.

`python2.7` was [EOL'd on Jan.01.2020](https://www.python.org/doc/sunset-python-2/) and should not be used at all, anywhere, in JEDI code.

Any and all tests should be converted to use `python3`.

**Comment by srherbener** [comment]
I agree that every script  that sets the interpreter should use `#!/usr/bin/env python3`. I see no reason to not do this.

**Comment by CoryMartin-NOAA** [comment]
I think `#!/usr/bin/env python3` is less compatible though. If the user's environment has python 3 as default, /usr/bin/env python3 might not exist?

**Comment by srherbener** [comment]
An alternative could be to always check the version at the start of the script and throw an error if it's not version 3.

I would guess however, that the occurrence of python3 not being found would be more rare than python being version 2 and the script quitting after discovering this. So I would lean toward setting the interpreter to python3.

Maybe we could use the cmake configure_file command for all the scripts, and then have the interpreter line be something like `#!/usr/bin/env @IODACONV_PY_VERSION@` and then set IODACONV_PY_VERSION in the top level CMakeLists.txt to 'python3' for now. That way we could easily change all the scripts later if it turns out to be a problem.

**Comment by rickgrubin** [comment]
`/usr/bin/env` searches a user's `$PATH`

The advantage of `#!/usr/bin/env python3` is that it will use whatever `python3` executable appears first in the user's `$PATH`.

The disadvantage of `#!/usr/bin/env python3` is that it will use whatever `python3` executable appears first in the user's `$PATH`.

On multiple systems `#!/usr/bin/env` is more _"portable."_ On a singular system `#!/path/to/known/python3` is guaranteed to work, and you can pass arguments to `python3`, whereas you cannot with `#!/usr/bin/env python3`

Of course, `env` might not be in `/usr/bin`, but that would be a rare case.

If you care about which version of python3 you're running:

`python_dot_version=$(python3 -c 'import sys;print(sys.version_info[0],".",sys.version_info[1],sep="")')`

`#!/usr/bin/env python3` provides the greatest degree of cross-platform compatibility, both for multiple versions of python and multiple hosts / operating systems.

**Comment by travissluka** [comment]
we were having similar issues on one of the hpcs and have already changed soca-science scripts to explicitly use  `#!/usr/bin/env python3`
