### ISSUE TITLE
ioda-converter for GSI files specifying cross-channel correlations

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/ioda-converters#586]
## Description

Write a converter from GSI files specifying cross-channel correlations to JEDI files specifying cross-channel correlations.

**Comment by shlyaeva** [comment]
@KristenBathmann-NOAA could you please send me/attach here one of GSI files with cross-channel covariances? Preferably one with most channels, and already reconditioned.

**Comment by KristenBathmann-NOAA** [comment]
I will send you a file.
