### ISSUE TITLE
Add suffix to AMVs filename in bufr2ioda converter => add BUFR version instead

### ISSUE THREAD

**Issue by ilianagenkova** [JCSDA-internal/ioda-converters#587]
The bufr2ioda AMVs converter uses CLATH mnemonic to recognize if it's reading from **old** or **new** BUFR format/sequence. We need to add a suffix to the output file name to preserve the information about the original BUFR file (old or new table).

**Old** (a.k.a **heritage** BUFR format) refers to using  BUFR sequence 3-10-014 in Table D. 
**New** (introduced with the start of GOES-R AMV products) refers to using  BUFR sequence 3-10-077 in Table D.   

Note: sequence 3-10-067 was used as intermediate while sequence 3-10-077 was finalized. 

Going forward, we will be using suffixes "014" (for old) and "077" (for new) in the filenames produced by the ioda converters.

**Winds using sequence 3-10-014**
GOES-13 and GOES-15 AMVs (and prior GOES)
AVHRR AMVs from NOAA-15..19 instruments
MODIS AMVs
VIIRS AMVs from S-NPP before 5 Dec 2018 (DATE to be verified)
EUMETSAT AMVs (from any instrument) before 2 Feb 2021  (DATE to be verified)
MTSAT and Himawari AMVs 

**Winds using sequence 3-10-077**
GOES-16 and GOES-17 AMVs (and future GOES)
VIIRS from S-NPP after 5 Dec 2018 (DATE to be verified)
VIIRS from NOAA-20
EUMETSAT AMVs  (from any instrument) after 2 Feb 2021  (DATE to be verified)

run_satwind.py code is updated to accommodate the needed suffixes.

**Comment by ilianagenkova** [comment]
A very brief intro to 3-10-014 and 3-10-077 :
https://www.nco.ncep.noaa.gov/sib/jeff/TableD_0_STDv31_LOC7.html (i.e. search for  3-10-014)

For the meaning of a sequence number, i.e. x-xx-xxx, see:
https://rda.ucar.edu/docs/formats/bufr/WMO306_vI2_BUFR_TableD_en.pdf

Brief doc on BUFR:
https://www.eumetnet.eu/wp-content/uploads/2017/04/OPERA_BUFR_template_primer_V1.4.pdf
or 
http://dss.ucar.edu/docs/formats/bufr/bufr.pdf
Detailed BUFR doc from WMO:
http://meteo.ieec.uned.es:8086/PFC_JMEstepa/documentos/BUFR/layer3.pdf

**Comment by rmclaren** [comment]
This issue may become irrelevant when I introduce the new syntax to query the BUFR file. You will be able to specify queries like this **[\*/CLATH, \*/CLAT]** (basically picks the first query that is valid).

**Comment by ilianagenkova** [comment]
A decision was made to not add suffix name to the ioda file.
Instead, the proper BUFR sequence version, i.e. 310014 and 310077,  is added as a global attribute to the ioda output NetCDF file. This will allow the UFO filters to read in and use the vriable's content for quality control decisions. 

Reading the global attribute will be dealt with later.
