### ISSUE TITLE
Sonde data QC filters 

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#599]
## Description
The purpose of the issue is to:
- Review the UFO Sonde data QC yaml file:
https://github.com/JCSDA-internal/ufo/blob/develop/test/testinput/instrumentTests/Sonde/sonde_gfs_qc.yaml
- Extract the QC filters information 
- Create a PPT flow diagram

## Requirements
No requirement.

## Dependencies
No dependencies.

**Comment by huishao-r** [comment]
Close this issue. Please resume this if this is still valid.

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA  is this still relevant or subsumed by a more recent issue

**Comment by PraveenKumar-NOAA** [comment]
This is still relevant and coming to this one soon. This will be the next step once we finish writing yamls for the sonde data, combined with the progress of _bufr2ioda.x_ and QC procedures in the  Obsproc codes.

**Comment by PraveenKumar-NOAA** [comment]
@huishao-r I am dealing with this in a similar issue https://github.com/NOAA-EMC/JEDI-T2O/issues/41

**Comment by PraveenKumar-NOAA** [comment]
I am closing this issue, as I am working on this within https://github.com/NOAA-EMC/JEDI-T2O.
