### ISSUE TITLE
[Bug?] ioda-v2 conversion of avhrr sst data

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/ioda-converters#600]
## Current behavior (describe the bug)

I'm trying to convert the avhrr sst files to ioda-v2 on discover, these are very large files I put one example in the following drive, while trying to convert them to ioda-v2, I get the "Bus error (core dumped)" error.  any ideas? 

https://drive.google.com/drive/folders/1mlT3L-STm5v9u3Q2J0N-9FghV4LHlFie?usp=sharing
"
$bin_path/ioda-upgrade.x /discover/nobackup/projects/jcsda/s2127/hebrahi1/data/data/ioda_data/smap/obs/radiance.rss/nc4//20201201/sst_avhrr_20201201.nc test.nc
Input: /discover/nobackup/projects/jcsda/s2127/hebrahi1/data/data/ioda_data/smap/obs/radiance.rss/nc4//20201201/sst_avhrr_20201201.nc
Output: test.nc
 Unique variable: MetaData/datetime.
 Unique variable: MetaData/latitude.
 Unique variable: MetaData/longitude.
 Unique variable: MetaData/time.
 Unique variable: ObsError/sea_surface_skin_temperature.
 Unique variable: ObsError/sea_surface_temperature.
 Unique variable: ObsValue/sea_surface_skin_temperature.
 Unique variable: ObsValue/sea_surface_temperature.
 Unique variable: PreQC/sea_surface_skin_temperature.
 Unique variable: PreQC/sea_surface_temperature.
 Unique variable: VarMetaData/variable_names.
 Converting old-format string variable: MetaData/datetime
 Converting old-format string variable: VarMetaData/variable_names

 Copying data:
  MetaData/datetime
Bus error (core dumped)
"

**Comment by srherbener** [comment]
@HamidehGMAO, it looks like the upgrader is hitting a memory limit of some kind. When I ran the upgrader on my iMac, it crashed (but with different messages). I used the NCO tool ncks to cut the file in half and I successfully converted it with the upgrader.

```
ncks -4 --dmn nlocs,0,59999999 sst_avhrr_20201201.nc sst_avhrr_20201201_60M.nc
```

As a workaround, I think you could split the file in half, convert the two halves and then join the two converted halves back together (using NCO ncrcat tool).

**Comment by HamidehGMAO** [comment]
Thanks @srherbener for looking into this. Yeah, I will do that. Thanks
