### ISSUE TITLE
Add site ID to the GHCN IODA files.

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [JCSDA-internal/ioda-converters#601]
## Description

In ghcn_snod2ioda.py, the ID column (character variable) in the input GHCN csv file is not being read in. 
The site variable (integer) in the output file in the IODA file is all zeros. 

There are some duplicate observations in the GCHN files, so it would be useful to have the IDs read in, then included in the GHCN IODA output file as the ID, so that we can apply a duplicate QC filter.

## Requirements

>If this is a new feature: What does the new code need to accomplish? Does it require new software dependencies (e.g. new jedi-stack components or new python modules?)

Adds site ID to output files. No new software.

>If this is a bugfix: What is the expected behavior?

## Acceptance Criteria (Definition of Done)
>What does it mean for this to be finished?

ID included in GHCN IODA file so that duplicate QC filter can be applied.

## Dependencies
>What must be done before this can be done? Add issue dependencies in ZenHub as appropriate
>Does this block progress on other issues? Add this issue as a dependency to other ZenHub issues as appropriate

No dependencies.

**Comment by YoulongXia-NOAA** [comment]
I did not find name  of site ID  in Greg Thomson's excel file. Can we use siteIdentification, stationIdentification, siteNumber,  stationNumber, siteID, or something else? @gthompsnJCSDA , do you have any suggestions for site ID?

**Comment by YoulongXia-NOAA** [comment]
I know that it should belong to metaData. Just suggest a name and then I can start to work on this assignment.

**Comment by ClaraDraper-NOAA** [comment]
Thanks @YoulongXia-NOAA . I just had a look at the QC code, and it looks like the variable that we store the site ID (or whatever you decide to call it) needs to be an integer variable.

**Comment by YoulongXia-NOAA** [comment]
I will wait for Greg's suggestion. Otherwise, I will may use siteID instead.

**Comment by YoulongXia-NOAA** [comment]
We have OBS3 meeting today with Greg and he suggested just use stationIdentification right now. If there are a more appropriate name for site ID or station ID in future, I can change as suggested.

**Comment by gthompsnJCSDA** [comment]
For the record, I strongly advise that ```stationIdentification``` be a string variable (which we could enforce a maximum length of perhaps 16 chars) and not an integer.  This is because nearly all station identifiers I know about except 5-digit WMO numbers are combinations of letters and numbers.  If someone has data that are always integer numbers for station ID, then they can easily "cast" the string into an integer whereas other persons with mixed alpha/numbers could not force their content into an integer.

**Comment by YoulongXia-NOAA** [comment]
The GHCN site/station ID is alike AM000037682 or ALM00013615, can I used this string directly @gthompsnJCSDA ?

**Comment by YoulongXia-NOAA** [comment]
This is a good suggestion as it fits to both integer ID and (letters+integer) ID. I completely agree with your suggestion here.

**Comment by ClaraDraper-NOAA** [comment]
@gthompsnJCSDA - I agree that characters make sense (since this is how stations are typically labeled). However, the temporal thinning filter (which we would use to discard obs. when there is more than one obs per station) requires an integer as the category_variable which we would use to associate the obs with a given station:

https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/ufo/qcfilters/GenericQC.html#temporal-thinning-filter

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA - I agree that characters make sense (since this is how stations are typically labeled). However, the temporal thinning filter (which we would use to discard obs. when there is more than one obs per station) requires an integer as the category_variable which we would use to associate the obs with a given station:
> 
> https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/ufo/qcfilters/GenericQC.html#temporal-thinning-filter


Well what if the string shown in the comment a few items ago is not always unique with the integer value of station?  Someone just has to map from alpha-numeric to integer.  I would expect a filter with name "temporal thinning" is doing something with regard to time, not station ID.  There are tons of data sets that don't have integer representation of station info, so it sounds more like a change needed on the data type in the filter to me.

**Comment by ClaraDraper-NOAA** [comment]
Greg - I'm inclined to agree with you that the filter should be changed (since this will keep coming up). 

The temporal filter filters the obs by time within each station - hence the need for a station ID. Let me check in with the UFO team - perhaps there's a better way to do it.

**Comment by ClaraDraper-NOAA** [comment]
I just heard back from Ryan. The documentation is out of date, and the stationIdentification (or whatever you want to call the variable) MetaData used by the QC is no longer restricted to integer, and it can be a character variable. 

@YoulongXia-NOAA Do you need anything else, or is it clear now what needs to be done?

**Comment by YoulongXia-NOAA** [comment]
@tsga As you knew from this issue Clara wrote, I need to keep all duplicate stations and also add station ID to ioda v2 output.  Based on my understanding,  I need to remove the sentence df10 = df10.drop_duplicates(subset=["ID"]) in https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/land/ghcn_snod2ioda.py. Please let me know if my understanding is correct. Thank you.

**Comment by tsga** [comment]
@YoulongXia-NOAA, yes that is true.

**Comment by ClaraDraper-NOAA** [comment]
@tsga, @YoulongXia-NOAA : I'm going to schedule a quick meeting about this. I hadn't realized that we're already screening out duplicates. There are some remaining duplicates (based on same lat and lon), but now I'm wondering if these are actually different stations, as I've noticed some and them have different elevations.

**Comment by YoulongXia-NOAA** [comment]
Now my ioda v2 output for 20191215 is ghcn_snod2ioda_20191215.nc in /scratch2/NCEPDEV/stmp3/Youlong.Xia/GHCN/NewTest. I have built my own ioda-bundle, and compared the output with use of ioda-bundle built by Cory Martin and they are identical. Now Module_env_setup  uses my built library.  See the instructions in README.md of the same directory.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA It looks like the snow depth variable has a new name in this file. I tried changing the input observations name in the yaml, but then it crashed with an error related to the variables. 

@jiaruidong2017 Did you mention yesterday that you did some work so that you can read in observations with different variable names? Do you know what I need to do?

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, I did not change variable name since I used "snowDepth" Greg suggested a while ago. See the name is snowDepth -  https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/land/ghcn_snod2ioda.py.  I used ncdump -h to check my nc file, its name is snowDepth. What the name for snow depth did you used before?

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA it's called snwdph in the file in the fv3-jedi test case. Could this be an IODAv1 IODAv2 format difference?

**Comment by YoulongXia-NOAA** [comment]
This is the name Tsega used as I never used such a name.  @tsga, is it right? This may need either Jiarui or Tsega's help as I did not touch that part yet @tsga @jiaruidong2017

**Comment by tsga** [comment]
Yes that is true @YoulongXia-NOAA. It's has been a while since I run anything JEDI but that variable name was used for snow depth.

**Comment by ClaraDraper-NOAA** [comment]
I think @jiaruidong2017 has a solution for this. I'll email him.

**Comment by ClaraDraper-NOAA** [comment]
Jiarui is sending me his yaml, which can assimilate obs with the new name. Once I've tested it, I'll update the test case in fv3-jedi to use the new format. It will take me a few days though.

**Comment by YoulongXia-NOAA** [comment]
This is what we should work together. I will closely touch with Greg and ioda-converter development team and try to use standard name as requested, and Jiarui and you can modify your yaml file to use the output data from my converters. Furthermore, you can provide any requests/issues to me including to add/modify additional variables/data and then I will help to to do that. I am feeling that we have some disconnection in previous works.
