### ISSUE TITLE
Change date_time attribute in GHCN file to 18

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [JCSDA-internal/ioda-converters#603]
## Description

The GHCN observations are daily aggregates, and are assimilated at 18 UTC each time to match the timing of the IMS snow cover observations. The IODA files are currently time-stamped at 12, and this needs to be changed to 18.

## Requirements

No dependencies, etc.

## Acceptance Criteria (Definition of Done)

date_time attribute in GHCN ioda files is at 18 UTC each day, rather than 12 UTC.

## Dependencies

This is just a one line change in ghcn_snod2ioda.py (with test output updated too).

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA Would you mind doing this while you're adding the site identification? I started doing it, but then figured it'd be much easier for you to do it, rather than my having to familiarize myself with the ioda-converters. 

In ghcn_snod2ioda.py, we just need to change line 209 to: 
base_datetime = start_datetime + 'T18:00:00Z'

**Comment by YoulongXia-NOAA** [comment]
Yes, I can modify it.

**Comment by ClaraDraper-NOAA** [comment]
Thanks! (this is not particularly urgent).

**Comment by YoulongXia-NOAA** [comment]
My newly developed python code is ghcn_snod2ioda_newV2.py in /scratch2/NCEPDEV/stmp3/Youlong.Xia/GHCN/NewTest. Please see README.md update there. You will not need to use ioda-upgrade.x to convert ioda v1 file to ioda v2 file as the python code can output v2 format directly. Although Cory Martin just developed lib-v2 feature branch and I have tested it. Additionally I compare the plot results using my new output with those when the converted v2 nc file is used. The results are the same as code still keep in removing duplicate stations for comparison. Please tested it and let me know. I will test the code when sentence df10 = df10.drop_duplicates(subset=["ID"]) is dropped off and keep these duplicate stations soon.

**Comment by ClaraDraper-NOAA** [comment]
Thanks Youlong. I can have a look on Monday. Can you please point me to an example output file, generated with the new code?

**Comment by YoulongXia-NOAA** [comment]
NEWoutputv1.nc is ioda v1 format, and NEWoutputv2.nc format. Please check when your time is available.

**Comment by YoulongXia-NOAA** [comment]
NEWoutputv2.nc format is directly output ioda v2 NetCDF file. Your JEDI UFO can directly use it if there is no problem.

**Comment by ClaraDraper-NOAA** [comment]
> @YoulongXia-NOAA. Jiarui's pull request has been accepted, and the fv3-bundle letkf_snow test case now uses the correct IODAv2 format file. Now you can submit a PR updating the date_time attribute to 18. Please let me know when you've done that, and then @jiaruidong2017 or I can update the fv3-bundle test case.

@YoulongXia-NOAA @jiaruidong2017 I just realised that Jiarui's PR did not in fact update the fv3-bundle to use the IODA file. Instead, it just changed the variable name in the old file. @YoulongXia-NOAA If you can send me the latest version of the file, I'll update it now. Then we can also address and close this issue.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA , the UTC18 nc file is ghcn_snod2iodaV2_20191215UTC18.nc in /scratch2/NCEPDEV/stmp3/Youlong.Xia/GHCN/NewTest on Hera. Please make your test and let me know if this is what you need.

**Comment by ClaraDraper-NOAA** [comment]
Thanks @YoulongXia-NOAA! I'll start on it now.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA @jiaruidong2017. I was wrong - the file in the jedi repo is the new (IODAv2) file. I was confused as it has the same name as the old file. I'm still confused though, as the unit for snow depth is given as m, and the obs error is given as 40 m! @jiaruidong2017 -  I also don't understand how this could have passed the assimilation test. I'll compare the new and old now, and perhaps we can sort this out at our meeting on Monday.

**Comment by ClaraDraper-NOAA** [comment]
I figured it out. The data in the file are in mm, but the meta data has "string totalSnowDepth:units = "m" ;". I thought JEDI might be smart enough to ingest the unit. I'll create a separate issue to correct this.
