### ISSUE TITLE
[Bug] on build with iod-converter

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA-internal/ioda-converters#613]
@HamidehGMAO commented on [Thu Sep 02 2021](https://github.com/JCSDA-internal/soca-science/issues/346)

## Current behavior (describe the bug)

I seem to have issue building the bundle with ioda-converter. I get the following error. it builds fine with commenting the ioda-converter build line in the CMakeList.
"
-- Configuring done
CMake Error at /gpfsm/dswdev/jcsda/modules/core/ecbuild/ecmwf-3.6.1/share/ecbuild/cmake/ecbuild_add_test.cmake:438 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE_DIR:_ioda_python>

  No target "_ioda_python"
Call Stack (most recent call first):
  ioda-converters/test/CMakeLists.txt:560 (ecbuild_add_test)

"

---

@guillaumevernieres commented on [Thu Sep 02 2021](https://github.com/JCSDA-internal/soca-science/issues/346#issuecomment-911639072)

@HamidehGMAO , try that option `-DBUILD_PYTHON_BINDINGS=ON`, if that fails and you don't need the ioda-converters, just comment it out in the cmakelist. 

---

@HamidehGMAO commented on [Thu Sep 02 2021](https://github.com/JCSDA-internal/soca-science/issues/346#issuecomment-911648565)

@guillaumevernieres OK, I will try it. Thanks

---

@HamidehGMAO commented on [Thu Sep 02 2021](https://github.com/JCSDA-internal/soca-science/issues/346#issuecomment-911733445)

Thanks @guillaumevernieres. It worked adding the -DBUILD_PYTHON_BINDINGS=ON option. I'll modify the wiki for SOCA-GEOS

---

@shlyaeva commented on [Thu Sep 02 2021](https://github.com/JCSDA-internal/soca-science/issues/346#issuecomment-911780187)

I've been seeing this issue on mac too. I'm going to reopen and move this issue to ioda-converters to open a discussion on whether we can avoid adding extra options in ecbuild, and still have ioda-converters build.

**Comment by srherbener** [comment]
Thanks for reporting this. I'm working on a fix for this. Ioda converters depend on ioda now, so when BUILD_IODA_CONVERTERS is enabled, the BUILD_PYTHON_BINDINGS also needs to be set. Therefore the fix is to automatically set BUILD_PYTHON_BINDINGS when BUILD_IODA_CONVERTERS is used (so the user doesn't have to remember to do this).

**Comment by shlyaeva** [comment]
Thank you @srherbener !

**Comment by guillaumevernieres** [comment]
Thanks @srherbener !
