### ISSUE TITLE
Modifiy GOES-16/17 Converter to Utilize the IODA Python API

### ISSUE THREAD

**Issue by ericlingerfelt** [JCSDA-internal/ioda-converters#626]
## Description

This issue addresses the need to modify the GOES_16/17 IODA converter to utilize the IODA python API instead of numpy and netCDF4 directly.

## Acceptance Criteria (Definition of Done)

This issue is completed when the IODA python API is utilized for converting GOES-16/17 data files into the IODA data format.

**Comment by srherbener** [comment]
I don't think the work for this has been done yet. Is that correct? If so, are there plans in AOP 22 for this? Thanks!

**Comment by ericlingerfelt** [comment]
Hi @srherbener, this work has not been done yet.

**Comment by srherbener** [comment]
Should we keep this open (for AOP 22) or is this going to be covered in another issue/epic in AOP 22? Thanks!
