### ISSUE TITLE
[New issue]

### ISSUE THREAD

**Issue by andytangborn** [JCSDA-internal/ioda-converters#627]
## Description

Develop the capability to use the recent updates to BUMP in aerosol assimilation. This includes the yaml files: staticb_vbal_gfs.yaml, staticb_var_gfs.yaml, staticb_cor_gfs.yaml and any others that these depend on.  It's not yet clear if new yaml files are needed, or if these can be used directly by just changing the input files and state variables to the aerosol species. 
>Provide a detailed description of this issue.
>What problem needs to be fixed? What new capability needs to be added?
>If this is a bug, describe the current behavior (or use the bug template).
>[Be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Requirements

This will require changes to existing yaml files to load in aerosol fields, with the existing (and perhaps new) yaml files, including staticb_vbal_gfs.yaml, staticb_var_gfs.yaml, staticb_cor_gfs.yaml, and possibly staticb_ens-to-psichi_*, staticb_vbal_* and staticb_ens-to-psichi_*.  It is possible that the aerosols can follow the same route through these files as RH, but this is not yet clear. 

## Acceptance Criteria (Definition of Done)

AOD assimilation is done using this latest BUMP static B matrix, and (if necessary) a pull request for new yaml files has been merged. 

## Dependencies

Testing of the existing yaml files with aerosols, then determine whether they are sufficient or if new yaml files are needed.

**Comment by CoryMartin-NOAA** [comment]
@andytangborn this probably shouldn't be in ioda-converters repository, perhaps it should be in jcsda-internal/saber?

**Comment by andytangborn** [comment]
You're right. I'll move it.

**Comment by andytangborn** [comment]
Moving this to SABER
