### ISSUE TITLE
Development of processed imsFV3 snow cover and total snow depth ioda v2 converter

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#629]
## Description
Work on development of the processed imsFV3 snow cover and total snow depth  ioda V2 converter in support of PSL GEFS ensemble snow DA task when ascii 4km ims now cover data are used.  This needs to use ioda module and ioda engine module to develop the new converter using the example file produced by PSL scientists. 

## Requirements

New python code needs to be developed. The new JEDI-stack ioda and ioda engine module are required.

## Acceptance Criteria (Definition of Done)
The ioda-bundle c test need to be passed for upgrade.

## Dependencies
New ioda V2 python converter instructions are needed to be followed from ioda-converter team.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA I've created new input files that include an "oro" variable. Can you please update the converter to: 
1. include altitude in the Metadata (like in the GHCN files), using the oro values as the altitude. 
2. change the observation error to 80 mm. 

Thanks!

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, C48 and C768 have been produced as  imsFV3_iodav2_C48.nc and imsFV3_iodav2_C768.nc in /scratch2/NCEPDEV/stmp3/Youlong.Xia/Converter_dev/IMSfsc on Hera. A plot check is https://docs.google.com/presentation/d/1K5f4vuxUy8ix_Wf97ZPKrmJ5sB76ozbV/edit?usp=sharing&ouid=113857655975465624380&rtpof=true&sd=true. When snow cover fraction is 1.0, snow depth is -999.0. I am not sure if this is what you want to set up. For snow cover fraction and altitude, they look reasonable as expected. Please let me know your thoughts.

**Comment by ClaraDraper-NOAA** [comment]
Thanks @YoulongXia-NOAA! 

I set the snow depth to -999.0 if both IMS and the model indicate 100% snow cover (so I would expect to see some examples of IMS having 100% snow cover and positive snow depth). Later today I will try to assimilate your files, and let you know how it goes.

**Comment by YoulongXia-NOAA** [comment]
Thank you @ClaraDraper-NOAA. Now understood for data set up. I recalled that Noah code uses the snup (maximum SWE values depending on vegetation type) to calculate SWE and snow cover fraction. Tsega used that equation to drop off the second term to inversely convert snow cover fraction into SWE, and then you use GFS snow density to convert SWE into total snow depth. It should have the values when snow cover fraction is 1.0.   This is the reason I am puzzling. It is clear now. Just let me know if you have any new requests.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA I've assimilated the files you created, and had a quick look at the output. Everything looks OK so far.

**Comment by YoulongXia-NOAA** [comment]
Great @ClaraDraper-NOAA.  Thank you.
