### ISSUE TITLE
Development of Python script for plot bufr data directly using bufr python libs

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#631]
## Description

The purpose is to develop several python script examples on Hera to plot global bufr dump data directly when either py-ncepbufr (https://github.com/JCSDA-internal/py-ncepbufr) or NCEPLIBS-bufr (https://github.com/NOAA-EMC/NCEPLIBS-bufr) python is used.  It can be used to check the outputted ioda-v2 NETCDF data via the data plots.  

## Requirements

The Python scripts can plot global bufr dump and Prebufr files directly and produce the correct results as expected. 

## Acceptance Criteria (Definition of Done)

Checked and worked

## Dependencies
No

**Comment by huishao-r** [comment]
@YoulongXia-NOAA is this one still valid? We plan to close issues if they are not active. Please let us know.

**Comment by YoulongXia-NOAA** [comment]
@huishao-r , please close this issue as it has been completed. Thank you.
