### ISSUE TITLE
[Bug] test_iodaconv_smos_ssm fails on discover

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/ioda-converters#657]
## Current behavior (describe the bug)
test_iodaconv_smos_ssm fails on discover with the following modules:

"
Currently Loaded Modules:
  1) git/2.30.2
  2) git-lfs/2.10.0
  3) jedi-python/3.8.3
  4) comp/gcc/9.2.0
  5) comp/intel/19.1.0.166
  6) jedi-intel/19.1.0.166
  7) szip/2.1.1
  8) zlib/1.2.11
  9) udunits/2.2.26
 10) mpi/impi/19.1.0.166
 11) jedi-impi/19.1.0.166
 12) hdf5/1.12.0
 13) pnetcdf/1.12.1
 14) netcdf/4.7.4
 15) nccmp/1.8.7.0
 16) boost-headers/1.68.0
 17) eigen/3.3.7
 18) bufr/noaa-emc-11.5.0
 19) cmake/3.21.0
 20) ecbuild/ecmwf-3.6.1
 21) eckit/ecmwf-1.16.0
 22) fckit/ecmwf-0.9.2
 23) atlas/ecmwf-0.24.1
 24) nco/4.9.9
 25) pio/2.5.1-debug
 26) gsl_lite/0.37.0
 27) gptl/8.0.3
 28) pybind11/2.7.0
 29) jedi/intel-impi/ecbuild35

"
test 70
    Start 70: test_iodaconv_smos_ssm

70: Test command: /discover/nobackup/projects/jcsda/s2127/hebrahi1/experiments/2020/soca_crtm/build.intel/bin/iodaconv_comp.sh "netcdf" "/discover/nobackup/projects/jcsda/s2127/hebrahi1/experiments/2020/soca_crtm/build.intel/bin/smos_ssm2ioda.py
                            -i testinput/smos_l2nrt_ssm.nc
                            -o testrun/smos_ssm.nc
                            -m maskout" "smos_ssm.nc" "0.0"
70: Environment variables: 
70:  OMP_NUM_THREADS=1
70: Test timeout computed to be: 10000000
70: ERROR: Unrecognized numpy data type:  >f8
1/1 Test #70: test_iodaconv_smos_ssm ...........***Failed    0.37 sec

**Comment by rhoneyager** [comment]
Closing since the new spack-based stack should resolve.
