### ISSUE TITLE
Add Dilution of Precision DOPX DOPY into HF radar as pre-procesing quality flag

### ISSUE THREAD

**Issue by lliu1220** [JCSDA-internal/ioda-converters#691]
## Description

An Issue to address new PR:
https://github.com/JCSDA-internal/ioda-converters/pull/680

## Requirements

DOPY DOPX value flag theory table:

<1 | Ideal | Highest possible confidence level to be used for applications demanding the highest possible precision at all times.
1-2 | Excellent | At this confidence level, positional measurements are considered accurate enough to meet all but the most sensitive applications.
2-5 | Good | Represents a level that marks the minimum appropriate for making accurate decisions. Positional measurements could be used to make reliable in-route navigation suggestions to the user.
5-10 | Moderate | Positional measurements could be used for calculations, but the fix quality could still be improved. A more open view of the sky is recommended.
10-20 | Fair | Represents a low confidence level. Positional measurements should be discarded or used only to indicate a very rough estimate of the current location.
>20 | Poor | At this level, measurements are inaccurate by as much as 300 meters with a 6-meter accurate device (50 DOP × 6 meters) and should be discarded.

## Acceptance Criteria (Definition of Done)
quality flag show qc ==11 in PreQC group of NetCDF4 output from Version 2 upgrade

## Dependencies
Upgrade Python converter for (ndbc_hfradar2ioda.py) to IODA-v2
https://github.com/JCSDA-internal/ioda-converters/pull/680

**Comment by BenjaminRuston** [comment]
@lliu1220 this putting into backlog, meaning not being worked on at the moment but in the next 2-6 week

**Comment by lliu1220** [comment]
@BenjaminRuston 
sorry about this- I should have closed it, the PR already merged: https://github.com/JCSDA-internal/ioda-converters/pull/680
