### ISSUE TITLE
Add 3D thinning algorithm to high-res marine glider V2 converter

### ISSUE THREAD

**Issue by lliu1220** [JCSDA-internal/ioda-converters#707]
## Description

This issue is to add a 3D thinning box with any given resolution, e.g., 1 degree horizontal, 1 meter vertical to the upgraded version 2 marine glider converter

## Requirements

This issue is building upon Version 2 high-res marine glider converter 
https://github.com/JCSDA-internal/ioda-converters/pull/679

## Acceptance Criteria (Definition of Done)
success of compile ioda-bundle
success of passing ctest

**Comment by BenjaminRuston** [comment]
@lliu1220 closing as this looks to be completed.  Please re-open if this is incorrect.
