### ISSUE TITLE
New converter for SMAP level 2 9 km soil moisture retrievals

### ISSUE THREAD

**Issue by ClaraDraper-NOAA** [JCSDA-internal/ioda-converters#710]
## Description

Currently we have a SMAP soil moisture converter for the NRT SMAP retrievals only. These are retrieved at 36 km, and are of slightly lower quality than the standard (non-NRT) retrievals.  For initial experiments assimilating SMAP soil moisture retrievals, the standard level 2 retrievals are necessary. The best option is the enhanced product: 

https://nsidc.org/data/SPL2SMP_E/versions/5

These have higher resolution (9 km), better data quality, and are the same as used by the LIS team, allowing coordinated experiments. 

## Requirements

A new converter for the SMAP soil moisture retrieval files linked above. The input variables to include in the IODA file are: 

soil_moisture_option3 
vegetation_opacity_option3

retrieval_quality_flag_option3
surface_flag

These are all for the dual channel algorithm (option 3). Note that the default fields link to option 3 within the file - so soil_moisture links to soil_moisture_option3. 

The last two variables are 16 bit binary strings. If we're not yet able to read in and operate on binary fields from IODA file, we could decide on the flags to use now, and simply use these to screen out data now.

## Acceptance Criteria (Definition of Done)

IODA converter for SMAP level 2 9 km enhanced product. 

## Dependencies
None.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, To not block my work progress, could you please help me to download several example data files (SMAP L2 9km) to hera? I can download it and shared with you in google drive, my government laptop has MacAfee access issue, so I used my home desktop.  But the WinSCP does not work for Hera. Thank you.





















/











/

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA It's here: /scratch2/BMC/gsienkf/Clara.Draper/forYoulong/

**Comment by YoulongXia-NOAA** [comment]
That is great. Thanks a lot @ClaraDraper-NOAA

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, double check the below sentence:
DATASET "retrieval_qual_flag_option3" {
         HARDLINK "/Soil_Moisture_Retrieval_Data/retrieval_qual_flag"
      }
I understand that I can use Soil_Moisture_Retrieval_Data/retrieval_qual_flag to retrieve option3 data, right?

**Comment by YoulongXia-NOAA** [comment]
Additionally,  there are groups: Soil_Moisture_Retrieval_Data and Soil_Moisture_Retrieval_Data_Polar where both include the variables described above. Which one do you want for my converter development?

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA Yes to the first question ( I didn't know that you could link variables inside a hd5, it's kinda clever). Let me look into the second, but I think it's the one without "_Polar".

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA Yes, we want the one without "_Polar". The "_Polar" option is the full northern hemisphere, while the other one is (very close to) global.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA Great. Let me work an offline version to produce the iodaV2 mc output first, and then either you or Zifa  can do the preliminary test to decide if it can be further modified. When you are satisficed,  I can test it on ioda-bundle and to provide a PR to request merging.

**Comment by YoulongXia-NOAA** [comment]
@gthompsnJCSDA, as described above, I am working for this new ioda-converter. Two meta variable names cannot find in your document. They are surface flag and vegetation opacity. Here I just use surfaceFlag and vegetationOpacity, if you agree, please add them to your document. If not, please give me your suggestions so that I can replace mines. Thank you.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA , soil moisture observed error is constant with a value of -9999. for whole domain. What value do you me to put or set it as 0? Any suggestions from you?

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA , A first test output data  produced by my converter is smap9km_ssm.nc in /scratch2/NCEPDEV/stmp3/Youlong.Xia/Converter_dev/smap9km and its ncdump output is OUTPUT. Please take a look for various variables and see if this what you want. I can make a further modification based your suggestions.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA Thanks. I'll try to look at it tomorrow. For the soil moisture observation errors, let's use 0.04 m3/m3 for now.

**Comment by BenjaminRuston** [comment]
@amfox37 was this ever completed?  can we close, please do so if that's the case.

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, please do not close. This ioda converter is being tested by the user and not merged into the develop branch. I am waiting for the users' feedback.

**Comment by ClaraDraper-NOAA** [comment]
@YoulongXia-NOAA. Thanks for working on this. We're using the converter as is, and I think it's ready to be merged into the develop branch.

**Comment by YoulongXia-NOAA** [comment]
@ClaraDraper-NOAA, Okay. Understood. I will test within the ioda-bundle framework and create a pull request soon. Thank you.

**Comment by ClaraDraper-NOAA** [comment]
Thanks Youlong!
