### ISSUE TITLE
create script for ATMS data pull from NASA repository

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#720]
## Description
add a script which uses the NASA servers to get NRT or archived ATMS data

## Requirements

This will allow system to ingest ATMS and will have an accompanying converter to turn these files into IODA2

## Acceptance Criteria (Definition of Done)
script can run on multiple machines and populate ATMS data

**Comment by srherbener** [comment]
Closing this issue since its associated PR was merged into develop.
