### ISSUE TITLE
bufr2ioda processing the yaml file for bufr_read_2_dim_blocks.nc

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#728]
## Current behavior (describe the bug)
bufr2ioda.x  is able to process "*/QCPRMS/GNAP[1]" and "*/QCPRMS/PCCF[1]" but it cannot process "*/QCPRMS/GNAP[1]" and "*/QCPRMS/PCCF[1]"  due to PRE-MAIN-ERROR Exception: Serious Bug: Invalid sequence. If I set up them as:
query: "[*/QCPRMS/GNAP[1], */QCPRMS/GNAP[2], */QCPRMS/GNAP[3], */QCPRMS/GNAP[4]]"
          percent_confidence:
            query: "[*/QCPRMS/PCCF[1], */QCPRMS/PCCF[2], */QCPRMS/PCCF[3], */QCPRMS/PCCF[4]]"
It only read the first three columns. The original NC output (v1 format) in testoutput within ioda-bundle has 12 columns (each variable has 3 columns, and 4 variables have 12 columns).  This task is an upgrade work for ioda-bundle burfr data.  

## Requirements

output needs to be validated by comparing with the testoutput within ioda-bundle, run ctest and update yaml and output data.

## Acceptance Criteria (Definition of Done)
Pass ctest 

## Dependencies
bufr2ioda.x development and upgrade

**Comment by ilianagenkova** [comment]
@YoulongXia-NOAA , I will have to reach out to JCSDA to fix my profile. Others couldn't not add me to their PR and Issues either.  You could tag me in the comments when you want me to see something.

**Comment by YoulongXia-NOAA** [comment]
5 test yaml files are in /scratch1/NCEPDEV/da/Youlong.Xia/test/test_fromRon on Hera, but only Test3_bufr_read_2_dim_blocks.yaml works.

**Comment by YoulongXia-NOAA** [comment]
Okay, @ilianagenkova , take your time.

**Comment by YoulongXia-NOAA** [comment]
As Ron indicated to Iliana and me, this is due to the indentation issue in yaml file.  After the indentation is fixed, the yaml file works now and all 5 tests produced the results. Iliana and I will check the results and see if they are correct.

**Comment by huishao-r** [comment]
@YoulongXia-NOAA It seems this issue is complete. I am going to close this issue. Please resume this if it is active.

**Comment by YoulongXia-NOAA** [comment]
@huishao-r , this issue has been solved. Please close it. Thank you.
