### ISSUE TITLE
add a converter for avhrr radiance data (patmosx)

### ISSUE THREAD

**Issue by HamidehGMAO** [JCSDA-internal/ioda-converters#730]
## Description

we add a ioda-converter to convert the AVHRR radiance data to ioda-v2 fprmat. there are several sources of data for AVHRR, this converter is for patmosx data in nc format "https://www.ncei.noaa.gov/data/avhrr-hirs-reflectance-and-cloud-properties-patmosx/access/"

**Comment by huishao-r** [comment]
@HamidehGMAO Is the PR in already. I'll close this. Please resume it if it is active.

**Comment by rhoneyager** [comment]
Closed by https://github.com/JCSDA-internal/ioda-converters/pull/731
