### ISSUE TITLE
Tropomi converter doesn't work properly for 2+ files at once

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [JCSDA-internal/ioda-converters#741]
## Current behavior (describe the bug)
```
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 217, in <module>
    main()
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 207, in main
    no2 = tropomi(args.input)
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 58, in __init__
    self._read()
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 151, in _read
    (self.loc_mdata[varname_ak], avg_kernel[..., k].ravel()))
AttributeError: 'tropomi' object has no attribute 'loc_mdata'
```

## To Reproduce

For example:
`tropomi_no2_nc2ioda.py -i S5P_OFFL_L2__NO2____20190801* -o test.nc`

## Expected behavior
Multiple files should concatenate together to one output file

## Additional information (optional)
Note if you specify only one input file, it works as intended.

**Comment by CoryMartin-NOAA** [comment]
I'm actually more worried about performance of 3DVar now with this updated file format, some full scale testing is suggesting it is taking 2+ hours to read in 6 hours worth of TROPOMI obs.

**Comment by jeromebarre** [comment]
This format is actually less computation than before in UFO...

**Comment by CoryMartin-NOAA** [comment]
@jeromebarre yes, I think the bottleneck is IO though. @srherbener @rhoneyager this might be something we need to take a closer look at.  Something that previously took an hour to run now is over 3 hours and the log file is at:
```
NO2 vars: 1 variables: nitrogen_dioxide_in_tropospheric_column
WARNING: string style datetime will cause performance degredation and will eventually be deprecated.
WARNING: Please update your datetime data to the epoch style representation using the new variable: MetaData/dateTime.
```

**Comment by jeromebarre** [comment]
How many observations are we talking about?

**Comment by CoryMartin-NOAA** [comment]
```
NO2 nitrogen_dioxide_in_tropospheric_column nlocs = 5633100, nobs = 5633100
```
For the record, it did complete, but it took a long time:
```
OOPS_STATS ------------------------------------------------------------------------------------------------------------------
OOPS_STATS ---------------------------------- Parallel Timing Statistics ( 264 MPI tasks) -----------------------------------
OOPS_STATS ------------------------------------------------------------------------------------------------------------------
OOPS_STATS Name                                                :     min (ms)    max (ms)    avg (ms)     % total   imbal (%)
OOPS_STATS fv3jedi::LinearGetValues::LinearGetValues           :     17688.00    23765.96    19543.54        0.16       31.10
OOPS_STATS oops::GetValues::GetValues                          :     25962.66    33935.28    28083.60        0.23       28.39
OOPS_STATS oops::LinearGetValues::LinearGetValues              :     17689.28    23767.29    19544.90        0.16       31.10
OOPS_STATS oops::LinearObsOperator::simulateObsTL              :     14696.59    15668.70    15049.87        0.12        6.46
OOPS_STATS oops::ObsSpace::ObsSpace                            :  12164866.77 12164974.99 12164921.66       98.96        0.00
OOPS_STATS util::Timers::Total                                 :  12292626.50 12293401.67 12293222.92      100.00        0.01
OOPS_STATS util::Timers::measured                              :  12259079.09 12300224.30 12278410.64       99.88        0.34
OOPS_STATS ---------------------------------- Parallel Timing Statistics ( 264 MPI tasks) -----------------------------------

OOPS_STATS Run end                                  - Runtime:  12297.62 sec,  Memory: total:   251.64 Gb, per task: min =   934.32 Mb, max
```
nearly 3.5 hours for this 3DVar exe

**Comment by jeromebarre** [comment]
and this is the data thinned/superobbed and selected within the lam model? seems high. but not sure.
Global models assimilating tropomi are supperobbing or thinking to reduce number of data point. If you use a regional model you will reduce your number of obs as well.

**Comment by jeromebarre** [comment]
but I agree there is a problem even 1 hours is not ok in my opinion. most of the time is spent in oops::ObsSpace::ObsSpace

**Comment by CoryMartin-NOAA** [comment]
@jeromebarre thinning is done (and obs outside of the domain are removed), but current thinning in IODA/UFO is not actual thinning, but just QC. All of the original points are still along for the ride all the way through. In GSI, we toss them out so that they aren't kept in memory. So all 5.6 million points are kept, even though:
```
QC NO2 nitrogen_dioxide_in_tropospheric_column: 921227 missing values.                                                                
QC NO2 nitrogen_dioxide_in_tropospheric_column: 1502630 out of bounds.                                                                
QC NO2 nitrogen_dioxide_in_tropospheric_column: 2957752 out of domain of use.                                                         
QC NO2 nitrogen_dioxide_in_tropospheric_column: 246965 removed by thinning.                                                           
QC NO2 nitrogen_dioxide_in_tropospheric_column: 4526 passed out of 5633100 observations.      
```

**Comment by jeromebarre** [comment]
"4526 passed out of 5633100 observations.", wonder that if you feed actually just those obs will it take still hours... part of the QC and thinning should be done at the converter stage for efficiency, in my opinion.

**Comment by jeromebarre** [comment]
> 

clearly there's something off here as it takes no more than 90secs to getvalues and simobs. All this time spent somewhere else Obsspace is indicating a bug. @rhoneyager @srherbener @huishao-r @BenjaminRuston any idea of the origin of this very long runtime?

@CoryMartin-NOAA would be good to have the full log and the executable to know exactly what you are doing. I suspect the QC on an overly large number of points. Still, I don't expect this to take 3.5 hours.

This is off topic here, we should move this to an issue if the problem persists.

**Comment by CoryMartin-NOAA** [comment]
@jeromebarre agreed this is probably a new issue that belongs in `ioda`. I'm not the one who is running the tests, but I created the YAML and added the code to the regional_workflow. It is about 2 hours longer with the averaging kernel variables added to the file. I wonder if we can do some timing tests in `ioda` as a function of number of input variables. I'll wait until Chan-hoo has been able to run several days worth of cycles and see if this ~3 hour wall clock time persists.

**Comment by jeromebarre** [comment]
I expect the same result to happen in several cycles if you keep passing a majority of data points to be tossed out... 0.08% seem to be actually used in the last test...  this points however a slowdown with the I/O as you pass a now larger data amount by specifying directly the vertical coordinates and not calculating them in UFO. This is mandatory as most of the L2 products for composition actually provide the data like this and not just the surface pressure and sigma alpha and beta coefficients...  Still, I don't understand why the runtime is multiplied by 3 (given what you said earlier) as we've just added another array  (nloc,nlev) in addition of the ak(nloc,nlev) and the other quantities like the column value and error that are (nloc). So the increase in data passed shouldn't be more than a factor 2.

**Comment by jeromebarre** [comment]
@CoryMartin-NOAA Once you have more test results I suggest you create a new issue on this runtime problem.
Thanks!

**Comment by jamiebresch** [comment]
The timing problem was also seen for MPAS https://github.com/JCSDA-internal/ioda/pull/525#issuecomment-973645463 , https://github.com/JCSDA-internal/ioda/pull/525#issuecomment-988128580

**Comment by srherbener** [comment]
> The timing problem was also seen for MPAS [JCSDA-internal/ioda#525 (comment)](https://github.com/JCSDA-internal/ioda/pull/525#issuecomment-973645463) , [JCSDA-internal/ioda#525 (comment)](https://github.com/JCSDA-internal/ioda/pull/525#issuecomment-988128580)

FYI, these issues with the ioda reader performance are not acceptable and must be addressed. We are kicking off an effort tomorrow (Friday 1/14/22) to work on resolving the ioda file io performance issues (as well as some other ioda issues). We can surely get this to run much much faster, but until we start to investigate it's hard to quantify the speedup we can achieve.

Thank you for your patience with this as we work to get it resolved.
