### ISSUE TITLE
Use IODA-validate to check IODA output for AMSU-A and MHS and make modification accordingly

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#765]
## Description
Run IODA-validate to check IODA output for AMSU-A (Normal/DB) and MHS (Normal/DB) and make modification accordingly
Also, change nchans to Channel and change nlocs to Location 

Working branch /feature/query_validation

**Comment by emilyhcliu** [comment]
Modifications: 
Replace nlocs with Location in src/bufr/IodaEncoder/IodaEncoder.cpp
Replace "nchans" in the YAML with "Channel" in the YAMLs

These modifications caused ctest failure in the followin tests:
	468 - test_iodaconv_bufr_mhs2ioda (Failed)
	469 - test_iodaconv_bufr_hrs2ioda (Failed)
	470 - test_iodaconv_bufr_filtering (Failed)
	471 - test_iodaconv_bufr_splitting (Failed)
	472 - test_iodaconv_bufr_filter_split (Failed)
	473 - test_iodaconv_bufr_ncep_1bamua2ioda (Failed)
	474 - test_iodaconv_bufr_ncep_esamua2ioda (Failed)
	475 - test_iodaconv_bufr_ncep_1bmhs2ioda (Failed)
	476 - test_iodaconv_bufr_ncep_esmhs2ioda (Failed)
	477 - test_iodaconv_bufr_adpsfc2ioda (Failed)
	478 - test_iodaconv_bufr_snowadpsfc2ioda (Failed)
	479 - test_iodaconv_bufr_read_2_dim_blocks (Failed)
	480 - test_iodaconv_bufr_read_wmo_radiosonde (Failed)
	481 - test_iodaconv_bufr_satwnd_old_format (Failed)
	482 - test_iodaconv_bufr_satwnd_new_format (Failed)
	483 - test_iodaconv_bufr_sevcrs_v2 (Failed)
	484 - test_iodaconv_bufr_mtiasi (Failed)

Need to update  files in the testoutput.

**Comment by huishao-r** [comment]
@emilyhcliu This issue has a merged issue #765 associated. However, #765 is about merging two branches (not into develop). I assume this is still an active issue? I moved this to "in progress". However, please close it if this is done. Thanks!
