### ISSUE TITLE
Create a new group for observation smoothing

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/ioda-converters#787]
With L2 retrieval assimilation more things than usual have to be passed to the operator.
See jedi doc https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/ufo/obsops.html#averaging-kernel-operator

The averaging kernel and a priori vector are now stored in the MetaData group but they are not meta data _per se_. They are vectors to take into account the smoothing error of the retrieval.

We would need to create a new auxiliary obs group. For example ObsSmoothing. 
If we don't want to create a new group this could go to ObsError group. It wouldn't exactly be accurate but still OK.

Opinions before we start modifying things?

**Comment by srherbener** [comment]
@jeromebarre I think it would be fine to add a new group, and I think a new group would be better than overloading the ObsError group. If others agree and you want to go that route, we should submit the new group name to the JEDI Conventions team and get it added to that documentation.
