### ISSUE TITLE
Create Subset 024 - INSAT YAML for IRLW

### ISSUE THREAD

**Issue by AshleyStanfield-NOAA** [JCSDA-internal/ioda-converters#789]
## Description
>Generate and validate INSAT IRLW YAML.

## Requirements
>Are we using the correct nomenclature?
>How does it compare before and after YAML implementation? Does it match up?
>Does it pass validation tests?

**Comment by ilianagenkova** [comment]
@AshleyStanfield-NOAA and @emilyhcliu , we don't assimilate Indian AMVs data, so NC00502* subsets don't have to be converted. 

@emilyhcliu , should @AshleyStanfield-NOAA  add you to these issues as an assignee so you could find these easier.?

**Comment by BenjaminRuston** [comment]
@AshleyStanfield-NOAA again promoting this out of `new issues`

**Comment by emilyhcliu** [comment]
@AshleyStanfield-NOAA We do not use INSAT in our operational system.  Do not need to do INSAT.

**Comment by BenjaminRuston** [comment]
closing per advice from @AshleyStanfield-NOAA , can reopen a new issue if ever needed in the future
