### ISSUE TITLE
Document how the GNSSRO flag is set by the various data providers.

### ISSUE THREAD

**Issue by fcvdb** [JCSDA-internal/ioda-converters#803]
In NOAA operational GNSSRO BUFR files, the Quality Flags for RO (QFRO descriptor 0 33 039 from Table 9 of the ROMSAF GNSSRO BUFR file [documentation](https://www.romsaf.org/romsaf_bufr.pdf) ) is coded into a 16-but integer. Setting one bit of this flag providing an indication of the quality of the occultation to which the flag is attached to. Some bits have minor meaning (eg: 7), while some others (eg: 4 & 5) could serve as the basis to reject the occultation. We would like to document, as the QFRO is used by the various centers providing operational data to NOAA. 

The objective is to create a converter, and later on a UFO filter, that is uniquely based on the QFRO flag. GSI currently uses both the QFRO flag for occultation providing by DMI and Eumetsat and the Percentage Confidence (PC) for data processed by CDAAC.

We'll be using the `gnssro_bufr2ioda.f90` program to read the NOAA BUFR files and examine the QFRO/PC flags, sort them according to the processing centers and generate graphics of the distribution.

 ### Building the ioda-bundle on s4

 See JEDI [readthedocs](jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/using/jedi_environment/modules.html?highlight=hera#s4) documentation.

 Load the JEDI stacks and modules

 ```
 module purge
  export JEDI_OPT=/data/prod/jedi/opt/modules
  module use $JEDI_OPT/modulefiles/core
  module load jedi/intel-impi
```

 Load the NOAA BUFR module (s4 only)

 `  module load  bufr/noaa-emc-11.5.0`

 Go to s4 /data dir and create a workdir

 ` cd /data/users/${USER}`

eg:

  `mkdir -p gpsro_count`

  `cd gpsro_count`

 Save the path of the topdir

  `TOP_DIR="/data/users/${USER}/gpsro_count"`

 Clone the ioda-bundle code
```

  mkdir -p src
  cd src
  git clone git@github.com:JCSDA-internal/ioda-bundle.git ioda-bundle
  cd ..
```

 Configure the bundle

```
  mkdir -p build
  cd build
  mkdir -p ioda-bundle
  cd ioda-bundle
```

`  ecbuild -DMPIEXEC_EXECUTABLE=/usr/bin/srun -DMPIEXEC_NUMPROC_FLAG="-n" -DBUILD_PYTHON_BINDINGS=ON -DBUILD_IODA_CONVERTERS=ON  ../../src/ioda-bundle `

 Compile the bundle

`  make -j4`

### 2. Prepare the data and run the gnssro_bufr2ioda converter

 Load the JEDI stacks and modules

 ```
 module purge
  export JEDI_OPT=/data/prod/jedi/opt/modules
  module use $JEDI_OPT/modulefiles/core
  module load jedi/intel-impi
```

 Load the NOAA BUFR module (s4 only)

  ` module load  bufr/noaa-emc-11.5.0
`
 Define gnssro_bufr2ioda executable here

`  gnssro_bufr2ioda="${TOP_DIR}/build/ioda-bundle/bin/gnssro_bufr2ioda"`

 Copy over BUFR data and README archived in:

`  cp -f /data/users/fvandenberghe/gpsro_count/gdasx_gpsro.20220120-29.tar .`

 Untar the NOAA BUFR gpsro data

`  tar xvf gdasx_gpsro.20220120-29.tar`

 Convert one BUFR file into one IODA file

`  ${gnssro_bufr2ioda} 2022012000 gdasx.20220120/00/gdas.t00z.gpsro.tm00.bufr_d 2022012000_gdasx_gpsro.nc4`

 Cat NOAA bufr files together

```
rm -f gdas.all.gpsro.tm00.bufr_d

for d in gdasx.*
do
  for hh in 00 06 12 18
  do
    cat ${d}/${hh}/gdas.t${hh}z.gpsro.tm00.bufr_d >> gdas.all.gpsro.tm00.bufr_d
  done
done
```

 Convert 10 days of 4 cycles into one single IODA

${gnssro_bufr2ioda} 2022012500 gdas.all.gpsro.tm00.bufr_d 20220120_29_gdasx_gpsro.nc4

 ### 3. Modify the gnssro_bufr2ioda source code

 Edit the gnssro converter Fortran program: 

  ${TOP_DIR}/src/ioda-bundle/iodaconv/src/gnssro/gnssro_bufr2ioda.f90

 Add the logic to print out the bits that make up the BUFR Quality Flags 
 for RO (descriptor 0 33 039)
 From Table 9. Quality Flags for RO Data (16-bit Flag Table) 
 of [https://www.romsaf.org/romsaf_bufr.pdf](https://www.romsaf.org/romsaf_bufr.pdf)

          call upftbv(lnbufr,nemo,qfro,mxib,ibit,nib)

          write(*,*) 'Occultation ',' ogce = ',ogce,' said = ',said,' qfro = ',qfro(1),' pcc = ',pcc

          if(nib > 0) then

            do i = 1, nib

               SELECT CASE (ibit(i))

                 CASE( 1); write(*,*) 'Non-nominal quality'
                 CASE( 2); write(*,*) 'Offline product'
                 CASE( 3); write(*,*) 'Ascending occultation'
                 CASE( 4); write(*,*) 'Excess Phase processing non-nominal'
                 CASE( 5); write(*,*) 'Bending Angle processing non-nominal'
                 CASE( 6); write(*,*) 'Refractivity processing non-nominal'
                 CASE( 7); write(*,*) 'Meteorological processing non-nominal'
                 CASE( 8); write(*,*) 'Open loop data included'
                 CASE( 9); write(*,*) 'Surface reflections detected'
                 CASE(10); write(*,*) 'L2C GNSS signals used'
                 CASE(11:13); write(*,*) 'Reserved'
                 CASE(14); write(*,*) 'Background profile non-nominal'
                 CASE(15); write(*,*) 'Background profile'
                 ! All 16 write(*,*) 'Missing'

               CASE DEFAULT
                 write(*,*) 'Unexpected value ibit = ',ibit(i)
               END SELECT

            end do

          end if

 Recompile with the command

  `cd ${TOP_DIR}/build/ioda-bundle
`
  `make gnssro_bufr2ioda`

 Rerun the converter and sort output/print-out

 ` cd ${TOP_DIR}/data`

  `${gnssro_bufr2ioda} 2022012500 gdas.all.gpsro.tm00.bufr_d 20220120_29_gdasx_gpsro.nc4`

**Comment by huishao-r** [comment]
@fcvdb Thanks for this. @haydenlj this is for the fortran decoder.

**Comment by fcvdb** [comment]
@haydenlj The tarball with the data and this README is on S4 in:

`/data/users/fvandenberghe/gpsro_count/gdasx_gpsro.20220120-29.tar `

Let me know if you have any question.

**Comment by haydenlj** [comment]
Thanks, I'll go through this. I'm hoping to have it working soon

**Comment by haydenlj** [comment]
I don't see a gnssro_bufr2ioda executable in /build/ioda-bundle/bin/  Is it called something else or have I missed something when building?

**Comment by jamiebresch** [comment]
Here is all it needs to compile `gnssro_bufr2ioda.f90`.
`ifort -o gnssro_bufr2ioda gnssro_bufr2ioda.f90 -I${NETCDF}/include -L${NETCDF}/lib -lnetcdff -lnetcdf -L${JEDI_OPT}/modules/clang-12.0.5/bufr/noaa-emc-11.5.0/lib -lbufr_d_DA`. Change `clang-12.0.5` to the compiler used on your machine, or locate the path of `libbufr_d_DA.a`.

**Comment by huishao-r** [comment]
The ioda converters for RO in python and Fortran have been updated by @haydenlj to incorporate different flags. I am closing this issue for now. Please reopen it under AOP22 if needed.
