### ISSUE TITLE
convert TROPICS satellite data to IODA

### ISSUE THREAD

**Issue by BenjaminRuston** [JCSDA-internal/ioda-converters#809]
## Description
Create a python based converter for TROPICS satellite data to IODA format

## Requirements

python h5py

## Acceptance Criteria (Definition of Done)
a successful IODA formatted output file is created

**Comment by fcvdb** [comment]
The Tropics IODA converter is in branch [https://github.com/JCSDA-internal/ioda-converters/tree/feature/tropics_satellite_ioda_converter](https://github.com/JCSDA-internal/ioda-converters/tree/feature/tropics_satellite_ioda_converter). It has been tested and will be merged soon.

**Comment by BenjaminRuston** [comment]
pull request being submitted now
