### ISSUE TITLE
Python API is producing local times instead of UTC times when writing MetaData/dateTime from python datetime objects

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#864]
The conversion path going from a python datetime object into the output ioda file is producing local times instead of UTC times.

This was discovered in #844 (ATMS converter), but is probably present in more than this one case.

## Notifications

Fill in a list of GitHub handles here. People here are not *assigned*, but instead receive notifications
about this issue's progress.

Notifications should always go to: @rhoneyager.

Other people:

**Comment by CoryMartin-NOAA** [comment]
Darn. Ok I'll take a look later today.
