### ISSUE TITLE
Upgrade converter for tropomi_no2_nc2ioda.py to follow the JEDI Data Conventions

### ISSUE THREAD

**Issue by YoulongXia-NOAA** [JCSDA-internal/ioda-converters#886]
Update the converter identified in the title (hereafter referred to as the **target converter**) to follow the JEDI Data Conventions.

- Update variable names
- Ensure variable units match the units in the conventions table
- Update the global attributes dictionary as needed
- Run the converter test to make sure it runs (but will fail because of unupdated test reference)
- Run ```ioda-validate.x``` on your output file and verify that there are no errors or warnings
- Update test reference file
- Run unit tests making use of the target converter and verify that they pass
- Make sure you verify the results by examining the file using ```ncdump -t```, ```h5dump```, ```HDFview```, or a similar application.

## ZenHub organization

Please make sure that you have properly set:
- Labels: OBS3
- Estimate: An estimate of how long this issue will take to resolve. 1 = half a day. 2 = full day. 3 = two days, 5 = three days.
- Epics: [Sprint: Implement the JEDI Data Conventions in the Converters](https://github.com/JCSDA-internal/ioda-converters/issues/813)
- Assignees: Anyone **working** on this issue. Anyone who is not working directly on the issue, but
  who should receive notifications, should be listed below.
- Reviewers

## Notifications

Fill in a list of GitHub handles here. People here are not *assigned*, but instead receive notifications
about this issue's progress.

Notifications should always go to: @rhoneyager.

Other people:

**Comment by YoulongXia-NOAA** [comment]
I am working on tropomi_no2_nc2ioda.py previously worked by Cory Martin. The first is the name. Now the converter uses 
obsvars = {
    'nitrogendioxide_tropospheric_column': 'nitrogen_dioxide_in_tropospheric_column',
    'nitrogendioxide_total_column': 'nitrogen_dioxide_in_total_column',
}

I found some references below:
https://space.oscar.wmo.int/variables/view/no2_tropospheric_column.
no2TroposphericColumn and no2TotalColumn. Or nitrogenDioxideInTroposphericColumn and nitrogenDioxideInTotalColumn??

Who has a good reference or suggestion for two variables names with this upgrade?

**Comment by YoulongXia-NOAA** [comment]
Additionally, these variables cannot be found in this table (https://docs.google.com/spreadsheets/d/1fHb2QIHOwgp4d6plyn9Dj9HZFZsDRxcPaUV6hdTb5BU/edit#gid=0). 

quality assurance value, troposphere layer index,  air mass factor total,  air mass factor troposphere, tropospheric averaging kernel precision, averaging kernel precision

These variable names need to be defined.

**Comment by YoulongXia-NOAA** [comment]
Based on the definition from https://confluence.ecmwf.int/display/ECC/WMO%3D15+element+table for averaging kernel value, we can define averagingKernelPrecision and troposphericAveragingKernelPrecision.

**Comment by YoulongXia-NOAA** [comment]
@CoryMartin-NOAA, another difficulty is  float averaging_kernel_level_1  and pressure_level_1 with many levels. Now for each level, it was defined a variable with number to represent different levels. Obviously, it should be a 2-D variable with (Location, Level). Any thoughts for this case?

**Comment by CoryMartin-NOAA** [comment]
@YoulongXia-NOAA @jeromebarre started to work on this, I think he came to the conclusion that we need the IODA Fortran API to be modified before this file can match conventions (for those levels that you just mentioned)

**Comment by YoulongXia-NOAA** [comment]
@CoryMartin-NOAA, if @jeromebarre started to work on this, I will stop to work on this converter. I still have another task. Can I close this issue?

**Comment by jeromebarre** [comment]
I will take care of this in the next months.

**Comment by jeromebarre** [comment]
> Based on the definition from https://confluence.ecmwf.int/display/ECC/WMO%3D15+element+table for averaging kernel value, we can define averagingKernelPrecision and troposphericAveragingKernelPrecision.

averagingKernelPrecision is useless in the DA framework in my opinion. Those variables should be dropped.

I provided an updated version to @rhoneyager and @gthompsnJCSDA couple of months ago but this was never updated. As far as I understand, the idea was to use the opportunity of the last code sprint to makes updates. But I think it's preferable if the table should be updated from my original suggestions.

**Comment by jeromebarre** [comment]
> @CoryMartin-NOAA, another difficulty is float averaging_kernel_level_1 and pressure_level_1 with many levels. Now for each level, it was defined a variable with number to represent different levels. Obviously, it should be a 2-D variable with (Location, Level). Any thoughts for this case?

This was the whole reason why we hold off on not updating the converters during the last code sprint. Modifications on UFO should be made to accept more than 1D arrays or flattening the AK and pressure coordinates matrices to be passed in UFO and reconstruct the in the operator. So far I don't know which solution is the best.

**Comment by jeromebarre** [comment]
To finish this issue extends to other trace gas observations with averaging kernel (so basically most of L2 products). So we should hold off creating new converters until we have solved this issue of 2D arrays.

The issue was documented before here https://github.com/JCSDA-internal/ufo/issues/1720 back in December.
