### ISSUE TITLE
Create a ioda-converters-data repo

### ISSUE THREAD

**Issue by srherbener** [JCSDA-internal/ioda-converters#892]
## Description

Currently test files are checked in and managed directly in the ioda-converters repo (like we used to do a long time ago). There are many test files now (~200MB worth) and EMC has expressed interest in tier2 testing which entails much larger test files. So, it seems that now is a good time to switch ioda converters over to our current scheme of using a companion data repo (ioda-converters-data).

## Requirements

Test files moved over to, and managed by, a new ioda-converters-data repo.

## Acceptance Criteria (Definition of Done)

ioda-converters tests all pass while utilizing the new ioda-converters-data repo.

## Dependencies

- CI testing code updated
- bundles using ioda-converters updated

**Comment by BenjaminRuston** [comment]
@srherbener going to close for now but can begin the discussion again if we feel it is needed
