### ISSUE TITLE
The MODIS AOD converter cannot be used as is. (hdf4->netcdf)

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/ioda-converters#927]
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/modis_aod2ioda.py

The currently the converter takes netcdf as input but the actual input data is hdf4.
https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/science-domain/aerosol/

I understand that IODA might not accommodate for hdf4... but with the information provided in the repo the converter is not very useful as there is no direction to make the conversion beforehand.

If this is done through a single command, this needs to be included in the python script with os.system for example.
If this involves a more complicated script this needs to be in the repo.

Thanks a lot

**Comment by mpagowski** [comment]
FYI: At GSL  use a FORTRAN MODIS converter that directly reads hdf4 ... but
writes in ioda v1.
Would it be useful to include it in the repo?

**Comment by jeromebarre** [comment]
There are tool to convert hdf4 to hdf4. It takes one line of code. e.g. https://www.hdfeos.org/software/h4toh5-def-download.php
I can succesfully convert the original modis files to hdf5 which can be read by the IODA-converter API.  
The problem is that the testinput file provided is not a straight conversion from hdf4 to hdf5 (i.e. netcdf). The groups have been removed so it lead to key error when trying to access the data. It is easy to use group with python scripts. See the other converters for example https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/mopitt_co_nc2ioda.py.

**Comment by jeromebarre** [comment]
So we need to integrate the converter script that produce to the input nc fields or add the h4toh5 binary somewhere (or at least explain this in the header comment section) but need to adapt the converter to read in the groups.

**Comment by andytangborn** [comment]
I have written a python code to convert the hdf file to the format that the ioda converter can read. The problem was that this step could not work on all of the platforms (including some laptop builds), so we decided to leave it out of the repository. Can this go into the repository without needing be part of a ctest?

**Comment by jeromebarre** [comment]
@andytangborn we need to understand why this is not working on the CI test environments provided.

**Comment by andytangborn** [comment]
The code that handles hdf is run_modis2ioda.py, which also calls the ioda converter for MODIS.  I have it in my repository: https://github.com/andytangborn/IODA-Wrappers.   I need to look back through the messages and find who had indicated that the hdf converter was not working for them.  In general, hdf is a problem to handle. Much of the information in the files is in a long text string that needed to be extracted. It took some effort to get this step to work.

**Comment by jeromebarre** [comment]
@rhoneyager @srherbener @mpagowski do you remember an issue on the git addressing this?

https://github.com/andytangborn/IODA-Wrappers/blob/4e1d2d49806d6e8b018fd4517c5684d196273598/run_modis2ioda.py#L22 call a python script on Orion which is a modified version of the IODA converter... so right now after a first glance I don't understand why all this cannot be in a single converter?

**Comment by CoryMartin-NOAA** [comment]
I seem to remember it being an issue to install whatever python library was used to convert from HDF4 to HDF5. But I'm not sure.

**Comment by jeromebarre** [comment]
The imports are the same in the header... so it shouldn't be a problem as far as I can tell.

**Comment by jeromebarre** [comment]
More importantly what lays in the JCSDA repos should be usable by anyone. This is not the case for this converter.

**Comment by andytangborn** [comment]
It can be used by anyone, once the hdf files are converted to nc.   This
was the issue before, because not everyone was able to make this step work
on their local platforms. I'm still looking for that message chain.  Daryl
also indicated that the hdf to nc step could be separated from the
converter. Give me a little while to find what was said.

**Comment by jeromebarre** [comment]
> It can be used by anyone, once the hdf files are converted to nc.

Not true... the conversion to nc is the actual problem we are discussing here...

**Comment by andytangborn** [comment]
Yes, I understand. What we need is to make that step work on any platform.
Let me update the wrapper so that it uses the latest modis ioda converter,
and you can try that.

**Comment by jeromebarre** [comment]
Discussed this @srherbener. I will create a feature branch using https://hdfeos.org/software/pyhdf.php. If this works fine we will update the containers to include the python package. pyhdf can be installed easily. https://pypi.org/project/pyhdf/

**Comment by jeromebarre** [comment]
You won't need a wrapper in the future...

**Comment by jeromebarre** [comment]
This is a different problem than what is discussed. Again this is about the **hdf4 conversion to nc, only..**.

**Comment by climbfuji** [comment]
> Discussed this @srherbener. I will create a feature branch using https://hdfeos.org/software/pyhdf.php. If this works fine we will update the containers to include the python package to pass the CI tests. pyhdf can be installed easily. https://pypi.org/project/pyhdf/

Please make sure that any change that gets merged into our repositories that adds a new software dependency is discussed with the infrastructure team first. Ideally by creating an issue in https://github.com/noaa-emc/spack-stack and referencing that issue in the corresponding PR to ioda-converters etc. Thanks!

**Comment by srherbener** [comment]
> > Discussed this @srherbener. I will create a feature branch using https://hdfeos.org/software/pyhdf.php. If this works fine we will update the containers to include the python package to pass the CI tests. pyhdf can be installed easily. https://pypi.org/project/pyhdf/
> 
> Please make sure that any change that gets merged into our repositories that adds a new software dependency is discussed with the infrastructure team first. Ideally by creating an issue in https://github.com/noaa-emc/spack-stack and referencing that issue in the corresponding PR to ioda-converters etc. Thanks!

The plan is for @jeromebarre to try out the pyhdf module (which seems the most promising way forward) in a feature branch. We would keep that solution in the feature branch (ie, not issue a PR to develop branch) until we can get the stack and containers updated. I agree that once we decide to use pyhdf (or whatever solution) we should submit an issue to spack-stack to track getting the stack and containers updated.

**Comment by climbfuji** [comment]
> > > Discussed this @srherbener. I will create a feature branch using https://hdfeos.org/software/pyhdf.php. If this works fine we will update the containers to include the python package to pass the CI tests. pyhdf can be installed easily. https://pypi.org/project/pyhdf/
> > 
> > 
> > Please make sure that any change that gets merged into our repositories that adds a new software dependency is discussed with the infrastructure team first. Ideally by creating an issue in https://github.com/noaa-emc/spack-stack and referencing that issue in the corresponding PR to ioda-converters etc. Thanks!
> 
> The plan is for @jeromebarre to try out the pyhdf module (which seems the most promising way forward) in a feature branch. We would keep that solution in the feature branch (ie, not issue a PR to develop branch) until we can get the stack and containers updated. I agree that once we decide to use pyhdf (or whatever solution) we should submit an issue to spack-stack to track getting the stack and containers updated.

Thanks, @srherbener that sounds like a good plan. One more Python dependency, yay :-) Note that we already have `h5py` just in case that library can provide the same functionality that you are looking for.

**Comment by jeromebarre** [comment]
"The h5py package is a Pythonic interface to the **HDF5** binary data format." not HDF4 unfortunately.

**Comment by jeromebarre** [comment]
Please have a look at 
https://github.com/JCSDA-internal/ioda-converters/blob/feature/modis_aod_from_h4/src/compo/modis_aod2ioda.py

this is very straightforward using the pyhdf package which is not problematic to install I think.

**Comment by srherbener** [comment]
This looks great! I suspect that pyhdf will be okay as a dependency. It's been around since 2003 and the latest update was a year ago (May 2021) so it should be mature and there is some maintenance happening. There is also decent documentation: http://fhs.github.io/pyhdf/modules/SD.html

**Comment by climbfuji** [comment]
See https://github.com/NOAA-EMC/spack-stack/issues/129.

**Comment by jeromebarre** [comment]
https://github.com/JCSDA-internal/ioda-converters/pull/942 has been merged, closing this now.
