### ISSUE TITLE
Find out how profile level LAT/LON are calculated in ADPUPA prepbufr? 

### ISSUE THREAD

**Issue by PraveenKumar-NOAA** [JCSDA-internal/ioda-converters#952]
## Description

- There are both profile level LAT/LON (YDR/XDR) and LAT/LON (YOB/XOB) in ADPUPA prepbufr data. 
- But there is no profile level LAT/LON in ADPUPA bufr dump data. 
- Profile level LAT/LON is required in ADPUPA prepbufr yaml for bufr2ioda conversion. 
- Here, I will find out how profile level LAT/LON are calculated in ADPUPA prepbufr.

## Requirements

- There is no requirement.

## Acceptance Criteria (Definition of Done)

- A formula/equation for generating profile level LAT/LON from BUFR variables. 

## Dependencies

- There are no dependencies.

**Comment by PraveenKumar-NOAA** [comment]
Created a google drive folder for the progress of this issue:
https://drive.google.com/drive/folders/184SOItgC5wFCbCRKWmIUqKI2UG-EM9oR

This folder contains Fortran subroutine and mathematical equations for the profile level LON/LAT calculation, extracted from the prepbufr codes.

**Comment by emilyhcliu** [comment]
@PraveenKumar-NOAA That's good.  Based on the information abstracted, we could implement the drift lat/lon in UFO or in BUFR converter - export/variable part.

**Comment by PraveenKumar-NOAA** [comment]
Completed, a document is written for this calculation.

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA see you re-opened this, did you want this issue or to create a new one?

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston keep it opened for sometime until I create a Python converter for the ADPUPA BUFR dump which will have profile level LAT/LON in it.

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA I used the `yaml` file from this PR on a BUFR dump `adpupa` file (NOT one output from the `split_by_subset` from a prepBUFR file) and it works

but you also want to create a python version?  Just want to make sure we don't have too many redundant converters for the `adpupa` BUFR dump,,, and the `ADPUPA` from the `split_by_subset` 

hope i am making sense
