### ISSUE TITLE
Convert prepbufr time information from DHR to standard IODA dateTime format

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#975]
## Description
Convert the prepbufr time information from DHR (hours relative to the center of analysis time) to the standard IODA dateTime format (seconds since 1970-01-01T00:00:00Z)

Thoughts:
We have the[ functionality](https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/bufr/BufrParser/Exports/Variables/DatetimeVariable.cpp) fo convert [year, month, day, hour, minute, second] into IODA dateTime variable.  The goal is to enhance this function or create a new function to convert DHR (from prepbufr) + the cycle information (provided by user: e.g. 2021101518) to [year, month, day, hour, minute, second] and then to IODA dateTime variable.

This is related to [PR 745](https://github.com/JCSDA-internal/ioda-converters/issues/975)

**Comment by PraveenKumar-NOAA** [comment]
@emilyhcliu I also have one similar issue #945 that can be linked here.

**Comment by gthompsnJCSDA** [comment]
I would like to suggest we close this issue number and consolidate it entirely within issue #945 

I will continue discussion of an idea over there.  @emilyhcliu  if you agree, would you please close this issue allowing us to move ahead with solutions in the other issue?
