### ISSUE TITLE
Create converter for TROPOMI CO

### ISSUE THREAD

**Issue by jeromebarre** [JCSDA-internal/ioda-converters#987]
Create converter for TROPOMI CO
Using template from TROPOMI NO2:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/tropomi_no2_nc2ioda.py
getting data at:
https://s5phub.copernicus.eu/dhus/#/home or eumetsat

**Comment by weiwilliam** [comment]
@jeromebarre @mer-a-o Do you have model outputs with CO on Orion? I'm preparing the GeoVals files of TROPOMI CO for UFO unit-test. Thank you.

**Comment by SarahLu-NOAA** [comment]
We can use UFS-RAQM.   Let me ping Brad.

**Comment by weiwilliam** [comment]
@SarahLu-NOAA Sure, but it would have to be in the 6-tile format, which was created in the RESTART folder generally (not sure their workflow).

**Comment by mer-a-o** [comment]
@weiwilliam yes, Orion is down today and tomorrow. I will point you to them on Friday. Meanwhile, can you use any of the files used by MOPITT CO tests?

**Comment by mer-a-o** [comment]
@weiwilliam GCHP file here also have CO fields: https://github.com/JCSDA-internal/fv3-jedi-data/tree/develop/testinput_tier_1/inputs/GEOSChem_c12

**Comment by SarahLu-NOAA** [comment]
@mer-a-o 
Are the files for MOPITT CO tests from RRFS (regional UFS with CMAQ)?   
Your CO files will work for Shih-Wei's unit test.

**Comment by mer-a-o** [comment]
@SarahLu-NOAA No, I don't think the files on ufo are model dependent? I'm talking about https://github.com/JCSDA-internal/ufo-data/blob/develop/testinput_tier_1/mopitt_co_2020090318_m.nc4
We don't have Brad's UFS-CMAQ files on Orion. They are on S4.

**Comment by weiwilliam** [comment]
@mer-a-o Thank you. I didn't notice Orion is down.
I think GCHP is a good option.
I must wait until Orion is back because my code is on Orion.

**Comment by weiwilliam** [comment]
@mer-a-o I'm not sure if that works for TROPOMI. Do they have the same footprints?
I thought GeoVals also contains the lat/lon information.

**Comment by SarahLu-NOAA** [comment]
@mer-a-o @weiwilliam 
I see - @mer-a-o  you are talking MOPITT CO obs.
I'm responding to CO model output that Shih-Wei is asking.   GEOS-Chem output will work.
@weiwilliam, We do need to use UFS-RAQMs later for the project.

**Comment by mer-a-o** [comment]
GeoVals file (out of the test) is https://github.com/JCSDA-internal/ufo-data/blob/develop/testinput_tier_1/mopitt_co_geoval_2020090318_m.nc4
https://github.com/JCSDA-internal/ufo-data/blob/develop/testinput_tier_1/mopitt_co_2020090318_m.nc4 is the input of the test?

**Comment by weiwilliam** [comment]
@mer-a-o From my understanding, I think they are inputs for UFO test of mopitt_co. And I'll need to do the same things for tropomi_co, including converted tropomi_co data and corresponding GeoVals.
Do you know what will be tested in the UFO unit-test? I suddenly get confused.

**Comment by mer-a-o** [comment]
@weiwilliam Sorry I think I'm confused myself! You are right, `mopitt_co_2020090318_m.nc4` is the obs file in ioda-format.

**Comment by weiwilliam** [comment]
@mer-a-o No problem. I'm still learning each component in JEDI, please let me know if I misunderstood anything. 🙂

**Comment by jeromebarre** [comment]
https://github.com/JCSDA-internal/ioda-converters/pull/1122 needs to be merged to close this
