### ISSUE TITLE
Missing Quality Mark for ADPSFC wind observation

### ISSUE THREAD

**Issue by emilyhcliu** [JCSDA-internal/ioda-converters#994]
The quality marker (QMWN) is missing in the [adpsfc wind YAML](https://github.com/JCSDA-internal/ioda-converters/blob/feature/query_cxx/test/testinput/bufr_ncep_adpsfc.yaml)

**Comment by nicholasesposito** [comment]
This task is being taken care of in PR #991

**Comment by nicholasesposito** [comment]
The PR has been closed and the issue fixed so this issue is now closed too.
